### ISSUE TITLE
Why ignore files for Python extensions?

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1054]
Why do we ignore certain files when activating Python extensions? If I remove the ignore statements, Spack crashes and says the file already exists, but why is this a problem? From my experience, if two packages contain the same file, it's always been identical to the original. I don't see why we can't symlink a file if it doesn't already exist, and skip it if it does. I'm currently running into problems with #1044 due to the fact that sites.py is ignored for all Python extensions.

**Comment by mathstuf** [comment]
Unfortunately, the commit history of the relevant lines isn't very informative (added at once, fiddled around with later). My guess is that projects had a habit of installing setuptools bits themselves (for whatever reason), but unless activation happens in a defined order, a package X that got activated first with old setuptools it installed, it would shadow the *real* setuptools files (and since it installs some bits, it probably doesn't `depends_on('py-setuptools')`, so it may come first too).

The exclusion for `site.py` might be able to be made more specific (in particular, by including the directory name it lives under).

**Comment by adamjstewart** [comment]
Yeah, there really isn't much documentation on how to use `ignore`. Sometimes it uses globs, sometimes it uses regex. I'm wondering how to tell it to only ignore site.py in a common directory. The one in the astropy directory obviously doesn't conflict with the one in the sncosmo directory.

**Comment by glennpj** [comment]
> I don't see why we can't symlink a file if it doesn't already exist, and skip it if it does.

As well as what @mathstuf pointed out, I think an issue would come in at deactivation time. How would spack know which package should own the symlink? Another way to look at it is, how would spack know when to remove the symlink if the package being deactivated may not be the only one to claim it.

**Comment by adamjstewart** [comment]
@glennpj Good point. I'm not sure how it currently works, but could we read the symlink and delete it if it points to a file in the deactivated package directory?

**Comment by mathstuf** [comment]
@adamjstewart But if the file is *also* provided by another package which is still activated, how do you know to put in *that* symlink?

**Comment by adamjstewart** [comment]
Well, in the case of setuptools related files, you can't deactivate setuptools without deactivating everything that depends on it, so you wouldn't need to put in any other symlink. The same would apply to numpy and astropy related files.

**Comment by mathstuf** [comment]
Here's a situation the "just skip the link if the path exists" logic would need to handle:

  - package A provides its own setuptools files (for whatever reason);
  - package B depends on setuptools;
  - package C depends on A and B.

If I activate C, I get A, setuptools, and B as well. A possible way the tree gets put together is:

  - A (which provides setuptools)
  - setuptools (skips its links because A provided them)
  - B
  - C

If I then deactivate A, C also gets deactivated, but the setuptools links also disappear. Now B is possibly broken because setuptools is basically half-activated. How would deactivate know that setuptools should replace the links that were already provided when it was activated and therefore skipped?

**Comment by adamjstewart** [comment]
Hmm, one solution to that would be to make A depend on setuptools, even if it doesn't explicitly claim to depend on it. Otherwise, yeah, there's some problems with it. Do you have any alternative suggestions for how to get sncosmo working?

**Comment by mathstuf** [comment]
Change the `site.py` regex to be `site-packages/site.py`. This should only cause top-level `site.py` files to be excluded.

**Comment by adamjstewart** [comment]
Hmm, if that's the only one preventing things from working I'll give it a shot. Does anyone know a way to deactivate all Python extensions without doing them one at a time in the perfect order over the course of an hour?

**Comment by mathstuf** [comment]
Use the output of `spack graph`?

**Comment by adamjstewart** [comment]
We still definitely need a recursive dependencies option to deactivate. Or a deactivate all option. But that should speed things up slightly.

**Comment by glennpj** [comment]
There is a `deactivate --all` option.
```
spack deactivate --help
usage: spack deactivate [-h] [-f] [-a] ...

positional arguments:
  spec         spec of package extension to deactivate.

optional arguments:
  -h, --help   show this help message and exit
  -f, --force  Run deactivation even if spec is NOT currently activated.
  -a, --all    Deactivate all extensions of an extendable package, or
               deactivate an extension AND its dependencies.
```

**Comment by adamjstewart** [comment]
@glennpj Good find! Now if only there was an `activate --all` option.

**Comment by adamjstewart** [comment]
@mathstuf: It worked!
