### ISSUE TITLE
spack not determining system type correctly

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#1075]
Sourcing `spack/share/spack/setup-env.sh` no longer loads the proper directory in `$MODULEPATH`. The reason is that the value of `_sp_sys_type` is wrong.

```
spack-python -c 'print(spack.architecture.sys_type())'
linux
```
should instead produce `linux-centos7-x86_64` on this system.

**Comment by gartung** [comment]
I disagree. All RHEL recompiles should list the system as linux-redhat...

**Comment by tgamblin** [comment]
There are actually two problems here:

1. `spack.architecture.sys_type` should probably print the default `platform-os-target` combo, instead of just the platform.
2. The Spack `linux` platform uses `platform.dist()` to figure out the distro.  I think it actually reports `centos` for CentOS, though I haven't tried.  I need to get Docker working on my mac for stuff like this...

For (2), is there a good way to get the base distro in Python?

**Comment by glennpj** [comment]
@gartung Whether the value should be `redhat` or `centos` is a different conversation. The point is that the variable is set to `linux` in the script and the modules are actually installed in

`spack/share/spack/modules/linux-centos7-x86_64`

and applications are installed in

`spack/opt/spack/linux-centos7-x86_64`

on my system.

**Comment by adamjstewart** [comment]
> For (2), is there a good way to get the base distro in Python?

We're already doing it in Spack, right? How are we doing it there? We could use [platform.linux_distribution()](https://docs.python.org/2/library/platform.html#platform.linux_distribution) but it doesn't work on macOS.

**Comment by tgamblin** [comment]
I was actually asking if you could get centos to report that it's rhel-something.  I suspect not... I agree with @gartung though that it would be useful.

**Comment by gartung** [comment]
The looks for /etc/*-release and picks the first one. On Centos distribution, there is both a centos-release and a redhat-release, but centos-release is first to the distribution is identified as centos.For the creation of binary tarballs I would prefer to use redhat for any binary compatible packages.

**Comment by gartung** [comment]
platform.mac_distribution() works for OSX.

**Comment by adamjstewart** [comment]
There is no `platform.mac_distribution()`, at least in Python 2.7

**Comment by tgamblin** [comment]
It's `platform.mac_ver`. That's what we use for OS X but we convert it to names like homebrew does.

**Comment by gartung** [comment]
Sorry, going from memory, which isn't so good anymore ;)

**Comment by mathstuf** [comment]
Also look at `/etc/os-release` which is the generally agreed-upon name to unify the `/etc/debian-release` and `/etc/redhat-release` files.

**Comment by adamjstewart** [comment]
I think it would be better to use the Python commands that we are currently using elsewhere. If we really want CentOS to be listed as RHEL, we can use a dictionary. I kinda like seeing CentOS because it's more specific.

**Comment by gartung** [comment]
I am just trying to avoid duplication of builds and binary tarballs (or rpms). If I build on a system that identifies as Redhat and someone installs on a system that identifies as CentOS then my binary tarball doesn't work because the directory name is different.

**Comment by adamjstewart** [comment]
Ah, that makes sense then.

**Comment by tgamblin** [comment]
@gartung: wouldn't it make sense, then, to alter the logic used to actually install from a binary cache, rather than the name stored in the build provenance?

I think it's useful to know that something was built on CentOS, in case that actually matters later for debugging.  But that doesn't mean we couldn't allow Spack to have looser semantics on *install*.  i.e., the user could allow using a CentOS-built binary if a RHEL one isn't available.  That would get you binary caching but it would also avoid losing information from the build.

**Comment by gartung** [comment]
@tgamblin Yes, I agree. The naming of the tarballs was already a problem because of the CentOS/Redhat naming based on available python routines.
