### ISSUE TITLE
[octave] can not install packages

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1111]
there are plenty of extension packages one can install for octave by 
```
pkg install <archive.xyz.tar>
```
however this is not possible within the current version of Octave in Spack:
```
pkg install specfun-1.1.0.tar.gz
mkoctfile: stripping disabled on this platform
make: *** [ellipj.oct] Error 1
mkoctfile -s ellipj.cc
Spack compiler must be run from Spack! Input 'SPACK_PREFIX' is missing.

pkg: error running `make' for the specfun package.
```
I suppose `octave` keeps compilers used during its build for later usage and then fails because Spack's compiler wrappers can't be used outside of spack. Any ideas how to fix it?

**Comment by adamjstewart** [comment]
From your octave installation directory, can you run the following command?
```bash
grep -R "spack\/env"
```
Sometimes there's a text file that contains the spack compilers. If it's in a binary file, then you're screwed. You may be able to contact the developers and ask them how to fix it. I had to do this for #1052.

**Comment by davydden** [comment]
could that be that the proper approach is to follow `py` and `r` languages and essentially install octave packages within spack, like `r-openssl` and alike?

**Comment by adamjstewart** [comment]
That might be a good idea.

**Comment by davydden** [comment]
@adamjstewart do you happen to know how to get a path to downloaded archive (`tar.gz`) file?

**Comment by tgamblin** [comment]
@davydden: you mean from `install()`?  `self.stage.archive_file` should work if the file's already downloaded.

**Comment by davydden** [comment]
@tgamblin thanks! Yes, that's what i was looking for...

**Comment by tgamblin** [comment]
@davydden: per @adamjstewart's comment above, I think it would be great if `octave` were extendable like `R` and `python`.  I also think ideally you could install octave extensions manually too -- if you want to.

A lot of things make this hard by referring to the compilers they were built with and assuming they can be run after installation.  Python, for instance, does this.  The tricky part is that you generally *want* the package to use Spack's compiler wrappers *within* a spack build of an extension (so that RPATHs are added), but you want to allow users to use the non-wrapped build compilers *outside* spack.  We get around this for MPI by patching its compiler wrappers and leveraging the fact that all the MPI implementations also let you inject a wrapper (look at `OMPI_CC`) in OpenMPI.  I'm not sure how you'd force this behavior from Octave.

**Comment by davydden** [comment]
@tgamblin i started fiddling with octave to make it extendable and added a single package. I can already install from bash and spack evn: 
```
$ spack env octave-specfun bash
bash-3.2$ octave --texi-macros-file=/dev/null --eval "pkg install /Users/davydden/Downloads/specfun-1.1.0.tar.gz"
```
but i still have some issues doing it within the `package.py`.  I guess i will open a WIP PR for that...

W.r.t. installing extensions manually -- so far i could not figure it out how to do this. So i would say for now the best bet is to make it extendable.

**Comment by adamjstewart** [comment]
I was thinking about adding a Matlab package at some point so if I ever get around to it I'll try to follow your steps to make it extendable.
