### ISSUE TITLE
[Proposal] : add a hierarchy to user configuration files

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1115]
Currently spack configuration files that are `--user` stored are directly saved into `~/.spack/`. When changes that modify the format of any of the configuration file are merged (for instace #561), this causes conflicts for users that want to try out the new version, but still rely on the old release for stability.

A simple way to avoid this is to increase spack version number any time that it is considered sensible and store more than one set of configuration files:

```
~/.spack/0.8/
~/.spack/0.9/
...
```

spack should also ask whether a user wants to import configuration files from an older version on first use.

**Comment by tgamblin** [comment]
@alalazo: I kind of like the sentiment but I'd really like to limit the amount of complexity here.  The intent is to disturb the config files as little as possible, and ideally in the long-term I'd like the user not to have to worry much about the format of config files in `~/.spack` and `etc/spack`.  Merging `newarch` was kind of an exception.  The change to `compilers.yaml` there is intended to make it *more* extensible in future releases so we don't have to do this again.  The inherent hierarchy in the original `compilers.yaml` made it hard to extend.  But I do see the obvious usefulness here.  It would be nice to be able to do it.

Thoughts:
1. This is hard to implement after-the-fact, because we can't go back and, e.g., inject stuff into 0.8 commits to make them look at the right config files.  

1. We *can* do patch releases onto master, though, with a backport of the necessary functionality to prefer different config files.  That might be a good option, but you obviously couldn't check out any old commit -- you'd need to use the point release.  Seem reasonable?

1. Rigidly enforcing a hierarchy like this is likely going to cause Spack to have *lots* of versioned config directories.  I don't want to tie the version to the config format; I'd rather tie it to features.  If we tie it to features, in the long term all the config files are going to contain copies of the same thing, with older versions containing stale configs.

1. What if we allow but do not require per-version config directories.  Proposed policy:
  1. On incompatible upgrade, Spack backs up incompatible configs to a `~/.spack/spack-<previous version>` directory.  Config format changes *will* require version updates, but are not the only thing that can trigger version updates (e.g., a new feature could, as well).
  1. If any versioned config directory is *higher* than the spack version number at runtime, Spack will use the next-highest versioned config directory (e.g., `v0.7.1` will use `~/.spack/0.8` if `~/.spack/0.7.5`, `~/.spack/0.8/` and `~/.spack/0.9/` exist).
  1. If Spack's version is newer than the latest versioned config directory, it will use the top-level configs as it currently does (`~/.spack/*.yaml`)

1. This doesn't solve the whole problem -- the install DB is also versioned and might benefit from something like this, but I `reindex` solves the problem there already (although it's not ideal).

Thoughts?

**Comment by citibeth** [comment]
I lean toward @tgamblin here.  Spack is Alpha, we have to deal with it.  Once Spack is closer to production, we can revisit the issue, if it seems that file formats will be changing all the time.

**Comment by alalazo** [comment]
@tgamblin 
> This is hard to implement after-the-fact, because we can't go back and, e.g., inject stuff into 0.8 commits to make them look at the right config files.

Sorry, I just made a poor choiche for the version numbers in my example : I just wanted to show an example with two random numbers, but it seems I randomly chose the last two released versions of `spack`. :smile: 

Bottomline : there's no need for me to backport a solution to this and I can live with manual tweaking of the config files for the time being. It was more to point out something that could bite us another time in the future.

> What if we allow but do not require per-version config directories.

The only objection I have against the policy you propose is that the versioning number is counter-intuitive. What if we : 
- use only `{version.major}.{version.minor}` for config directories 
- update at least `version.minor` when we break config format

Regarding : 

> Rigidly enforcing a hierarchy like this is likely going to cause Spack to have lots of versioned config directories. I don't want to tie the version to the config format; I'd rather tie it to features. If we tie it to features, in the long term all the config files are going to contain copies of the same thing, with older versions containing stale configs.

we may maintain the information on configuration format somewhere, and just link an older config directory if there was no format change, like : 
```
~/.spack/1.7
~/.spack/1.8 -> ~/.spack/1.7 # Minor version upgrade that doesn't break config format
```
What do you think ?

**Comment by citibeth** [comment]
> What do you think ?

I agree with Todd that this is problematic.  The fundamental problem here
is that ~/.spack/ is a global variable, and we need things on a per-Spack
instance basis.

Let me suggest another approach to finding configuration files, instead of
looking for ~/.spack/: starting from a start directory, look for a
directory named 'spack.config/' (or maybe spack.conf).  If you find it,
great; if not, look for '../spack.config/', '../../spack.config/', etc. all
the way to the root of the filesystem.

The start directory could be the root of the Spack being run.  This allows
users a lot of flexibility in setting up their Spack configuration:

 a) I can just put it in ..../spack/spack.config/, if I don't mind mixing
config files with git-cloned files.  I could even put spack.config in my
own fork, to get a pre-configured Spack.

 b) If I DO mind mixing config files with git-cloned files, I could put my
Spack installation one directory down, and then put spack.config just above
it.  For example:
     ..../myspacks
          spack1/
          spack2/
          spack.config/
  In this case, spack1/ and spack2/ would all have to use compatible
spack.config/ format.

  c) If I want to have a lot of Spacks installed, with different versions,
I can install them in different sube-directories on a per-version basis.
This is most semantically similar to the current proposal for version
numbers; but it's completely optional, and requires no code in Spack to
make it work.  For example:
      .../spacks-1.7/
          spack1/
          spack2/
          spack.config/
      .../spacks-1.8/
          spack3/
          spack4/
          spack.config/

Of course, there is supposed to be a HIERARCHY of spack configurations, not
just a single one.  Hierarchy can/should be added to the above approach as
follows:

    a) Once you've found a spack.config/ directory, should you stop
looking?  Or should you look further up the directory hierarchy for more
basic spack.config/ directories?  The most flexible answer would be to look
further up or not, according to the contents of the first spack.confg/ you
found.  For example, I could do:
    ~/
        spack.config/           # user-level Spack configuration
        spacks/
            spack1/
                spack.config/      # Configs specific to spack1
            spack2/
                spack.config/       # Configs specific to spack2

    b) There can/should be multiple search roots.  For example, ~ should
probably be a search root, as well as the Spack root.  Alternately, use
just the Spack root as a search root, but specifiy additional  searhc roots
on the Spack command line.  This allows per-application Spack configs.  For
example.... I'm building package A and package B within the same Spack.  I
need one spack.config/packages.yaml for package A and another
spack.config/packages.yaml for package B. So I set up AppA/spack.config and
AppB/spack.config, and point Spack to those two directories as appropriate.

OK, enough.  I've used this approach before (on a smaller scale), see
below.  This allows me to make an "ectl" directroy tree wherever I like,
not just in the ectl install directory.  (Similar approach could be used to
separate Spack's install/whatever directories from the main Spack tree).
See line 54:

      ectl_conf = pathutil.search_up(start_path, lambda path:
pathutil.has_file(path, 'ectl.conf'))

https://github.com/citibeth/ectl/blob/master/lib/ectl/config.py

(In this case, the file etl.conf contains nothing, it's just a marker in
the filesystem.  That might change in the future).

-- Elizabeth


On Wed, Jul 6, 2016 at 6:40 AM, Massimiliano Culpo <notifications@github.com

**Comment by alalazo** [comment]
> I agree with Todd that this is problematic.  The fundamental problem here
is that ~/.spack/ is a global variable, and we need things on a per-Spack
instance basis

per spack configuration are in `<spack-checkout-dir>/etc/spack` and I have no issues with those. The problem here is with `user` (right now) or `system` (in the future, see discussion in #1127) wide configurations that are shared among multiple spack instances.

**Comment by citibeth** [comment]
>
> per spack configuration are in <spack-checkout-dir>/etc/spack and I have
> no issues with those. The problem here is with user (right now) or system
> (in the future, see discussion in #1127
> <https://github.com/LLNL/spack/issues/1127>) wide configurations that are
> shared among multiple spack instances.
>

The system of scopes is complex and brittle.  And it leads to discussions
like the on on this thread.  The scheme I outline is simpler to implement
and more flexible for the user.  AFAIK, all use cases discussed so far can
be implemented with it.

**Comment by alalazo** [comment]
I'll close the issue for now as the configuration system underwent a lot of improvements that could resolve this use case (configuration files hierarchies).
