### ISSUE TITLE
[build location] use /spack/var/stage directly without symlinking from /tmp

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1137]
often one would like to keep sources of packages so that in case there is  segmentation fault somewhere it is possible to debug and check which line in source file of packages fails, get proper backtraces in a debugger. Currently one can keep the sources after successful install, but they will still be deleted after restart as location is temporary.

I think this issues can be resolved rather easy if instead of creating a temporary system-dependent folder and then symlinking into `/spack/var/stage/`, one could directly unarchive sources and compile inside `/spack/var/stage` and keep them there if needed. This could be controlled by a global or per-install flag.

**Comment by davydden** [comment]
p.s. in reference to the discussion here https://github.com/dealii/dealii/issues/2728
p.p.s. [homebrew guys decided that this is a wontfix issue](https://github.com/Homebrew/legacy-homebrew/issues/45722), but i still believe this is a good feature to have.

**Comment by tgamblin** [comment]
> often one would like to keep sources of packages so that in case there is segmentation fault somewhere it is possible to debug and check which line in source file of packages fails, get proper backtraces in a debugger. Currently one can keep the sources after successful install, but they will still be deleted after restart as location is temporary.

In `__init__.py`, set `use_tmp_stage` to `False`:

```python
# Whether to build in tmp space or directly in the stage_path.                                                      
# If this is true, then spack will make stage directories in                                                        
# a tmp filesystem, and it will symlink them into stage_path.                                                       
use_tmp_stage = True   
```

That will go into a larger `config.yaml` once I get to @hegner's PR.

You may be interested to know that @mplegendre has looked into how we might keep source around in the install directory for use for debugging later.  You could do this two ways:

1. Actually build out of `$prefix/.spack/src` or something similar.  This has the disadvantage that `$prefix` might be on a slow network filesystem.  It has the advantage that it would be easier to keep around generated source code.
1. Build in `tmp` as we do now, but use a path in `$tmp` at least as long as `$prefix`.  Patch the `DWARF` info in the binary file after the fact to point at `$prefix/.spack/src`.  Has the advantage the the preserved source is complete and comprehensive, except for any generated source.
1. Build in `tmp` as we do now, then scan the binary for debug information after the build, and copy any files into `$prefix/.spack/src`.  Generates everything you need for debugging, but you still need to copy the rest of the pristine source to `$prefix/.spack/src`, so that a user could more easily examine it and make sense out of it.

I believe @mplegendre was at one point going to try (2) above.

**Comment by davydden** [comment]
@tgamblin good to know that there are already solutions on how to keep build folder non-temp. I look forward to an option in `config.yaml` for that.

W.r.t. the ways to keep sources, (1) appears not to be the best solution. I will be happy to test either (2) or (3) when/if there are in the PR state.

**Comment by citibeth** [comment]
I think (2) sounds the most promising as well.  Two thoughts:

1. Would PatchELF be useful here?  I believe it's already in the Spack repo.
       https://nixos.org/patchelf.html

1. How would this work for non-ELF stuff?  For example... Java code?  Maybe that's not a big issue right now, since most of what we use is either binary or source-in-install (Python, R, etc).

**Comment by eschnett** [comment]
Patching Dwarf sounds tedious. Will this work on OS X? Will it work for Julia that downloads tarballs, patches them, builds them, and then installs the resulting libraries?

Maybe there can be an option allowing people to choose between (1) and (2)? (1) seems so simple that it appears to be almost trivial to support.

**Comment by robertdfrench** [comment]
Being able to build in a user-defined directory is a win for us, because the Cray login nodes will pass out if /tmp gets full.

**Comment by davydden** [comment]
this is implemented now `config.yaml` can have
```
config:
  install_tree: $spack/opt/spack
  module_roots:
    lmod:   $spack/share/spack/lmod
  build_stage:
    - $tempdir
    - /nfs/tmp2/$user
```
see http://spack.readthedocs.io/en/latest/configuration.html
