### ISSUE TITLE
MPI defaults to intel-parallel-studio, BLAS/LAPACK defaults to Atlas

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1300]
Is this change intentional? I don't know much about BLAS/LAPACK, but I thought OpenBLAS (the previous default) was a bit faster than Atlas.

**Comment by davydden** [comment]
maybe because it starts with letter `a`? I wonder where the default order for virtual dependencies is set? I don't think it is mentioned in documentation.

**Comment by tgamblin** [comment]
not intentional but could have to do with #1229.  I think we are starting to need something like what I described in #1286

**Comment by adamjstewart** [comment]
@tgamblin I agree. Spack should maintain an ordered list of the preferred BLAS/LAPACK provider, MPI provider, etc. As for which ones should be the default, I'm going to avoid that flame war altogether.

**Comment by tgamblin** [comment]
@adamjstewart: the idea would be that there would be Spack defaults that ship out of the box, and then sites could override the site default, and users could override that.  Hopefully that keeps us far enough away from the flames.

**Comment by tgamblin** [comment]
@adamjstewart: to further stay out of the fire, note that for #1286 (and I think I've mentioned this on telcons too), there are platform-specific defaults.  I think that is enough room for sensible defaults.

**Comment by adamjstewart** [comment]
Maybe more of a concern, MPI now defaults to intel-parallel-studio, which can't be installed without downloading manually.

**Comment by davydden** [comment]
can we have a quick fix for that before a proper one with different presets for different platforms? I think this is a big issue which may detract new users: they try install anything with mpi and it does not work. They may not bother to read how to specify which mpi to use  because the first impression of Spack will be negative. Same applies to Atlas, which  (i) does not like clang and does not build on macOS AFAIR (ii) is not tested much. Without this PR https://github.com/LLNL/spack/pull/1243 there certainly will be problems as of the current state.

I would suggest for now to somewhat force `openmpi` and `openblas` to be defaults so that things work, at least.

**Comment by adamjstewart** [comment]
For others reading this issue, this `~/.spack/packages.yaml` solves the problem temporarily:
```
packages:
  all:
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
```
but I agree that we need to fix the default for all Spack users.

**Comment by adamjstewart** [comment]
Resolved by #1309

**Comment by tgamblin** [comment]
Just to add in case anyone looks at this, #1309 uses @adamjstewart's settings above.

**Comment by adamjstewart** [comment]
Haha, no reason to use my settings, don't put the blame on me :P

Maybe we should vote on what packages should be the default? For example, almost none of my users are using openmpi. We use mvapich2 and mpich at ANL.

**Comment by tgamblin** [comment]
Honestly, I think the settings above are the sensible defaults.  Sites can customize so I don't think we need to worry too much about this.  On particular platforms there will likely be other defaults that make sense -- we can have subdirectories of the defaults directory that override the top-level file for those.
