### ISSUE TITLE
OpenSSL checks are too slow

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#1332]
I often work on systems that can't see the outside world.  On such systems, everytime spack queries the OpenSSL package, a 2 minute delay is added to my command.  For example:

```
% time spack spec openssl%intel@16.0.3
<output trimmed>
==> Warning: This installation depends on an old version of OpenSSL, which may have known security issues. 
==> Warning: Consider updating to the latest version of this package.
==> Warning: More details at http://www.openssl.org
<output trimmed>

real	2m9.064s
user	0m0.632s
sys	0m0.216s
```

Also:

```
% spack -p spec openssl%intel@16.0.3
  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1  127.316  127.316  127.316  127.316 {method 'connect' of '_socket.socket' objects}
        3    0.689    0.230    0.689    0.230 {built-in method poll}
<output trimmed>
  
```

Is there any way to disable this check? or make it time-out after 15-20 seconds?  For now, I just comment out this section of openssl/package.py.

**Comment by adamjstewart** [comment]
Even when you are connected to the outside world this check can cause a noticeable slowdown. How necessary is it? Could we just remove all old versions of OpenSSL from the package and call it good enough? @alalazo @citibeth

**Comment by tgamblin** [comment]
I really want to remove this check.  It adds time to anything that uses the spec, and it gets executed for commands that don't need it like `spack spec`.  I don't think the benefits outweigh the cost.  I think users need to be responsible for pulling their own updates, at least until we can do something better.  I also don't know of another package manager that pings the OpenSSL site like this.

**Comment by citibeth** [comment]
I agree 100% with Todd.

We've discussed possible better things in the past --- how to deprecate
outdated/insecure packages, remove them from the Spack installation, and
then rebuild around them.  It brings up a lot of thorny issues.  I don't
think that in the OpenSSL package is the right place to tackle them.

Also... packages should never have to download stuff.  In case they do need
to download stuff, you should make two packages: package (a) downloads the
stuff and "installs" by copying the tarballs, then package (b) uses the
tarballs from package (a).  Then make (b) depend on (a).

**Comment by tgamblin** [comment]
I think the right place for a check like this would be as a phase of some sort in @alalazo's #1186 PR, preferably one that is disable-able in a config file somewhere.  Right now it's sort of instrumented into `url_for_version`, which is the wrong place for it.  I'll make a PR to get rid of the check and we can talk about where it might make sense to put it back.

**Comment by tgamblin** [comment]
@KineticTheory: if you want to override this in the meantime you can change `url_for_version` to `_url_for_version` in `var/spack/repos/builtin/packages/openssl/package.py`

**Comment by tgamblin** [comment]
Another idea: we could easily give packages a method to execute when fetch fails, rather than always doing something *before* fetch in `url_for_version`.  This would at least give you a place to tell the user what to do when it can't find the package anywhere.  In the case of OpenSSL, it usually means something's been updated.

This would stay out of the way of users who use mirroring (their fetch won't fail, and they won't be delayed by a ping) but it would give a better warning than "all fetchers failed" when what's really happened is that OpenSSL has gotten a security update.

Thoughts?

**Comment by citibeth** [comment]
> Thoughts?

I believe the OpenSSL check did more than that.  It would warn you if an
ALREADY INSTALLED instance of OpenSSL is out of date.  I think the packages
are just the wrong, wrong, wrong place for this stuff.

The "right" way, I believe, is a little more global:

 1. Have a way to identify which package@versions are deprecated.  This
could vary depending on the package.  For example, for OpenSSL it might
involve looking at tarballs on the website.  For other packages, it might
involve having someone follow security advisories.  Collect deprecated
package@versions in a database somewhere.

 2. Given the deprecation database, have a way to check Spack against it.
 "Do something" for all installed specs involving software found in that
database.  (For example, "do something" might be uninstall.  Or it might
not.  Also, in real life there are different degrees of security alerts,
which might warrant different behavior).

 3. Figure out how to re-install all the software that was just uninstalled
due to security problems.


None of these steps are particularly easy.  What we have right now is an
ad-hoc equivalent to this databse, in which (a) only OpenSSL is tracked,
and (b) "do something" means warn the user any time Spack is run.  We can
do better.

I will re-iterate that I believe this kind of checking in the package is
just wrong.  There are many ways we MIGHT discover a package has been
deprecated, looking for missing tarballs is just one way.

-- Elizabeth

**Comment by citibeth** [comment]
One other thought... OpenSSL in particular has a really static API, and
updates are pretty much only due to security.  It's the kind of package
where it makes a lot of sense to use the system-installed OpenSSL, and let
the OS deal with updates.

**Comment by tgamblin** [comment]
With the recently added #1309, we can actually default to the system OpenSSL out of the box, so there is that.  Once I get per-platform ones in place we could do something smart for different host OSes.

**Comment by adamjstewart** [comment]
I would be fine with a system OpenSSL. What if we just got rid of the OpenSSL package and removed all dependencies to it? Would there be any foreseeable consequences?

**Comment by tgamblin** [comment]
@adamjstewart: you couldn't install your own OpenSSL.

**Comment by citibeth** [comment]
I've encountered systems that are so old, they cannot connect to modern SSL
websites.  So curl doesn't work, meaning Spack doesn't work.  On these
systems, it is necessary to bootstrap Spack by installing your own curl
with your own OpenSSL.

**Comment by alalazo** [comment]
Just for the context, I added the logic in `url_for_version` in #422 out of concern from other users (if I remember well mainly @mathstuf ). If it is fine with them, it is fine with me too. 

Currently at our site we use `@system` with a properly configured `packages.yaml` and #1167 to keep track in the DB of the external package.

**Comment by alalazo** [comment]
> I would be fine with a system OpenSSL. What if we just got rid of the OpenSSL package and removed all dependencies to it? Would there be any foreseeable consequences?

Ahem #1325 is just around the corner...

**Comment by tgamblin** [comment]
I'm not ignoring #1325 I promise!
