### ISSUE TITLE
Missing dependencies in spec.yaml

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1498]
So I recently updated Spack to cfde03e694b05a2aec315e0821fa82dc1e4b12c7 and installed a couple packages. Then I switched back to a slightly older branch (3ea13256205524c0a40612b712536ebea626472c) and all of a sudden Spack no longer works:

```
$ spack deactivate py-matplotlib@1.5.1~gui
==> Error: Unable to read file: /blues/gpfs/home/software/spack-0.9.1/opt/spack/linux-centos6-x86_64/intel-16.0.3/libsigsegv-2.10-fzppdolwulhgvv63qw5vh5t4fivvb66i/.spack/spec.yaml
Cause: 'dependencies'
```

The only difference between the spec.yaml for this libsigsegv that I installed on cfde03e694b05a2aec315e0821fa82dc1e4b12c7 and older libsigsegv spec.yaml's is that it is missing a `dependencies: {}` tag. Did we recently change the spec.yaml format to not include the dependencies tag if it is empty?

**Comment by tgamblin** [comment]
Yes, this was intended to make specs smaller -- it was actually only intended to affect abstract specs, but the dependencies field does indeed affect concrete ones.  Rebasing that branch should fix it, but there might be some inadvertent rebuilding due to the hash change.

Sorry for the oversight -- I am actually trying to bundle hash changes together and would like to put some regression tests in for things like this so that we don't change the hashes too frequently.  There are a couple more hash changes coming down the line, so maybe I should get them in soon so that they all come at once.  Would you like the `dependencies` field to be put *back* in until we do the other changes?

**Comment by adamjstewart** [comment]
I don't care about the dependencies field, I was just shocked to see that Spack was no longer compatible with 2 different branches.

As I mentioned in #1325, changes that make Spack no longer backwards compatible should probably be saved up until they reach critical mass, then added into a release branch, forcing a new release. Most software doesn't break backward compatibility without changing the major version. I know Spack is still very much beta software, but we should at least increment the minor version.

I've said it before, but I still don't know what is in the hash that isn't in the spec.yaml file. If there's something that is missing, surely we could add it. Otherwise, every time the hash changes, every single user needs to reinstall Spack. Since the hash is in the installation directory, there's no way to change it post-install. If all of the necessary information were in the spec.yaml file, it wouldn't force me to reinstall Spack and all of my packages.

You still haven't commented on #1325. Do you have any opinions on that? You can't avoid it forever :stuck_out_tongue:

**Comment by tgamblin** [comment]
> changes that make Spack no longer backwards compatible should probably be saved up until they reach critical mass

Technically this is a change that breaks _forward_ compatibility of old versions.

> I've said it before, but I still don't know what is in the hash that isn't in the spec.yaml file.

I guess I don't understand this one.  There's nothing in the hash that isn't in the `spec.yaml` file.  I should probably document all this, but one key design point is that hashes of already-installed packages won't change.  This is for reproducibility, and so that you can continue to refer to installed packages with the _same_ hash.  The way this is implemented is that the `spec.yaml` file actually stores the hash as computed at install time, and when Spack reads something in, it remembers its hash and trusts what is in `spec.yaml`, _even_ if the current set of inputs to the hash would generate a different value.

That _doesn't_ mean that the new version of Spack won't generate a different hash for essentially the same build, if it has to install it again.  This is why you get rebuilds -- dependency computation is done without looking for matches among the installed specs.  We only reuse exact hash matches right now; we don't check during concretization whether any installed spec `satisfies` the requested spec, so when the hash changes you can't reuse what's already there.  That said, you should be able to force a build to reuse an existing spec (assuming there are no unsatisfiable constraints) with, e.g.:

    spack install foo ^/abc123

That says use _exactly abc123_ as a dependency.  Does this work for you?  You should always be able to refer to existing specs by the hash they were installed with.  Two issues (#1409, #1469/#1377) currently make that less useful than it should be.

So back to `spec.yaml`.  The issue is that sometimes we have to change the `spec.yaml` format for new features like dependency types, additional arguments, etc. because the old "format" can't express the new feature.  It's hard to make old versions understand the new format, but I _have_ actually put code in that ensure that _new_ versions are backward compatible with old specs.  We actually check 3 different ways for variants to be represented in order to handle this.

I'll go over to #1325 now.  I might reuse some of the text above there.
