### ISSUE TITLE
clang as CPP for Fortran and compiler wrappers

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1647]
i recently came across `-Werror=line-truncation` issues when compiling two packages in Spack with `clang+gfortran` (see below). One of them is `ape`, both [Homebrew](https://github.com/Homebrew/homebrew-science/blob/master/atomic-pseudopotential-engine.rb) and [Macports](https://trac.macports.org/browser/trunk/dports/science/ape/Portfile) don't set any special flags during configure. As a matter of fact, i contributed `ape` to Homebrew and did not have any problems building it at that time. This makes me believe that the issue could be related to compiler wrappers in Spack.

In APE's mailing list it was suggested that

> the problem is not with the not the
Fortran compiler, but rather the C preprocessor. It seems the CFLAGS
macro was not replaced by it's appropriate value, probably because "//"
indicates a C++ comment (in Fortran "//" is a string concatenation
operator).

Logs for both packages show the same flags `-E -x c -ansi`. Here's an excerpt from the configure
```
checking whether /Users/davydden/spack/lib/spack/env/clang/clang -E is usable for Fortran preprocessing... preprocessor cannot be run
checking whether /Users/davydden/spack/lib/spack/env/clang/clang -E -x c is usable for Fortran preprocessing... preprocessor mangles C++ style comment
checking whether /Users/davydden/spack/lib/spack/env/clang/clang -E -x c -ansi is usable for Fortran preprocessing... yes
```
On [this page](http://www.tddft.org/programs/octopus/wiki/index.php/Preprocessors) there is an m4 macro used to get flags.

I am somewhat suspicious by the fact that `-x c` is there as at least for [LLVM](http://clang.llvm.org/docs/CommandGuide/clang.html)
> -x <language>
Treat subsequent input files as having type language.

Would appreciate of someone who knows well compiler wrappers' code could comment on this issue.

---

p.s. I must tell that both issues disappear when `-ffree-line-length-none` flag is set

> -ffree-line-length-n
Set column after which characters are ignored in typical free-form lines in the source file. The default value is 132. n may be ‘none’, meaning that the entire line is meaningful. -ffree-line-length-0 means the same thing as -ffree-line-length-none.

but I am not sure anymore that this is the right solution.

----

1) ape
```
/Users/davydden/spack/lib/spack/env/clang/clang -E -x c -ansi  -I../liboct_parser -I../libstring_f -I../src -I../src -I. ape.F90 > ape_ape.f90
/Users/davydden/spack/lib/spack/env/clang/gfortran -g -O2 -I /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/libxc-2.2.2-ovavb5bmxo3o63ccr4gp6fayscvdpcyw/include    -I ../src -c  -o ape.o ape_ape.f90
ape.F90:68:132:

  message(6) = "  C compiler flags: "// CFLAGS
                                                                                                                                   1
Error: Line truncated at (1) [-Werror=line-truncation]
ape.F90:68:41:

  message(6) = "  C compiler flags: "// CFLAGS
                                        1
Error: Unterminated character constant beginning at (1)
f951: some warnings being treated as errors
make[2]: *** [ape.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

2) octopus
```
/Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/openmpi-2.0.0-6uy66j3mu3rsjoiauplx556zsr7yzaon/bin/mpicc -E -x c -ansi  -I../../src/include -I../../src/include -I../../external_libs/spglib-1.5.2/src -I../../liboct_parser -I/Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/gsl-2.1-ff4bai6puh25vcodlowkim6tl5w75fbd/include  -DSHARE_OCTOPUS='"/Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/octopus-5.0.1-jo7vq4dzll22s7sh5nillplc3fvc7wn6/share/octopus"' -I../../external_libs/metis-5.1/include/ -I. global.F90 > global_oct.f90
../../build/preprocess.pl global_oct.f90 \
	  "" "yes" "yes"
/Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/openmpi-2.0.0-6uy66j3mu3rsjoiauplx556zsr7yzaon/bin/mpif90 -O2 -I /Users/davydden/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/libxc-2.2.2-lprcrjphgengbwdlxtbcud3newxaxg6d/include         -I ../../src/basic -I ../../src/math -I ../../src/species -I ../../src/ions -I ../../src/grid -I ../../src/poisson -I ../../src/states -I ../../src/frozen -I ../../src/xc -I ../../src/system -I ../../src/hamiltonian -I ../../src/scf -I ../../src/td -I ../../src/opt_control -I ../../src/sternheimer -I ../../external_libs/qshep -I ../../external_libs/bpdn -I ../../external_libs/spglib-1.5.2/src  -I ../../external_libs/newuoa -c  -o global.o global_oct.f90
global.F90:157:132:


      conf%share = SHARE_OCTOPUS
                                                                                                                                   1
Error: Line truncated at (1) [-Werror=line-truncation]
global.F90:157:20:

      conf%share = SHARE_OCTOPUS
                   1
Error: Unterminated character constant beginning at (1)
global.F90:162:132:

    conf%cc         = CC
                                                                                                                                   1
Error: Line truncated at (1) [-Werror=line-truncation]
global.F90:162:15:

    conf%cc         = CC
              1
Error: Unterminated character constant beginning at (1)
global.F90:166:132:

    conf%fc         = FC
                                                                                                                                   1
Error: Line truncated at (1) [-Werror=line-truncation]
global.F90:166:15:

    conf%fc         = FC
              1
Error: Unterminated character constant beginning at (1)
f951: some warnings being treated as errors
```

**Comment by citibeth** [comment]
Why are these packages running `cpp` themselves?  GFortran already does this for .F90 files (note capitalization).

https://gcc.gnu.org/onlinedocs/gfortran/Preprocessing-Options.html
https://gcc.gnu.org/onlinedocs/gfortran/Preprocessing-and-conditional-compilation.html#Preprocessing-and-conditional-compilation

**Comment by davydden** [comment]
> Why are these packages running cpp themselves?

no idea.

**Comment by citibeth** [comment]
> p.s. I must tell that both issues disappear when -ffree-line-length-none flag is set
> but I am not sure anymore that this is the right solution.

I think this is the most expedient solution.  It's a lot easier than either the mixed C/Fortran solution, or patching the source.  I would not blithely add `-ffree-line-length-none` to all programs.  But now that I think I understand your issue, I see no downside in this case.

See below for more details...

> the problem is not with the not the
> Fortran compiler, but rather the C preprocessor. It seems the CFLAGS
> macro was not replaced by it's appropriate value, probably because "//"
> indicates a C++ comment (in Fortran "//" is a string concatenation
> operator).

I don't believe this, because your line truncation error would make no sense in that case.  What I think is REALLY going on is... the preprocessor IS expanding the macro, and the result is >132 chars.  CFLAGS is #defined as a quoted string.  And with it now too long, it looks to the compiler like a non-terminated string constant.  That is a hazard of using CPP macros in Fortran.

So why is it too long for you, but others got away with it?  I'll bet that the Spack-generated CFLAGS is super-long due to long Spack paths.

Patch the Source
------------------

The fix?  Think about it... the upstream authors created a line in Fortran that is guaranteed to break if you compile it with long paths.  I think the best fix would be upstream.  I understand the urge to print this stuff out when you launch.  But it doesn't make so much sense in Spack land because (1) Spack already keeps provenance information for everything it builds, and (2) Nobody knows what CFLAGS are set to anyway, we care more about variants.  Printing out the (fixed-length) Spack hash would be about as useful.

Or launch Ape/Octopus with scripts that copy the Spack provenance info into your output directory upon startup, and then you don't have to print anything.

If you want to go that route, I'd just make a Spack patch file to disable/remove the offending line with CFLAGS (and any other macros obtained from the build environment that are now too long).

Mixed C/Fortran
----------------

Yet another possibility would be to use the power of C to properly compile these long strings.  For example, make a file "cmacros.c" something like:

char *cflags_macro = CFLAGS;
char *share_octopus_macro = SHARE_OCTOPUS;
...etc...

Then use Fortran/C interop to access those symbols from the Fortran side.

https://gcc.gnu.org/onlinedocs/gfortran/Interoperable-Subroutines-and-Functions.html#Interoperable-Subroutines-and-Functions

Is this worth the effort?  I dunno...  depends on how much I care about those lines coming out of Ape/Octopus.

**Comment by alalazo** [comment]
@davydden This error already occurred to me a couple of time, the most recent being molpro. My bet on the culprit : the C preprocessor is used to produce a FORTRAN file containing log messages. Among the things that are logged there is the installation prefix and THAT is longer than the 132 allowed characters... 

Just in case, I solved the issue both time using `-ffree-line-length-none`

**Comment by eschnett** [comment]
Modern C preprocessors perform a number of source code transformations that are illegal in Fortran. They might collapse whitespace sequences to a single blank (breaks fixed format), reformat floating-point numbers (breaks using dot-delimted operators, and using floating-point numbers using `d` for the exponent), and some more.

With GCC, the usual remedy is to use the `cpp` option `-traditional`. I don't know what is necessary to make Clang's cpp behave well for Fortran.

In any way, this should probably be documented somewhere, and having an environment variable `FPPFLAGS` set by Spack that one can use in such package might be a good idea. For GCC, `FPPFLAGS = -traditional`.

**Comment by davydden** [comment]
@citibeth @alalazo Thanks a lot for your explanation. This makes perfect sense now. I will notify upstream about this issue.

@eschnett maybe another propertly like [openmp_flags](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/compilers/gcc.py#L56-L58). I am not sure though such flags exist for all compilers. I did not see anything like this for `clang` at LLVM page above.

**Comment by davydden** [comment]
i notified developers of both `ape` and `ocotpus` and will close this for now as the issue is not with Spack or particular preprocessor used. As a matter of fact, now I recall that it happens both on mac and ubutnu, which it should.

@eschnett if there is a need, maybe open a separate issue to discuss preprocessor flags?
