### ISSUE TITLE
Support for deleting packages declared in environment spec matrix

### ISSUE THREAD

**Issue by mc-allen** [LLNL/spack#16651]
### Rationale

Currently, it is not possible to reinstall or delete a package declared in an environment spec matrix:

https://spack.readthedocs.io/en/latest/environments.html#spec-matrices

This is a blocker for reinstalling a given package in the matrix within the environment. The workaround for this is to uninstall the package globally, then reinstall it within the environment.

### Additional information
This is accurate as of spack version 0.14.2.

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by becker33** [comment]
@mc-allen I'm assuming you don't care about the spec being removed from the roots of the environment, what you need is for it to be removed from the concretization of the environment so that it is re-concretized if it is reinstalled? The former would be very difficult, but the latter is quite tractable.

**Comment by mc-allen** [comment]
Sorry for the delay - yes, what I really wanted to be able to do was to reinstall matrix-defined specs.
