### ISSUE TITLE
How to use IBM ESSL with Spack?

### ISSUE THREAD

**Issue by CodeCookr** [LLNL/spack#1666]
I would like to install the netlib-lapack package, using IBM ESSL for BLAS instead of, say, OpenBLAS. 
This is a very typical case on OpenPOWER systems, as we will always give priority to ESSL over other BLAS libraries.

What is the best way to handle this kind of configuration when installing a package with spack ?

Thanks!

**Comment by davydden** [comment]
you can see which packages currently provide `blas` by `$ spack providers blas`. 

In order to use `essl` you would need to add a package for it in Spack. It can be something like `mkl` which would require a license. Then, you would do `spack install netlib-lapack^essl`.

**Comment by adamjstewart** [comment]
I'm not sure if I understand the question. `netlib-lapack` is already a BLAS/LAPACK provider, it doesn't depend on OpenBLAS. But yes, @davydden is right. If you want to use a BLAS/LAPACK provider that is not in Spack, you will have to add a new package for ESSL containing the lines:
```python
provides('blas')
provides('lapack')
```
Then, you can build a package like `arpack` (which does depend on BLAS/LAPACK) by running:
```
$ spack install arpack ^essl
```
The [Packaging Guide](http://spack.readthedocs.io/en/latest/packaging_guide.html) is really useful if you've never written a Spack package before, especially the section on [Virtual Dependencies](http://spack.readthedocs.io/en/latest/packaging_guide.html#virtual-dependencies).

By default, Spack will still choose OpenBLAS as the default BLAS/LAPACK provider. If you want to change this permanently instead of having to change it on the command line every time, you can add this to your `~/.spack/packages.yaml` file:
```yaml
packages:
  all:
    providers:
      blas: [essl]
      lapack: [essl]
```
See [Build Customization](http://spack.readthedocs.io/en/latest/build_settings.html) for more details. And let me know if you have any other questions!
