### ISSUE TITLE
Installation issue: mpfr

### ISSUE THREAD

**Issue by ptaffet** [LLNL/spack#17311]
### Steps to reproduce the issue

```console
$ spack install mpfr

...
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
```
I looked into the issue a little, and the `package.py` file does specify `force_autoreconf = True`, which seems to be what is needed. `aclocal` does get called, which I think should regenerate the file, but clearly that's not working.

I was able to build it directly from the stage directory, but I think that was using libtool 2.4.2. 

### Information on your system

* **Spack:** 0.14.2-1609-5e1cb24
* **Python:** 2.7.16
* **Platform:** linux-rhel7-ivybridge

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4852360/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4852361/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ptaffet** [comment]
Modifying the `package.py` to depend on `libtool@2.4.2` instead of `libtool` does fix the issue, but I think that's not the right way to do it.

**Comment by mwkrentel** [comment]
@ptaffet See #13792 and #13903.

Back then (Nov 2019), the problem was using an external package (perl,
cmake) from /usr put /usr/bin early in your path, so building mpfr
would pick up /usr/bin/libtool instead of the spack-built libtool.
This is an awkward problem for spack because you want to use
/usr/bin/perl but not /usr/bin/libtool.

This was fixed in Nov 2019 in #13903, so unless you're using a really
old spack, I don't see why you would encounter this problem.  It's
possible there's a regression, but I don't think that's likely.

What machine are you running this on? 
What Linux distro and version?
What version is /usr/bin/libtool?
What libtool is on your PATH, what does `type -a libtool` report?

What is your packages.yaml file, especially what external packages
(eg, perl, cmake) are you using?

Btw, using `libtool@2.4.2` is probably harmless, so if you're stuck
and can't find a better workaround, then go ahead (for now).  But
you're right, that's not the correct fix.

Another workaround would be to have spack build everything, including
perl, cmake, etc. (blech)

**Comment by ptaffet** [comment]
Hi Mark,
I was running this on NOTS at Rice. It's a RHEL 7.6 (`linux-rhel7-ivybridge`) system. My copy of spack was pretty new (the day I posted the issue, or maybe one day before).

`type -a libtool` reports `libtool is /usr/bin/libtool`, and `/usr/bin/libtool --version` reports `libtool (GNU libtool) 2.4.2`.

My `packages.yaml` is:
```yaml
packages:
  cmake:
    paths:
      cmake@2.8.12.2: /usr
  automake:
    paths:
      automake@1.13.4: /usr
```

(I didn't realize how useful `packages.yaml` could be until after hitting this problem)

This issue is not a big deal. My end goal was to install `texlive` with spack, but I ended up just using the `texlive` installation on my Mac instead.

**Comment by mwkrentel** [comment]
@ptaffet I figured out what's going on here.  The problem is that
you're using automake 1.13.4 from packages.yaml.

Libtool and automake work closely together.  Libtool 2.4.6 is the
latest and automake 1.13.4 is **very** old (2013).  They're just too
far apart.

If you take out automake and let spack build the latest version, then
I expect it should work.

The problem is not specific to mpfr.  You get the same problem for
the same reason with probably anything that requires rerunning
autotools.  For example:

```
spack install libunwind@master ^libtool@2.4.6 ^automake@1.13.4
```

My advice is: always let spack build the latest versions of autotools
packages (autoconf, automake, libtool, m4).  They're tiny, build
easily and robustly and they "just work."

So, no bug here.

Edit: libunwind@master does fail (on RH 7.x), but it's for a different
reason.  I should read the error message more closely. :-)
Old automake does breaks mpfr, but it's not as widespread as I first
thought.

**Comment by ptaffet** [comment]
Hi Mark,
Thanks for the investigation! I had run `spack external find` at some point, and I didn't notice it had discovered those ancient versions.
