### ISSUE TITLE
[root] dictionary generation fails when using spack-installed compilers

### ISSUE THREAD

**Issue by vvolkl** [LLNL/spack#17488]
I'm using centos7 with a spack-installed gcc@8.3.0, and root@6.20.04. When I try to `spack load gcc; spack load root` and compile something that creates a dictionary (e.g. podio), root errors with `#include <string_view> not found`. This does not occur when using the system compiler on other machines, or using the spack compiler wrappers.
@HadrienG2 @chissg @drbenmorgan any ideas?

**Comment by HadrienG2** [comment]
Almost every time I have seen an error related to string_view includes in ROOT, the problem turned out to be caused by a mismatch between the C++ standard or compiler that ROOT was built against, and the C++ standard or compiler that the ROOT client application was using. In most cases, one was C++17 and one wasn't.

It seems that the ROOT API depends on which compiler and C++ standard you are using, most likely as a result of ROOT's implementation depending on GCC/libstdc++ implementation details which vary depending on those factors.

**Comment by vvolkl** [comment]
Indeed, that usually happens during a c++ standard mismatch in root, and in fact I try to inherit the root cxxstd for packages depending on it. 

But here I think the issue is a  different one - I'm not sure how exactly root uses the compiler during dictionary creation, but somehow it misses the stl provided with it. I'm not sure if the compiler wrappers are to blame, or it is an environment issue.
There is of course the workaround of using `spack build-env` or installing the package creating the dictionary with spack, but creating dictionaries is  a common operation and not being able to do  would limit the usefulness of spack installations of root a lot.

**Comment by HadrienG2** [comment]
This does ring a bell. I did actually encounter dd4hep dictionary creation issues too, though the error was different. I worked around it by sourcing the `thisdd4hep` script instead of relying only on spack's environment setup, which suggests that there is some env var which the ROOT dictionary mechanism needs and which spack does not currently set.

**Comment by vvolkl** [comment]
This turned out to be due to the fact that the spack-installed gcc does not provide a symlink `cc`, which root uses at runtime to find its include directories.

**Comment by vvolkl** [comment]
Fixed by https://github.com/spack/spack/pull/23888.
