### ISSUE TITLE
Exceptions raised during build environment construction result in e4s pipeline remaining pending

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#17482]
I submitted #17439 to test a PR with changes to Spack's core on the e4s pipeline. This was great, since it detected a bug that slipped through unit tests. 

I just want to report that the bug was during the construction of the build environment resulting in errors like [this one](https://cdash.spack.io/viewConfigure.php?buildid=13980). On the PR I never got an error reported, but the pipeline was hanging in the "pending for notifications" state until I push forced a fix.

### Steps to reproduce the issue
An example of a commit which was exposing the bug is: 8a15740a2. Submit a PR at that commit and wait for the pipeline to report back on Github.

### Error Message

Looking at the corresponding dashboard [this error message](https://cdash.spack.io/viewConfigure.php?buildid=13980) and many other similar ones have been logged, but the outcome has never been reported as an error. The pipeline doesn't fail and stays pending on Github.

### Information on your system

Not relevant.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
@alalazo Did you recently restart this [job](https://gitlab.spack.io/spack/e4s/-/jobs/243073)?  I ask because the check is marked as failed on your github PR, as well as marked as failed on the associated gitlab pipeline, but that particular job is still running.  I've not seen that happen unless someone clicks the retry button on the pipeline or on a specific job.

Anyway, regarding the error not getting reported to github, I wonder if there was some temporary service-related issue?  I've not yet seen the kind of issue you're describing, where a failure during the pipeline generation or a spack build failure left the github status pending.  Was the E4S pipeline perhaps still running on gitlab when you were looking for the status report on github?  I don't think it reports status back to github until the pipeline has finished to whatever degree it can (i.e. it doesn't report failure as soon as one job fails).

As an additional note, I have noticed that even if clicking a retry button in gitlab results in job/pipeline passing, the status check on github will not be updated.  For that, you would need to push another commit on your branch, or force push the previous one.

**Comment by alalazo** [comment]
> Did you recently restart this job? I ask because the check is marked as failed on your github PR, as well as marked as failed on the associated gitlab pipeline, but that particular job is still running. I've not seen that happen unless someone clicks the retry button on the pipeline or on a specific job.

Yes, I restarted it since it failed for a system error (pod didn't start on the first try).

**Comment by scottwittenburg** [comment]
> Yes, I restarted it since it failed for a system error (pod didn't start on the first try).

Was the job marked as failed, and this was the reason you saw in the job trace?  Normally, jobs will be retried the maximum of three times before they'd be marked as failed, so I wonder if the same thing happened the first two times?

**Comment by scottwittenburg** [comment]
@alalazo I created #17510 in order to test what you reported.

**Comment by scottwittenburg** [comment]
> @alalazo I created #17510 in order to test what you reported.

But since you force-pushed the branch, maybe you fixed the problem that caused the failures?  Any idea how I can get my hands on the change that results in the `AttributeError: 'Spec' object has no attribute 'mpicc'` type of issue you mentioned above?  I looked at the diff you linked, and it seems the same as the re-written commit with the same commit message currently on your branch, but so far in that [pipeline](https://gitlab.spack.io/spack/e4s/pipelines/3505), I'm not experiencing the problem.

**Comment by alalazo** [comment]
@scottwittenburg Just remove the last commit from the branch. If you do so there's a bug with subscripting virtual dependencies if they have been monkey patched. That will expose the `AttributeError: 'Spec' object has no attribute 'mpicc'` error that will happen *before* configure time when  the build environment is being set.

**Comment by scottwittenburg** [comment]
The pipeline for this [PR](https://github.com/spack/spack/pull/17510) still hasn't built it's first spec, due to a pretty large backlog of E4S pipelines running at the moment, around 20 of them it looks like.  I think this is mainly due to a large number of merges to `develop` in a (relatively) short period of time.  In our cloud infrastructure, we only have 10 of the medium sized runners that can run concurrently, and the vast majority of the E4S specs build on those, so many of those pipelines probably can't even get started, as there won't be any free runners.

I wonder if you ran into a similar thing @alalazo?  Maybe even though you were seeing CDash results of failed builds, there were still unfinished jobs in your pipeline due to a similar load on the system?  I guess overnight gitlab.spack.io should have a chance to work through the backlog, and maybe tomorrow morning we'll see if this [pipeline](https://gitlab.spack.io/spack/e4s/pipelines/3559) has the same problem you encountered.

**Comment by scottwittenburg** [comment]
It seems this was reproduced overnight.  Even though a bunch of jobs failed (job script exited non-zero) in later stages, and there do not seem to be any jobs still running, the E4S pipeline is marked by gitlab as running, therefore the dependent spack pipeline is still marked as pending, and there has been no update to the PR check.

Thanks for reporting this @alalazo, I'm looking into it.

**Comment by alalazo** [comment]
Closing, since I didn't see this issue in a while.
