### ISSUE TITLE
Make -j, --jobs flags definitive

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#17598]
### Rationale

Spack handles the `-j` flag differently from other popular build systems like `make` and `ninja`, because it sets a hard limit for the number of build jobs to the number of cores:

```python
# first the -j value is saved like
jobs = min(jobs, multiprocessing.cpu_count())
spack.config.set('config:build_jobs', jobs, scope='command_line')

# later it is used as
jobs = spack.config.get('config:build_jobs', 16) if pkg.parallel else 1
jobs = min(jobs, multiprocessing.cpu_count())
```

For reference, `make`, `ninja`, `scons` and `ctest` do not have an upper limit, and `ninja` seems to set the number of parallel jobs to `nproc + 2` by default on my system (something currently not possible with spack):

```
$ make --help | grep "jobs"
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
$ ninja --help 2>&1 | grep "jobs"
  -j N     run N jobs in parallel (0 means infinity) [default=18 on this system]
```

When it comes to the optimal number of build jobs, it seems to be common practice to have slightly more jobs than cores (like ninja does, see also https://stackoverflow.com/questions/15289250/make-j4-or-j8). I would expect to be able to enforce this in spack by specifying the `-j` flag, but I can't since it has an upper limit.

Notice that `ninja` also respects cpuset / taskset on Linux, which spack does not:

```
$ taskset -c 0-1 ninja --help 2>&1 | grep "jobs"
  -j N     run N jobs in parallel (0 means infinity) [default=3 on this system]
```

it automatically sets the number of jobs to 3 when I give it just 2 cores (so, nproc + 1 here), which is very useful.

### Description

It would be nice if the `-j` flag would be handled differently, in this way:

- If `-j` is specified by the user, simply take this value as the number of build jobs, do not limit it by the number of cpu cores.
- If `-j` is _not_ specified, take a sensible default:
   - Take `min(config:build_jobs, cpus available)`
   - Furthermore, on Linux, ensure that `cpus available` corresponds with the number of cores made available to the process through cgroups / cpuset, i.e. `sched_setaffinity`, such that it gets a proper default in `slurm`, `docker`, `kubernetes`, or people who simply use `taskset` (#17566).

### Additional information

Came up in #17566.

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by danieldjewell** [comment]
Yeah, I'm not sure of the rationale behind forcing an upper limit on jobs. In systems with massive numbers of cores (>= ~16) there *seems* to be a benefit in setting the job count to 150%-200% of the number of cores. As @haampie noted, I/O and other overhead tends to keep actual utilization low. Especially depending on what's being built: some builds paralellize very well - some don't (e.g. perhaps compiling multiple libraries that will be needed at the end for linking, but compiling each library sequentially but compiling files *in* the library in parallel).

I would also add that adding package level parallelization could be very beneficial. Something like what Gentoo does -- it will parallelize individual builds but also allows you to build whole packages in parallel. This is especially nice because the pre-build configuration steps are (1) quite often linear and sequential and (2) quite often a huge % of the total build time when using a system with lots of cores. (And since Spack seems to have the dependency graph thing pretty well figured out, choosing which packages are safe to build in parallel seems like it would be reasonably easy?)

**Comment by haampie** [comment]
> I would also add that adding package level parallelization could be very beneficial.

This already works :) for instance in bash `spack install -j2 package &` `spack install -j2 package &` would build at most 2 deps in parallel with 2 cores; and so does `srun -n2 -c2 spack install -j2 package` with slurm on a shared filesystem.
