### ISSUE TITLE
missing README info - no support for python 3.x and no info about the data source of package list

### ISSUE THREAD

**Issue by pbc** [LLNL/spack#1767]
1) I might be missing something but I can't see any information about which version of Python is required to actually run Spack.

My default python is 3.5 and when I run
    
    ./spack list

on current master branch it fails due to various print statements which use print without parenthesis, which is expected when you grep the repo for "print"

Can someone clarify what am I missing here ?

2) I can't find any information about what is the data source of "spack list" results.

- is it hardcoded ?
- is there a central server storing info about packages ?
- can this source be customised ?
- can you have multiple package data sources?

**Comment by tgamblin** [comment]
Hi @pbc: Spack currently doesn't work with Python 3.  We still have to support 2.6 due to its unfortunate widespread use on HPC machines, and supporting 3 doesn't seem worth it until we can ditch 2.6.  So I recommend running with 2.7.

`spack list` prints packages available in currently registered repos.  See `spack repo -h`. For you, that is likely the builtin repository in `var/spack/repos/builtin`, where the `package.py` files live.

**Comment by pbc** [comment]
Thank you @tgamblin for a quick reply. This explains everything.

Either way it would be good to have this info in the README or somewhere in the docs.

**Comment by citibeth** [comment]
Does this solve your problem?  See the first paragraph...

https://github.com/citibeth/spack/blob/efischer/docs2/lib/spack/docs/getting_started.rst

**Comment by citibeth** [comment]
`spack list` is equivalent to `ls ...spack/var/spack/repos/builtin/packages`
