### ISSUE TITLE
Getting Updates to Spack Packages Quickly

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1774]
@ax3l 

This thread is for discussion of ways we can get updates to Spack packages quickly.  Splitting the Spack repo (#1773) was proposed as one technical feature that might help with this goal.  But it's not immediately clear how much that approach would help with the stated goal, and I think we need more discussion on other ways to get updates quickly.  Hence this thread.

This is also a continuation of OT discussion on #1696

**Comment by adamjstewart** [comment]
Is this still a problem? A lot more people (including myself) are able to merge PRs now. For non-significant changes like adding a new version, PRs are generally merged on the timescale of hours. I agree that core Spack modifying PRs still take way too long to get merged, but package modifying PRs are now merged fairly quickly.

**Comment by ax3l** [comment]
My intend was more about triggering a conda-forge like continuous integration workflow for contribution.

Anyway, merges here are definitely super-fast and external repos have been added since then, too. So with regards to this issue I am good with closing it.

We could still consider if and how we might allow adding *this git repo* (or a splitted mainline package repo) as a constantly updated *external repo* to once-installed spack installations. But again, this only makes sense when versioning the package format and CI are in place.

**Comment by alalazo** [comment]
> My intend was more about triggering a conda-forge like continuous integration workflow for contribution.

Did you have a chance to look at #2917? It should be a first step towards what you mean.

**Comment by ax3l** [comment]
subscribed, thanks!
