### ISSUE TITLE
dependency types problem - bug?

### ISSUE THREAD

**Issue by JaroslavHron** [LLNL/spack#1831]
Consider package

A/package.py:
```
depends_on('C', type=('build','run'))
depends_on('B')
```

B/package.py:
```
depends_on('C', type='run')
```

Then it seems like package A effectively depends on C only by `type='run'` irrespective of type given in A/package.py - is that correct?

**Comment by adamjstewart** [comment]
@mathstuf?

**Comment by xjrc** [comment]
This is probably related in some way to #1457 and #1559.

**Comment by davydden** [comment]
Looks very much like #1457, see https://github.com/LLNL/spack/issues/1457#issuecomment-239318984

**Comment by mathstuf** [comment]
I thought I union'd deptypes in the graph creation, but maybe I missed it? Possible places to look: `Spec._replace_node`, `Spec._concretize_helper` (docstring contains `As things are concretized, they're added to the presets, and ancestors will prefer the settings of their children.`), `Spec._merge_dependency`, and `Spec._normalize_helper`

**Comment by tgamblin** [comment]
@JaroslavHron: this is intentional.  Currently we don't store build dependencies in the DB, or hash them.   This is so that changing a build dependency (like cmake version) doesn't trigger a full graph rebuild.  When the concretizer is a little smarter and can do some smarter matching, we'll preserve the build provenance better.
