### ISSUE TITLE
Bundle Packages

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1926]
@tgamblin @alalazo @adamjstewart 

I want to make a package that installs a bunch of other stuff, but doesn't install anything itself.  See below for my initial attempt.  Unfortunately, this causes an exception:

```
==> Error: Install failed for env-modele.  Nothing was installed!
==> Error: Installation process had nonzero exit code : 256
```

Any pointers on how to go about building such packages?  My sample is below.

```
from spack import *


class EnvModele(Package):

    homepage = ""

    version('1.0', 'e2b724dfcc31d735897971db91be89ff')

    variant('python', default=False,
            description='Include basic scientific Python environment')

    # --------- ModelE dependencies (taken from modele/package.py)
    # Build dependencies
    depends_on('m4')
    depends_on('cmake')
    # Link dependencies
    depends_on('mpi')
    depends_on('netcdf-fortran')
    #depends_on('fexception')
    depends_on('everytrace+fortran+mpi')
    depends_on('parallel-netcdf+fortran~cxx')

    # -------- Other things we need
    depends_on('modele-utils')
    depends_on('ncview')
    depends_on('nco')
    depends_on('modele-control')

    # -------- Python post-processing environment
    depends_on('python', when='+python')
    depends_on('py-scipy', when='+python')
    depends_on('py-netcdf', when='+python')
    depends_on('py-basemap', when='+python')

    def url_for_version(self, version):
        return 'https://github.com/citibeth/dummy/tarball/v1.0'

    def install(self, spec, prefix):
        pass
```

**Comment by tgamblin** [comment]
Ok two questions:

1. Are you doing this because spack doesn't have something like [`bundler`](http://bundler.io) or [`brew bundle`](https://github.com/Homebrew/homebrew-bundle)?  Would you like something like that?  It's something I've been thinking a lot about implementing recently, as our code teams need it for building *their* dependencies. The `Gemfile` and `Gemfile.lock`  concepts map nicely onto Spack's abstract and concrete packages (though in both cases Spack can be more specific than `gem`).  This would be a larger feature than what you're describing, but I think it's something spack needs to adequately encapsulate build environments.

1. Or, is this more like `X11`, where it's a bunch of packages that people will probably depend on together as _part_ of a larger system?

And one answer:

* Right now, if you just touch a file in the install method there (any file, really):

```python
def install(self, spec, prefix):
    touch('this-is-a-bundle.txt')
```

Spack will decide that the install succeeded.  Spack can also have sanity checks, but they're optional and the default behavior is to simply check whether something was put into the prefix.

Probably we should have a decent convention for doing this, so that people do it consistently.  I wonder if @alalazo's #1186 would allow us to have something like a `MetaPackage` or `BundlePackage` class that would label these in a consistent way.  This would be useful for two reasons:

1. Meta packages don't really need to be "installed" in a prefix.
1. Similarly, they don't need to be `RPATH`'d or added to `-I` or `-L` flags.
1. They should probably evaporate from the DAG during concretization so that they don't affect the hash.  Their dependencies should just be attached to their dependents.

Thoughts?

**Comment by citibeth** [comment]
> Are you doing this because spack doesn't have something like bundler or brew bundle?

No.  `spack setup` already does that.

> Or, is this more like X11, where it's a bunch of packages that people will probably depend on together as part of a larger system?

Yes.  My thought process was actually more technical and Spacky... Spack actually provides two ways to locate packages: spack module/find/etc., and the concretization algorithm.  Let's compare them....

Concretization is sophisticated and powerful.  If it can find a self-consistent answer for you, it will.  It can take into account many constraints (for example, from `packages.yaml`).  The one thing people don't like about it is it doesn't differentiate between packages that have / have not been built; but that can be solved by adding this information to some future concretization algorithm as additional constraints.

`spack load`, in comparison, is wimpy.  If doesn't acccept multiple constraints.  If it finds more than one thing that matches, it throws up its hands and gives up.  In practice, that means that `spack load` will stop working as soon as you have more than one version of something installed; or to keep it working, you have to keep adjusting your `spack load` command based on what's installed.

This observation was part of what drove me to create `spack setup` in the first place... rather than assembling a build environment with a series of `spack load` (or equivalent) commands, it would be better to have the concertizer do the assembly.

`spack setup` works great for creating build environments for packages as I develop them.  But it dumps me on the ground when I need to assemble all that into a *user* environment.  So far, I've been assembling the user environment with a series of `spack module loads` commands.  I know this is risky; for example:
  a) `spack module loads` is not guaranteed to work.
  b) If there is more than one `spack module loads` command, there is no guarantee that the modules loaded with multiple `spack module loads` commands will be compatible with each other.  This is not a problem when loading regular binary stuff; but it CAN be a problem when loading Python modules (which I do).

The dummy/bundle packages I'm envisioning will allow me to use the concretization algorithm in setting up user environments.  I will then only need a single `spack module loads` command to generate the `module load` commands for my entire user environment.  I will then have a better guarantee that my environment is self-consistent.

> Probably we should have a decent convention for doing this,..

Yes... we need a `BundlePackage` base class... just subclass it in your package and then you don't have to add in extra "dummy" cruft that you don't need, like install methods, etc.

> This would be useful for two reasons:

I like all three reasons.

**Comment by citibeth** [comment]
I forgot to mention two more reasons why bundle packages are better than a bunch of `spack load` or equivalent commands:

1. A single `spack module loads` command runs SO MUCH FASTER than multiple.

2. I now avoid loading the same module twice.  Not the end of the world, but it also speeds things ups for me.

**Comment by BarrySmith** [comment]
Based on @tgamblin suggestion in https://github.com/LLNL/spack/issues/2007#issuecomment-253358445  I found at http://spack.readthedocs.io/en/latest/workflows.html#running-binaries-from-packages

Dummy Packages
As an alternative to a series of module load commands, one might consider dummy packages as a way to create a consistent set of packages that may be loaded as one unit. The idea here is pretty simple:

Create a package (say, mydummy) with no URL and no install() method, just dependencies.
Run spack install mydummy to install.

Sadly this doesn't work as advertised. 

If you don't provide a version you get 

$ ./spack install xsdk
==> Error: There are no valid versions for xsdk that match ':'

but if you provide a version you get 

$ ./spack install xsdk
==> Error: Class constructor failed for package 'xsdk'.

Caused by:
NoURLError: Package Xsdk has no version with a URL.

Thus you need to provide a file somewhere on the web to download. As citibeth did with https://github.com/citibeth/dummy/tarball/v1.0

When you do all that you end with the error message about installer not doing anything.

So the question is, do you plan to support "true" dummy packages that really only require listing dependencies and don't require URLs and installers? They seem like a very useful thing.

**Comment by tgamblin** [comment]
My plan is to actually support dummy packages in a better way.  Right now there's annoying work, as you note, to fool Spack into thinking the dummy package is real.  Specifically, you have to:

1. provide a fake download of some sort
2. touch something in the install prefix (you can use the builtin `touch` for that)

I would really like to have a `MetaPackage` class for this, which you could just extend, and Spack would know it's not real.

I don't anticipate this being too hard -- I was hoping to get @alalazo's #1186 (which is due for `v0.10`) merged first, then start doing this.

**Comment by BarrySmith** [comment]
Cool. I am working away on a xsdk dummy package using the hacks and we can trivially switch to your MetaPackage class when it is ready.

**Comment by citibeth** [comment]
Barry,

The following works for me:

https://github.com/citibeth/spack/blob/efischer/develop/var/spack/repos/builtin/packages/env-modele/package.py

It looks like I got around the problem by downloading (but never using) a
dummy tarball.  A hack yes; but it would be easy to hide inside a
superclass and forget about it.

I don't have anything for env-modele in my packages.yaml.  I'm also using
it with the following PR, which makes repeated installs easier (I just do
`spack install -f env-modele`)

https://github.com/LLNL/spack/pull/1915

-- Elizabeth

**Comment by BarrySmith** [comment]
Thanks this was very useful and got things working for me.

**Comment by markcmiller86** [comment]
@citibeth ... the dummy tarball idea here has two drawbacks...

- 1.0 is the only version number one can assign to a _bundle_ or _meta_ package. I would like things like `0.1` or `0.9` or `alpha` or `develop`
- The LICENSE file the dummy tarball includes is a GNU license. IMHO, this is overly suggestive that the bundle is GNU licensed and certainly would be confusing to anyone who bothered to look.

**Comment by citibeth** [comment]
See #3133 which addresses this issue.  Would anyone like to push #3133 across the finish line and get it merged?
