### ISSUE TITLE
What is the difference between spack and portage package manager and additional questions?

### ISSUE THREAD

**Issue by Joe23232** [LLNL/spack#19271]
Hi I am curious to know some of the differences between `spack` and the portage package manager?

Additionally which package manager is easier to understand in terms of configurations between the two package managers?

---

With `pacman` if I don't update my system in a long time (specfically with Arch-based systems) then I end up running into all sorts of erros and then I have to manually fix the errors. Is it ok with `spack` if I don't update my system in a very long time, would there be any sort of issues if I update it a long time after?

---

Can `spack` be used with LFS (Linux From Scratch) and it is used as a normal/default package manager?

**Comment by tgamblin** [comment]
> Hi I am curious to know some of the differences between spack and the portage package manager?

Main difference is that portage manages a single set of packages and requires some consistency between them.  It's designed to manage a distro built from source, and it goes down to `glibc` in terms of the userland packages it manages.  Spack doesn't (yet) go down to system runtime packages like `libc`, but we'd like to.  Spack lets you install many potentially conflicting versions of the same package with different flags/options/etc.  Portage doesn't really have support for multi-versioning outside of their notion of "slots" -- where libraries with different `.so` versions can coexist on the same machine.  Spack doesn't care about that b/c they don't have to be in the same prefix.  If you want two versions of `libfoo`, they have entirely different hashes and live in different directories.

> Additionally which package manager is easier to understand in terms of configurations between the two package managers?

Not sure I can really answer this -- it's a pretty subjective question, and I don't have a whole lot of experience with deep `portage` configuration.  @junghans might be able to say as he's worked on Spack and Gentoo.

> . Is it ok with spack if I don't update my system in a very long time, would there be any sort of issues if I update it a long time after?

Should be fine, as Spack will rebuild what it needs if Spack has moved on.

> Can spack be used with LFS (Linux From Scratch) and it is used as a normal/default package manager?

You could think of Spack packages as an implementation of Linux From Scratch.  The recipes in Spack are basically building a similar stack.  Because Spack doesn't currently go down to the `glibc` level, I wouldn't try to use it as your *system* package manager.  I am not sure I can say whether you can use it as a "normal" package manager b/c there are lots of package managers.  Spack is probably not a "normal" package manager -- it's trying to encompass a lot of what system package managers do as well as a lot of what developer package managers do. Maybe one day it can be a system PM, at the moment it is mostly used to build scientific software on top of a regular system distribution.

**Comment by junghans** [comment]
> > Additionally which package manager is easier to understand in terms of configurations between the two package managers?
> 
> Not sure I can really answer this -- it's a pretty subjective question, and I don't have a whole lot of experience with deep `portage` configuration. @junghans might be able to say as he's worked on Spack and Gentoo.

Spack uses json, while portage has a mixture of files that get sourced or look like shell but get parsed and custom files.

I personally think portage has a lot of historically craft, while spack is a bit clearer. Even though Spack misses a manpage to look things up.

**Comment by Joe23232** [comment]
Thanks @tgamblin and @junghans .

I have one other question, 

>  and it goes down to glibc in terms of the userland packages it manages. Spack doesn't (yet) go down to system runtime packages like libc, but we'd like to. Spack lets you install many potentially conflicting versions of the same package with different flags/options/etc.

Is there a plan to implement this by any chance?

**Comment by tgamblin** [comment]
> Is there a plan to implement this by any chance?

Eventually.  We have a prototype branch that models languages as virtual dependencies, so you can `depends_on("c@1999")` or `depends_on("cxx@2017")` in a package.  That would enable us to do it.  I would expect the general capability in the next few months or so, but actually doing it for C may take longer.

**Comment by Joe23232** [comment]
> Eventually. We have a prototype branch that models languages as virtual dependencies, so you can depends_on("c@1999") or depends_on("cxx@2017") in a package. That would enable us to do it. I would expect the general capability in the next few months or so, but actually doing it for C may take longer.


I see, thanks man.
