### ISSUE TITLE
Installation issue: libtheora after updates to ParaView's package file

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#19312]
### Steps to reproduce the issue

```console
$ spack install libtheora@1.1.1%gcc@7.4.0 arch=linux-rhel7-broadwell
...
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/yellow/usr/projects/paraview/stam/pilotlight-dev/tests/spack/tmp_snow_develop_gcc_pyconda_7.4.0/spack/lib/spack/llnl/util/tty/log.py", line 645, in _writer_daemon
    line = _retry(in_pipe.readline)()
  File "/yellow/usr/projects/paraview/stam/pilotlight-dev/tests/spack/tmp_snow_develop_gcc_pyconda_7.4.0/spack/lib/spack/llnl/util/tty/log.py", line 704, in wrapped
    return function(*args, **kwargs)
  File "/usr/projects/hpcsoft/toss3/common/x86_64/anaconda/5.0.1-python-3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 145: invalid start byte
==> Error: ProcessError: Command exited with status -13:
    'make' '-j36'
```

### Information on your system
* **Spack:** 0.15.4-1466-72f431b67
* **Python:** 3.6.3
* **Platform:** linux-rhel7-broadwell

* [packages.yaml](https://github.com/spack/spack/files/5380149/packages.yaml.txt)
* [compilers.yaml](https://github.com/spack/spack/files/5380154/compilers.yaml.txt)

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers @chuckatkins 
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by EthanS94** [comment]
Seems related to #15285

**Comment by Billae** [comment]
Hello,

I am new in Spack and I had exactly the same issue in the same context on two different machines (one on ubuntu and the other on centos). I try with gcc9.2 and libtheora1.1.1.

After investigations, here are my conclusions and my solution: 
There is a problem with the Latex documentation generation, specially with the "\texttrademark" in the doc/spec/spec.tex in libtheora. I don't think the problem came from Libtheora, I think it is Spack which are not able to read this character.

The best solution is obviously to find in Spack which cause this encoding error, but there is a workaround.
I simply proposed a patch which add "\usepackage{utf8x}[inputenc]" in the latex file.

I add this patch in the libtheora recipe (both new one and the previous one) and it works on my two machines.

I attach my patch in this message, if someone want it =)

[fix_encoding.zip](https://github.com/spack/spack/files/5874661/fix_encoding.zip)


Regards,
Eloise.

**Comment by danlipsa** [comment]
An alternate way to solve this - simply don't build the doc, as its not really needed.
https://github.com/spack/spack/pull/21360
I have not seen the alternate solution listed.

**Comment by Billae** [comment]
It is also a solution, I thought it cleaner to repair the doc generation instead of avoiding it.

Eloïse

**Comment by danlipsa** [comment]
@Billae I used your patch instead as it worked for both versions. Thanks for submitting it. I advise trying to submit it upstream - to the libtheora repo. It would be nice to not have to apply this patch for future versions. Thanks!

**Comment by Billae** [comment]
Thanks for PR my solution. I'm a bit new with Github and i didn't know how to do that =).

I will try to propose this solution on the libtheora github :)

Eloïse

**Comment by EthanS94** [comment]
@danlipsa @Billae I am closing this, since https://github.com/spack/spack/pull/21360 fixes this problem. Let me know if you think this should stay open
