### ISSUE TITLE
Installation issue: Ambert Tools 20

### ISSUE THREAD

**Issue by ixdi** [LLNL/spack#19544]
Hi,

We are trying to install AmberTools without success. We have downloaded the AmberTools20.tar.bz2 to the folder where spack is called (~). It gives us the following error.

```
==> Installing amber
==> No binary for amber found: installing from source
==> Error: FetchError: All fetchers failed

/shared/spack/lib/spack/spack/package.py:1270, in do_fetch:
       1267                                 self.spec.format('{name}{@version}'), ck_msg)
       1268
       1269        self.stage.create()
  >>   1270        err_msg = None if not self.manual_download else self.download_instr
       1271        self.stage.fetch(mirror_only, err_msg=err_msg)
       1272        self._fetch_time = time.time() - start_time
       1273
```
The spec is:
```
$ spack install amber@18.20 +mpi +openmp %intel
```

Information of the system
```
* **Spack:** 0.15.4-1609-caab89b
* **Python:** 3.8.6
* **Platform:** linux-centos7-zen2
```

The three stage folders present are empty
```
build_cache  
resource-AmberTools-atcyu4m75qh7radyd3t65acy5pofbzgi
spack-stage-amber-18.20-atcyu4m75qh7radyd3t65acy5pofbzgi
```

Maintainer @hseara 

There's a similar issue here but it's closed without any solution #14063 

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@hseara did you get a chance to look at this? It looks like the tarball was renamed from `Amber#` to `AmberTools#`. We also need to add version 20 for this to work.

**Comment by hseara** [comment]
I will have a look during this week.

**Comment by hseara** [comment]
Hi all, 
Please take into account the following:

- I am not related in any way to Amber of their development team.
- **Amber** is proprietary software with a very cheap and flexible license (whole departments with a single license). There are no direct download links for it. It basically provides the advanced MD engine `pmemd`.
-  **Ambertools** is free of charge, and its components are mostly released under the GNU General Public License (GPL). Amber requires people to fill a form in their [webpage](https://ambermd.org/GetAmber.php#ambertools) to download Ambertools.  However, there is also a working link ('http://ambermd.org/downloads/AmberTools{0}.tar.bz2') that I will add in the new spack commit I am working on. I hope they do not mind.

Ambertools can be used as a stand-alone package. Currently, this option is not offered by spack. Amber, however, requires the source code of Ambertools to be embedded in the installation source code of Amber for its installation. They share a large fraction of code.

Another point that I would like to clarify is that each Amber version only supports a very limited set of Ambertools to be compiled with. 
- Amber20: Ambertools20 and Ambertools21
- Amber18:Ambertools18 and Ambertools19
- Amber16: Ambertools16 and Ambertools17

Therefore, the package combination added to the package Amber18 and Ambertools20 is not possible. 

Finally, there are the following issues that need to be check:
- Starting from Amber20 cmake installer is also available and as far as I know, preferred. Therefore, it will be hard to keep compatibility with old releases. We might have to split the package between Amber and Amber-legacy if we want to continue supporting Amber 18 and 16. I will not make any effort to support even older versions.
-  There are some issues with new versions of gcc (>9) and Amber version 16 and 18.
-  Currently, when installing ambers without mpi (`spack install amber@18.19%gcc@9.3.0`), still pulls `openmpi` as a dependency due to netcdf. The only way to achieve the desired result is by issuing `spack install amber@18.19%gcc@9.3.0~mpi^netcdf-c~mpi^hdf5~mpi'

For the rest, even without any changes, the package works as expected. The spack installation command must be issued from a directory containing the files Amber18.tar.bz2 and AmberTools19.tar.bz2 with the correct hashes.

I will try to implement some of the changes mentioned above, although I would appreciate some comments on how to proceed due to the differences between Amber20 and previous versions of installation methods.

**Comment by adamjstewart** [comment]
@hseara this all sounds good to me. I think it's safe to use that download link in the package, although I'm not a legal person. We do something similar for the `jdk` package. In that way, it should be easy to use the newest version of AmberTools that supports the chosen version of Amber.

For the changing build system question, that's much more open-ended. See https://github.com/spack/spack/pull/12941#issuecomment-538105434 for a list of packages in Spack that have changed build systems. You can look to those for examples of how to handle things. We don't yet have an agreed upon approach to handle changing build systems. Generally, I suggest that packages extend the `Package` base class and use `@when('@20:')` decorators for the new `install` method. `arpack-ng` is a good example of this. In the long run, I agree that removing those old versions is probably best. #20767 and #15896 have a proposed policy for handling this, but it hasn't been merged yet.

Let me know if you have any other questions!

**Comment by hseara** [comment]
I have created the above pull request that should solve all issues in the package.  All tests pass. Therefore, it only needs to be approved and merged.

**Comment by samcom12** [comment]
I'm still getting a `fetch` error.

```
[ tmp]$ spack debug report
* **Spack:** 0.16.2-4026-3e2f890
* **Python:** 3.9.5
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** original
* 
[ tmp]$ ls
amber20  amber20_src  Amber20.tar.bz2  AmberTools20.tar.bz2  install

[tmp]$ spack fetch amber
==> Error: Manual download is required for amber. Refer to http://ambermd.org/ for download instructions.

```

**Comment by samcmill** [comment]
It looks like the AmberTools filename changed on the download site?  

I took the new filename from the Conda feedstock and it worked for me?  https://github.com/conda-forge/ambertools-feedstock/blob/master/recipe/meta.yaml
