### ISSUE TITLE
Prohibit any internet usage

### ISSUE THREAD

**Issue by sebrowne** [LLNL/spack#19755]
Prohibit spack from reaching out to ANYTHING over the internet.

### Rationale

At SNL we have a software approval process for certain machines, and I want to ensure that nothing I have not had approved is going to be installed.

### Description

I think I'd just like an option to spack that says "--no-web" and forces the use of a local mirror, and prevents any downloading from the web.

### General information

Spack version: 0.14.2

Also this seems related to https://github.com/spack/spack/issues/3321

**Comment by sebrowne** [comment]
I will also note that I can kind-of make this happen now by feeding in a bogus proxy through my environment, but that seems hackish.

**Comment by adamjstewart** [comment]
This would also be amazing for testing installations of packages that like to pull in missing dependencies from the internet.

**Comment by robertu94** [comment]
Since packages could always try to some hackish thing to open a socket, your going to have to rely on some platform specific magic to get it to work.

+ On Linux, this probably means unsharing the network namespace using the `unshare` syscall.  Before adding the syscall, you could try running spack with `unshare -n spack ...` with the unshare program from util-linux 
+ On OpenBSD, this could probably be done using `pledge`
+ On MacOS, I'd guess that you'd used the `sandbox` framework https://jmmv.dev/2019/11/macos-sandbox-exec.html

**Comment by alalazo** [comment]
> This would also be amazing for testing installations of packages that like to pull in missing dependencies from the internet.

Meh, run in a container without access to external network :grimacing:

**Comment by robertu94** [comment]
On Linux the technologies are what native containers are built from and have fewer dependencies since they are part of the kernel

**Comment by alalazo** [comment]
https://github.com/spack/spack/issues/19755#issuecomment-723459656 seems to be the best answer to this
