### ISSUE TITLE
Wrong indent config.yaml release 0.16.0

### ISSUE THREAD

**Issue by gdolle** [LLNL/spack#19984]
Hi,

I got a yaml parser error with the default config.yaml for the last archive release 0.16.0. Coming from this line
https://github.com/spack/spack/blob/develop/etc/spack/defaults/config.yaml#L20

Re-indent seems to fix the problem.

**Comment by adamjstewart** [comment]
I'm unable to reproduce this with either Python 2 or 3.

**Comment by alalazo** [comment]
I'm also unable to reproduce. I think it's very unlikely that a problem like this wouldn't be caught by CI, since it's in the default configuration that gets parsed in many tests, but I'd like to understand if it's just a local issue or something more. @gdolle Does it occur for you on a fresh clone of Spack?

**Comment by gdolle** [comment]
@alalazo @adamjstewart I recheck and the problem came from my previous config.yml file ("install_tree" key filled).
My bad, this issue can be closed.

**Comment by alalazo** [comment]
Thanks for the feedback!
