### ISSUE TITLE
python package not active in environment

### ISSUE THREAD

**Issue by jacobmerson** [LLNL/spack#20042]
I created a python package for mpltools. When I add this package to an environment, it is not accessible to python. However, when I use `spack load py-mpltools` everything works as expected.

I'm not sure if the issue is related to the upstream `setup.py`, or my spack package. The spack package I created can be found [here](https://github.com/jacobmerson/spack/blob/a67bf0ca77b33f742c4650c6b4ba5e64739266ff/var/spack/repos/builtin/packages/py-mpltools/package.py)

### Steps to reproduce the issue

```console
$ spack env activate mypy # py-mpltools not active after loading an environment with the package in it
$ spack load py-mpltools # py-mpltools is now accessible
```

### Error Message

No errors reported, stacktrace looks normal. However, py-mpltools is not accessible when running python.
```console
$ python3 -c "import mpltools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mpltools'
```

### Information on your system

* **Spack:** 0.16.0-31-a67bf0ca7
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** original

I use the external python 3.8.5 installation with ubuntu 20.04

### Additional information
- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

@adamjstewart

**Comment by adamjstewart** [comment]
I think this issue (and likely your other issue) are because you are mixing Spack installations and external installations.

When you activate an environment, all of the installations in that environment are symlinked to a central location. However, I don't think external packages are symlinked at the moment (@scheibelp can you confirm?).

Python's import system first searches the current directory, then searches `PYTHONPATH`, then searches the Python installation prefix. In your case, since Python is installed on the OS, it searches that location instead of the view. Use `spack load` sets `PYTHONPATH`, which is of higher precedence, which explains why it wasn't found.

Possible solutions:
1. Don't use external packages, let Spack build Python for you
2. Change Spack Environments to symlink external packages as well
3. Always use `spack load`

**Comment by jacobmerson** [comment]
I will try using the spack built python instead. I guess there should be some warning in the docs that external packages may cause unexpected issues. I do get a warning that the external packages won't be symlinked, but it's not always obvious what kind of issue that may cause.
