### ISSUE TITLE
CGAL Build Broken by New Dependencies

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2005]
@adamjstewart 
Recent changes to CGAL (2015-09-22) added a bunch of new REQUIRED dependencies that are not in fact required.  I know the docs are fuzzy on this issue; but see section "7 CGAL Libraries" here:  http://doc.cgal.org/latest/Manual/installation.html

Yes, Qt5 is required if you want to run demos.  OpenGL is required if you want to read/write images.  But only GMP and MPFR are required to build core CGAL.

In general... extra dependencies beyond what is required for a library's core functionality should almost always be added as Spack variants.  If people are already using a package successfully, and the package is not mistakenly linking to system libraries, then you can assume that dependencies not listed are not required for core functionality.

I believe this needs to be sorted out for CGAL.  Until then I'm reverting back to the pre-Sep 22 version for my own use.  I cannot afford to build the world, I don't have enough inodes for that.

**Comment by adamjstewart** [comment]
I think "broken" is a bit of an overstatement. It's just inconvenient if you don't already have `qt` installed, or if Spack doesn't care that you already have it installed because the hash changed.

The docs break their dependencies down into "Essential Third Party Libraries" and "Optional Third Party Libraries". Since `qt` is listed as "essential" and not "optional", I made it required. If you can get `cgal` to build without `qt`, then by all means make it a variant. But it should probably default to True since it is listed as "essential". Once someone adds packages for the "optional third party libraries", those can be variants that default to False.

**Comment by citibeth** [comment]
The CGAL docs say it's "essential" even though it is not.  I can certainly
go in and fix CGAL, but I'd rather not have to do it.

**Comment by citibeth** [comment]
OK I'm seeing what I can come up with as a fix for CGAL while Spack builds my stuff...
