### ISSUE TITLE
Extending a preexisting package 

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2007]
I'm making this a new issue since it is a basic design question, not specific to an individual package. 

Say there is a package Y that depends on PETSc but needs some small additions to the PETSc that gets provided (for example an added dependency on spai). Now I could copy the petsc.py (call it petsc+spai.py) and add an additional line with the extra dependency and have my users use petsc+spai.py instead of petsc.py   The drawback is that overtime fixes etc may be made in petsc.py that don't get made into my custom petsc+spai.py. 

So, is there, or could there be a concept of "including" a previous xxx.py into a new xxx+yyy.py to use the information from both files in building the package? This way people can in a very light weight manner provide "custom" builds without the high overhead and danger of duplicate code.

**Comment by tgamblin** [comment]
@BarrySmith: two things:

1. You could just add that as a variant on the existing PETSc package:
```python
variant('spai', default=False, description='Build with spai')
depends_on('spai', when='+spai')
```

2. You can make one package extend another with normal Python semantics:
```python
from spack.pkg.builtin.petsc import Petsc
class PetscSpai(Petsc):
    ...
    depends_on('spai')
    ...
```

The second one can work across with different repositories as well -- e.g. if you make an external Spack repository:
```console
spack repo create namespace
spack repo add ./namespace
$ spack repo list
==> 2 package repositories.
namespace    /Users/gamblin2/namespace
builtin      /Users/gamblin2/src/spack/var/spack/repos/builtin
```

You would `import spack.pkg.namespace.petsc` to get the `petsc` package there.

**Comment by adamjstewart** [comment]
@tgamblin you beat me too it. I would recommend the first option as that is very common in Spack and seems to be what you want. That way there is only a single package that gets all of the fixes. Then, in another package that requires petsc+spai, you could use:
```python
depends_on('petsc+spai')
```

**Comment by tgamblin** [comment]
FWIW, I recommend the first option too.  The second one makes you vulnerable to changes to the original package, whereas just adding the variant to the PETSc package lets the package maintainer also maintain the variants into the future.

**Comment by tgamblin** [comment]
It was fun messing with the import system so that the second option would work, though.  I think the second option is good for people who want to develop external repositories that need major customizations, but still want to use some of the builtin Spack packages.  But it's not something we'd be able to maintain in the mainline, and it introduces dependencies between repositories, which I recommend people NOT go nuts with because then we'd need a package manager repo manager.

**Comment by BarrySmith** [comment]
This is very useful. Thanks

So conceivably there could be a xsdk variant of Trilinos that "did all the right things according to xsdk" and I could just request trilinos+xsdk? Which might be different than just trilinos

And PETSc could have a +xsdk that forced it to require superlu_dist and hypre? 

So xsdktrilinos would depend on trilinos+xsdk and petsc+xsdk ?

**Comment by tgamblin** [comment]
Yes.  You can propagate this all the way down:

```python
class Petsc(Package):
    variant('xsdk', default=False, description='use xSDK build options')
    depends_on('trilinos+xsdk', when='+xsdk')

class Trilinos(Package):
    variant('xsdk', default=False, description='use xSDK build options')
    depends_on('someotherpackage+xsdk', when='+xsdk')

    def install(self, spec, prefix):
        ...
        if '+xsdk' in spec:
            build_options += ['foo', 'bar', 'baz']
        ...
```

etc. Planned is a capability to propagate variants to sub-DAGs automatically, even if the dependency doesn't explicitly forward it.  We haven't got that yet but I'd be curious to know whether/how you'd use it.

**Comment by tgamblin** [comment]
@BarrySmith: I think I assume this is obvious but note that variants get included in the DAG hash.  i.e., they're part of Speck's "version" for a package.  So all of these can coexist and will have separate install directories:

```
petsc+xsdk ^trilinos+xsdk
petsc+xsdk ^trilinos~xsdk  # error
petsc~xsdk ^trilinos+xsdk
petsc~xsdk ^trilinos~xsdk
```

If you use `depends_on('trilinos+xsdk', when='+xsdk')` in the `Petsc` package, though, Spack will complain when you try to build the second one, as it violates the constraint.

**Comment by BarrySmith** [comment]
This looks like what we would like for xsdk.

**Comment by tgamblin** [comment]
@BarrySmith: I guess the question is whether the xSDK args are going to be the "recommended" way to install things.  If they are, it might be good to just work the xSDK args into the packages as part of all the regular options, so there's not another option cluttering the `petsc` package.  Also, I suspect that an `xsdk` variant would probably not be orthogonal to other existing variants, so that might make maintaining the package difficult.

Say there are only certain features you want to support for each xsdk release.  You could have a separate `xsdk` package in Spack that doesn't install anything real, but depends on the right configurations of the various member packages.  e.g.:

```python
class Xsdk(Package):
    depends_on('petsc+foo~bar+baz')
    depends_on('trilinos+foo~bar')
    depends_on('superlu-dist~bar~baz')
    depends_on('hypre+foo')
```

Then the variant names in the member packages can represent "real" build features and the `xsdk` package can handle the concern of what is actually supported or part of an xsdk release.

Another place you can set things like this is in a per-user or per-spack-instance `packages.yaml` (see [Concretization preferences](http://spack.readthedocs.io/en/latest/configuration.html#concretization-preferences)).  I think that is probably the wrong place as it's for user-, site-, or project preferences, whereas the `xsdk` requirements really come from the packager.

**Comment by BarrySmith** [comment]
The idea of a phony Xsdk package sounds like the right approach. 

Do you want a pull request? @willenbring

**Comment by tgamblin** [comment]
@BarrySmith isn't his username @jwillenbring?

A PR would be awesome.  As you may have deduced, it'll probably get a lot of comments.

**Comment by jwillenbring** [comment]
@BarrySmith I agree with @tgamblin that a pull request here is a good idea. I was having a related conversation with @maherou yesterday about a phony xsdk package. I liked this approach then, and I like it even a little more now. One of the big advantages I saw of that approach was maintaining a sane way to version xsdk.

**Comment by BarrySmith** [comment]
https://github.com/LLNL/spack/pull/2035
