### ISSUE TITLE
Installation issue: Openfoam silently failing to build binaries

### ISSUE THREAD

**Issue by MichaelLaufer** [LLNL/spack#20120]
We are trying to install Openfoam on Intel X86-64 platform using GCC v10.2.0.
The installation "completes" succeessfully but many of the expected binaries (simpleFoam, pimpleFoam) do not seem to be actually built in /bin or /platforms/../bin 
After removing the "-silent" flag in the package.py, rerunning the command, and searching the build log: pimpleFoam does not appear in the log at all, it appears to fail before getting to the solver source files. Please see logs attached below.

--> one error does exist in the log though:
```
/mnt/central/spack/var/spack/stage/root/spack-stage-openfoam-2006_201012-ew2n27aeolegl2sqcitowa3axfzsfg73/spack-src/wmake/scripts/wrap-lemon: line 280: 87818 Aborted                 (c\
ore dumped) "$lemon" "$skel" "$@" $parserFlags "$tmpFile"
Retaining intermediate: /mnt/central/spack/var/spack/stage/root/spack-stage-openfoam-2006_201012-ew2n27aeolegl2sqcitowa3axfzsfg73/spack-src/build/linux64GccDPInt32-spack/src/OpenFOAM/e\
xpressions/fields/fieldExprLemonParser.lyy
make: *** [/mnt/central/spack/var/spack/stage/root/spack-stage-openfoam-2006_201012-ew2n27aeolegl2sqcitowa3axfzsfg73/spack-src/wmake/rules/General/transform:35: /mnt/central/spack/var/\
spack/stage/root/spack-stage-openfoam-2006_201012-ew2n27aeolegl2sqcitowa3axfzsfg73/spack-src/build/linux64GccDPInt32-spack/src/OpenFOAM/expressions/fields/fieldExprLemonParser.o] Error\
 134
make: *** Waiting for unfinished jobs....
Generating manpages from OpenFOAM applications
```

### Steps to reproduce the issue

```console
$ spack install openfoam@2006_201012 ^adios2@2.4.0 
```
(adios2@2.4.0 is chosen due to open bug  #19088)
### Information on your system

* **Spack:** 0.16.0-5-3069631f37
* **Python:** 3.6.8
* **Platform:** linux-centos8-cascadelake

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/5601726/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5601727/spack-build-out.txt)

@olesenm @samouyal 
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by olesenm** [comment]
Hello @MichaelLaufer 

Interesting, the problem is coming from lemon:
```
lemon: lemon.c:5139: SetAdd: Assertion `e>=0 && e<size' failed.
```
Never seen this before, and not knowing any better, it looks like it _might_ be a compiler issue.

I've opened an [OpenFOAM issue 1938](https://develop.openfoam.com/Development/openfoam/-/issues/1938).
Can followup in either place.

**Comment by olesenm** [comment]
Problem is unrelated to adios

**Comment by MichaelLaufer** [comment]
Thank @olesenm,
What is weird is that my colleague @samouyal is able to correctly compile from source manually (outside of spack) without any issues (on the same machine, with the same compiler).
Have you had any success compiling with GCC 10+?

**Comment by olesenm** [comment]
- gcc-10 (SUSE Linux) 10.2.1 20201117 [revision 98ba03ffe0b9f37b4916ce6238fad754e00d720b]

Building manually with our develop branch looked fine as does building with the master branch (very close to the tar file that spack pulls). So looks fine to me.

Since your colleague had success with the same compiler, same machine and same source outside of spack is encouraging for _me_ (maybe don't have to start digging inside of this bit of OpenFOAM).
I don't know if I would immediately blame the problem on spack, but it does add an extra layer of overhead. Perhaps this is just enough to push things over the edge and the compiler is running out of memory in the process. Or you hit a peak time when someone else was hogging most of the memory and that caused the issue that becomes impossible to trace.

Keep us updated.

**Comment by olesenm** [comment]
@MichaelLaufer - can we close this?

**Comment by MichaelLaufer** [comment]
@olesenm 
Hi Mark,
Unfortunately the issue still persists on my end, but it appears to be something on our end.
Lets close this for now, and I will open another if need be. 
Thanks,
