### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by aphecetche** [LLNL/spack#20213]
Hi,

Trying to do `spack install llvm` on a Mac (Catalina) I got : 

```
==> Installing llvm-11.0.0-gpecd63u5gvd4mhbq3gibgvxjtsucwrq
==> No binary for llvm-11.0.0-gpecd63u5gvd4mhbq3gibgvxjtsucwrq found: installing from source
/Users/laurent/github.com/spack/spack/lib/spack/spack/architecture.py:203: UserWarning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.3-apple for further details]
  warnings.warn(msg.format(compiler))
==> Error: UnsupportedCompilerFlag: clang (< 3.3) does not support the C++11 standard (as compiler.cxx11_flag).
    If you think it should, please edit the compiler.clang subclass to implement the cxx11_flag property and submit a pull request or issue.

/Users/laurent/github.com/spack/spack/var/spack/repos/builtin/packages/llvm/package.py:357, in setup_build_environment:
        356    def setup_build_environment(self, env):
  >>    357        env.append_flags("CXXFLAGS", self.compiler.cxx11_flag)
```

If I understand correctly the error is already happening in the "recipe" (package.py), so I don't have build logs to provide ?

```
> spack debug report
* **Spack:** 0.16.0-121-32e23f532
* **Python:** 3.8.5
* **Platform:** darwin-catalina-skylake
* **Concretizer:** original
```

@naromero77  @trws

Might well be a stupid error from my side, but cannot pinpoint it...

**Comment by alalazo** [comment]
I'm retrying a build on:
```console
% spack arch
darwin-bigsur-cannonlake
```
Can you please post the result of:
```console
% spack compiler list
==> Available compilers
-- apple-clang bigsur-x86_64 ------------------------------------
apple-clang@12.0.0
```
on your machine?

**Comment by aphecetche** [comment]
```
~$ spack compiler list
==> Available compilers
-- clang catalina-x86_64 ----------------------------------------
clang@11.0.3-apple  clang@9.0.0

-- gcc catalina-x86_64 ------------------------------------------
gcc@9.3.0
~$ spack arch
darwin-catalina-skylake
```

**Comment by naromero77** [comment]
I am not build anything on Mac OS X in years. I recommend building GCC first and then try compiling LLVM with GCC.

@trws may no more

**Comment by alalazo** [comment]
@aphecetche I encountered a different issue, that I'll investigate. I think though that your `compilers.yaml` was generated with earlier versions of Spack, since it mentions `clang@11.0.3-apple` instead of `apple-clang@11.0.3`. Can you try to remove it, detect compilers once again and retry the build? 

Asking since we factored Apple Clang logic in its own class, see #17110, and  referring to the wrong compiler may cause inconsistencies.

**Comment by aphecetche** [comment]
@alalazo indeed, removing `~/.spack/darwin/compilers.yaml` and letting Spack recreate it, I now get `apple-clang` instead of `clang`. Thanks !
Now trying a `spack install llvm` again but that may take a while as lots of packages have to be (re)built (as a consequence to the compiler changer I assume).

```
~$ spack compiler list
==> Available compilers
-- apple-clang catalina-x86_64 ----------------------------------
apple-clang@12.0.0

-- clang catalina-x86_64 ----------------------------------------
clang@10.0.1

-- gcc catalina-x86_64 ------------------------------------------
gcc@10.2.0  gcc@8.2.0
~$
```

**Comment by trws** [comment]
That would make sense, the only way you should see this is if the version is being interpreted incorrectly, which might be caused by it being clang rather than apple clang..?  There are various things on Mac that require a blocks-enabled compiler, so building with apple-clang first is usually safest, and any clang you build should be built with objective c language support so you can use it in more places.  Otherwise this should (*should* 🤞) just work.  I don't test this configuration constantly but I do occasionally use it and it's normally alright.

**Comment by aphecetche** [comment]
Closing this as the original problem was understood. Plus I no longer have access to a Catalina machine but only BigSur ones anyway ;-) ...
