### ISSUE TITLE
Bug: comparisons between abstract specs can raise -> spack spec callpath fails

### ISSUE THREAD

**Issue by mvanwaveren** [LLNL/spack#20310]
I installed Spack v0.16, and I tried to install callpath. I get the error message below.

I discussed the issue with @becker33, and he says it looks like there is a bug in the dyninst package and the elf providers, so it fails if there is a dependance on dyninst and elf. It looks like the error is releated to `elfutils`.

The error does not show up in Spack v0.15.

### Steps to reproduce the issue

Install Spack, and checkout v0.16

```console
$ spack install callpath
```

### Error Message

```console
Error: '<' not supported between instances of 'str' and 'NoneType'
```

### Information on your system

I run on CentOS 7.

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by becker33** [comment]
Concretizing `callpath` succeeds when built with `dyninst@:9.2` (when it `dyninst` depends on `libelf` instead of `elfutils`).

It also succeeds when either the `dyninst` or `elf` dependencies are commented out.

**Comment by mwkrentel** [comment]
The problem is related to how callpath and dyninst specify their
dependencies on elf, elfutils and libelf.  In commit c786eb46bb
(PR #18063), dyninst replaced elf@0/1 with elfutils or libelf.

If you replace the callpath depends_on to elfutils, then it
concretizes (I haven't tried building).

IMO, the abstraction of elf@0/1, elfutils, and libelf has never really
worked.  Libelf and libdwarf are old, elfutils is new and pretending
they are interchangeable is a fiction.  A package needs to know if
it's using old or new.

In this case, I don't use callpath, so I don't really know if it would
work with elfutils, libelf or both.  Depends on how actively callpath
is maintained.

ping @hainest

**Comment by mwkrentel** [comment]
@becker33 Btw, can we get a more informative error message here?
`'<' not supported between instances of 'str' and 'NoneType'`
doesn't really identify what the problem is.

Even `spack -d spec callpath` isn't much better.

```
  File "/home/krentel/comgr/spack-repo/lib/spack/spack/spec.py", line 2674, in _merge_dependency
    provider = self._find_provider(dep, provider_index)
  File "/home/krentel/comgr/spack-repo/lib/spack/spack/spec.py", line 2609, in _find_provider
    providers = provider_index.providers_for(vdep)
  File "/home/krentel/comgr/spack-repo/lib/spack/spack/provider_index.py", line 78, in providers_for
    return sorted(s.copy() for s in result)
  File "/home/krentel/comgr/spack-repo/lib/spack/llnl/util/lang.py", line 249, in <lambda>
    lambda s, o: o is not None and s._cmp_key() < o._cmp_key())
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

The real problem is conflicting versions of elf and elfutils, but none
of the errors identify elf as part of the problem.  The stack trace
hints at merging specs, but it never says elf.

**Comment by becker33** [comment]
Yeah I haven't yet been able to figure out exactly what the bug is causing that error (vs a good error message for an incompatibility). But that definitely needs to change.

**Comment by becker33** [comment]
Ok, so after much digging this seems to have almost nothing to do with elfutils. This is a core bug in Spack, in that comparison between Spec objects fails (with the error shown above) if we compare abstract specs and either we compare a spec with a name to an abstract spec, or we compare a spec with a namespace to one for which the namespace has not been defined yet. Expect a PR in the next ~20 minutes.

@mwkrentel @mvanwaveren

**Comment by becker33** [comment]
Interestingly enough, I think this bug goes all the way back to before Spack v0.9 (December 2015), but we haven't had a spec that consistently triggered it until Spack v0.16.0. Maybe in part because it only triggers in python3.
