### ISSUE TITLE
install libpython.py when installing python

### ISSUE THREAD

**Issue by robertu94** [LLNL/spack#20483]
install libpython.py when installing python

### Rationale

Installing this gdb extension would dramatically improve the debugging experience  with python with C extensions.

### Description

libpython.py is a gdb extension written by the python core developers which provides several helper functions for debugging python c extensions using gdb such as `py-bt` which translates the full C backtrace in to a python readable back trace.  Right now we don't install it. According to the documentation, it is generated when the python library is built.

https://devguide.python.org/gdb/

### Additional information

There are a few other packages which provide gdb extensions such as gcc's libstdc++, so an appealing way to solve this would be to make gdb extendable and have python extend gdb to provide this file, however, this would create a circular dependency between gdb and python since gdb depends on python to provide the embedded interpreter within gdb and this file is meaningless without the gdb and the gdb module.  I'm not sure how to resolve this.

@adamjstewart ping'ing you as requested.  I'm not in a hurry to fix this before the new year.

### General information

- [X] I have run `spack --version` and reported the version of Spack

0.16.0-220-cf37e9276

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@robertu94 I looked into this. According to the docs you linked, it seems like the only way to activate Python support is to set `add-auto-load-safe-path` in your `~/.gdbinit`, correct? We try to avoid modifying any files outside of the Spack installation prefix in order to make Spack easy to uninstall. Unless `gdb` has some default `gdbinit` file we can overwrite (I couldn't find one), the best we can do is to make sure that the `python` install copies `python-gdb.py` to the installation prefix so you can set it manually. Spack doesn't yet have a "caveats" thing like Homebrew does, although there are a couple PRs to add it. We could add a `tty.info` telling you where to set it, but it won't be displayed unless someone builds with `--verbose`.

**Comment by robertu94** [comment]
@adamjstewart I'm okay with having to modify the file myself to enable this.  I just need the file to be installed with the spack prefix in the first place.

On a side note, it is [also possible](https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html) to set a spack-built gdb's default auto-load-safe-path at configure time for gdb using `--with-auto-load-dir`, but I think the default safe paths are `$debugdir` and `$datadir` which I believe default to `$prefix/lib/debug` and `$prefix/share/gdb` respectively.  I'd have to experiment more to confirm this.

**Comment by adamjstewart** [comment]
That looks promising! Any thoughts on the best place to put `python-gdb.py`? Maybe in `$prefix/share/gdb` if there isn't already a default location in the Makefile somewhere. I'll try to put together a PR to make all of this work and let you test it.

**Comment by adamjstewart** [comment]
According to [this](https://stackoverflow.com/questions/40391404/loading-python-support-in-gdb) it looks like the `$prefix/bin` directory is a good choice.

**Comment by adamjstewart** [comment]
pyenv does the same thing: https://github.com/pyenv/pyenv/pull/1289
