### ISSUE TITLE
Is there any concept like a "virtual" or "meta" package (e.g. Perl's Task:: distributions)?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2049]
I'd like to be able to create a Spack package, e.g. *my-stuff*, that does nothing on its own but depends on all of the various things, specified as I want them, so that when I `spack install my-stuff` it pulls in *emacs* and *R* and ....

I'm currently doing something like [Erik Schnetter put forth](https://groups.google.com/forum/#!topic/spack/h_UtM17jV7Y).

I imagine I could create a fake tarball (or a tarball with a bit of documentation) but then I'd have to bump it's version every time I change the list of dependencies and keep the package.py and tarball in sync.

Or I could probably override the definitions of Package's `fetch` and `install` so that they didn't do anything interesting, but a quick glance shows me more going on around there than I expected.

**Comment by davydden** [comment]
I relevant trick to avoid duplicated packages is to edit your `packages.yaml` so that packages have the same variants and thereby there is no duplication when you do `spack install` package-by-package in _my-stuff_. The end result is that you would have everything installed with only one version of each package. 

This could get cumbersome if the number of packages is big and the overlap between dependencies is also big.

**Comment by alalazo** [comment]
Ok, I don't want to say it too early, but #1186 is under review. If it gets in it would be quite easy, I guess, to code a `MetaPackage` class that permits to just declare dependencies (and overrides fetch and other methods appropriately). @tgamblin ?

**Comment by tgamblin** [comment]
My thoughts exactly.  @BarrySmith needs this too. Might also be nice to have an X11 metapackage.

**Comment by hartzell** [comment]
Reading through #1186 also led me to #1926, of which this is essentially a duplicate.

**Comment by citibeth** [comment]
I already do this, see:

https://github.com/citibeth/spack/blob/efischer/develop/var/spack/repos/builtin/packages/env-modele/package.py

**Comment by hartzell** [comment]
@citibeth -- Thanks, that works perfectly.   Your tarball is even GPL'ed!   👍

**Comment by hartzell** [comment]
Just noticed, I don't seem to be able to simultaneously depend on two different versions of Perl, I ended up with:

    ==> Error: 5.22.2 does not satisfy 5.24.0

**Comment by tgamblin** [comment]
do you want it to *work* with one version of perl *or* another , or do you want it to simultaneously use two perls?  the former would be `depends_on('perl@5.22.2,5.24.0')`.  The latter isn't possible -- what's the use case?

**Comment by hartzell** [comment]
I want to replicate our standard environment.  It's a replacement for:

```
spack install perl@5.22.2
spack install perl@5.24.0
```

From there people can `(spack|module) load perl@5.(22.4|22.2)` as they see fit.

Perhaps it's better to just script the installation, since there's a bit of mucking about with compilers.yaml and such.

**Comment by tgamblin** [comment]
For now, yes, but you bring up a good point.  It might be convenient to allow a meta-package to specify two versions of something.  That would be allowable for a metapackage because it doesn't build anything (spack guarantees a consistent build environment for each package, and no two versions of one thing is a rule for that).  The only issue with that is that for metapackages that *do* require two versions of something, other packages could NOT depend on them b/c they'd end up with an inconsistent DAG.  I'll keep that in mind but I will have to see how much it complicates the dependency resolution.

**Comment by hartzell** [comment]
Being able to do this is not a big deal for me.  I'm going to need to script some 'activates' along side the various installs, and something to add the compiler to compilers.yaml and ... anyway.

**Comment by citibeth** [comment]
How is such a meta-package semantically different from.... two packages?

**Comment by tgamblin** [comment]
you can install it with `spack install <meta-package-name>`  Also there might be an opportunity for best-effort dependency consolidation if you do the install all at once vs. one after the other.

I think this is interesting as a use case because @hartzell is trying to do things that make it easy for him to set up and reproduce an entire environment.  We currently only really have `spack view` for that although @scheibelp is woking on better custom installation trees with NERSC folks (basically a way to have an easily-navigable symlink tree of packages that is NOT like the builtin Spack install layout).

**Comment by citibeth** [comment]
The concretization algorithm does not allow more than one build of each
package.  A dummy package uses concretization to make a *single*
self-consistent
set of software that can be "module loaded" at once.  I like to think of it
as analogous to a *single* Linux distro.

If you want two versions of something, you will need two top-level dummy
packages.

In your case, it should be possible to use a single top-level dummy package
to install both the 5.22.2 set of software and the 5.24.0 set of software:
just use two different `packages.yaml` files.

**Comment by hartzell** [comment]
I think that I can build:

    foo+D

and

    foo~D

and they'll co-exist happily in the same spack installation/deployment.

I can build

    bar^foo+D

and

    zoop^foo~D

If I now build

    moose ^bar ^zoop

What will happen?  Would it be different if it were foo@1 and foo@2 instead of the variant D?

**Comment by adamjstewart** [comment]
If you build:
```
moose ^bar ^zoop
```
it will build `bar` and `zoop` with whatever `foo`'s variant defaults too. Spack currently doesn't care about what you already have installed. It concretizes the spec and builds anything it doesn't find. If you try building:
```
moose ^bar^foo+D ^zoop^foo~D
```
Spack will crash.

**Comment by tgamblin** [comment]
But you should be able to force Spack to build against the installed things by getting their hashes:

```
spack find -l bar zoop
abc123 bar
123abc zoop
```

And then:

```
spack install moose ^/abc123 ^/123abc
```

There is an outstanding bug on matching specs by hash that you *may* run into here but that is getting fixed before next week.

**Comment by citibeth** [comment]
This looks to me like the right approach to building against installed
things. Something like:

1. Create a packages.yaml file indicating the preferred versions of each
package (by hash)

2. Make sure there's a way to use multiple packages.yaml file, with one
overriding values in the next.
