### ISSUE TITLE
`libxcb` breaks Python3 environments (improper handling of build deps)

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2098]
@adamjstewart 

The `libxcb` package breaks Python3-based builds.  It SHOULD be possible to do this build because `libxcb` has a build dependency on Python2, but the rest of the stuff has a "full" dependency on Python3.  However, the Spack concretizer is not smart enough to deal with that situation.

A quick grep through Spack shows there are very few other packages with the same problem (i.e. a build dependency on Python2, where it would make sense trying to build that package as part of a Python3 stack):

```
llvm/package.py:    depends_on('python@2.7:2.8')  # Seems not to support python 3.X.Y
paraview/package.py:    depends_on('python@2:2.7', when='+python')
libxcb/package.py:    depends_on('python@2:2.8', type='build')
```

To repeat the test, use https://github.com/LLNL/spack/pull/2097.  Then:

```
$ cd share/spack/qa/integration/efischer/gibbs-centos7
$ ./run-test     # spack install env-modele
Input spec
------------------------------
  env-modele

Normalized
------------------------------
==> Error: Invalid spec: 'python@3.2:^bzip2^ncurses^openssl^readline^sqlite^zlib@1.2.5:'. Package python requires version 2:2.8, but spec asked for 3.2:
```

@tgamblin 
This bug should be fixed, IMHO, for the release.  Either fix the underlying problem in concretization, or temporarily remove `libxcb`.

**Comment by tgamblin** [comment]
@citibeth: can you use the "add cards" on the project screen to add this to 0.10?  If you do that the link to 0.10 will show up in the upper right here.

**Comment by citibeth** [comment]
Thanks, that's what I was missing!

**Comment by scheibelp** [comment]
On account of changes in default variants (namely in #2590 which disables the 'X' variant for tk) one can now concretize/build python 3 with default variants:

```spack spec python@3.5.2```

The following is still not possible:

```spack spec python@3.5.2+tk ^tk+X```

This is because the concretizer does not currently concretize build deps separately. This is covered directly by #839 so I will close this issue since the minimal requirements have been met, namely:

> or temporarily remove libxcb

and it is a blocker for v0.10

Of course feel free to reopen if this does not seem sufficiently addressed.
