### ISSUE TITLE
`spack style` is not a recognized command

### ISSUE THREAD

**Issue by lindstro** [LLNL/spack#21210]
Reading the [contribution guide](https://spack.readthedocs.io/en/latest/contribution_guide.html#style-tests), I'm trying to style check my package before submitting a PR, but `spack style` fails with the error

```
% spack style
Error: style is not a recognized Spack command or extension command

% spack debug report
* **Spack:** 0.16.0-200-e117e087e
* **Python:** 3.8.2
* **Platform:** darwin-catalina-skylake
* **Concretizer:** original
```

**Comment by alalazo** [comment]
That's because the command was added at a later commit than the one you're on (the documentation you linked refers to the latest `develop` branch). I would suggest rebasing your branch, but if you can't for any reason this:

https://spack.readthedocs.io/en/v0.16.0/contribution_guide.html#flake8-tests

is the corresponding documentation for the now deprecated `spack flake8` command.

**Comment by lindstro** [comment]
Thanks--that solved the problem.
