### ISSUE TITLE
Merging a PR should keep full commit messages

### ISSUE THREAD

**Issue by jonglezb** [LLNL/spack#21283]
Merging a PR removes part of commit messages, it only keeps the first line.

For example:

- original commit in PR: https://github.com/spack/spack/pull/21267/commits/8f8a2a55d31e60169d9075dd1a760d4ca9fbd625
- final commit in tree: https://github.com/spack/spack/commit/7bed6a7077dcaed2b2400e2c437967124cc227ae

This is a shame because the commit message is typically relevant information that should be recorded as part of the history, for future users to be able to understand what happened. It's frustrating to spend time on commit messages only to have it discarded when the PR is merged.

I understand the rationale of squashing commits when merging, it allows to "clean up" PRs that have many fix-up commits. But it should still keep the full commit messages, especially when a PR only has a single commit.

**Comment by alalazo** [comment]
Hi @jonglezb I think there's a misunderstanding:

> Merging a PR removes part of commit messages, it only keeps the first line.

This is not the way it works, in the sense that whoever merge the PR can edit the message when squash merging. I think this is absolutely fine and helps in keeping the `develop` branch informative when looking at commit messages. The only thing that we never do is to remove the reference to the original PR, so if more context is needed it's just a single click away.

In the case you mention 7bed6a7 has a reference to #21267 and in the PR one can find all the discussion that lead to the accepted modification.

> It's frustrating to spend time on commit messages only to have it discarded when the PR is merged.

I can understand that. What we usually do in core Spack is to write in the PR description that we'd prefer certain parts of the commit messages to be kept, or that we think a particular PR is better rebased and merged rather than squash merged. Just my two cents.

**Comment by haampie** [comment]
Hm yeah, in this case the full commit message could've been used. But indeed, the reference to the PR is still there.

**Comment by jonglezb** [comment]
No hard feelings, I just wanted to make sure whether it was intentional or not.

There is indeed a link to the PR, but it's not in the git repository itself (which I often use to find stuff with git log)

Ok, I'll make sure to mention this in future PR then, thanks!
