### ISSUE TITLE
Spack using spack compiler wrappers of compilers instead of MPI compiler wrappers problematic on Apple

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2159]
@tgamblin It seems the fact that Spack uses its wrappers around the actual compilers instead of around the MPI compiler wrappers, causes difficulties on Apples. On Apple, unlike linux, when building a shared library all dependencies need to to be resolved. This means for libraries that use MPI that all MPI calls need to be resolved. But since Spack passes t the native compilers down to the package configure/cmake, as opposed to the MPI compilers, in many cases, the MPI libraries are never passed to the shared library linker so the package cannot properly build its shared shared library. I've attached an example with a  Trilinos shared library 

[spack-build.out.txt](https://github.com/LLNL/spack/files/557486/spack-build.out.txt)

If I understand things correctly either spack needs to instead pass the MPI compiler wrappers as compiler names to the subpackpage buildsystems (which is what PETSc does) or pass down to the subpackages the appropriate MPI libraries so they can do the shared memory builds including links to those libraries.  Based on our experience with PETSc the second approach is  very MPI specific and fragile which is why we adopted the "use the MPI compiler wrappers as the compilers approach". I believe that spack should just adopt the "MPI compiler wrappers are the compilers approach" but I'm fine with using the true compilers approach so long as you can get it to consistently work properly on Apple systems.

**Comment by davydden** [comment]
It is up to the package what to do. In case of Trilinos, you can always modify package.py to set Cmake compiler variables to point to MPI compiler wrappers (see deal.ii for an example on how to do it in Spack).

AFAIK, spack does not pass native compilers to Cmake anyhow. Instead, environmental variables are set to point to native compilers. What happens next is up to the package.py and its build system.

But for a record, I have zero problems building shared Trilinos on macOS Sierra and a colleague of mine uses El Capitan with Spack. A while ago i was also building it with gcc on macOS.

So your problems could be caused by something other than MPI wrappers. For now i would suggest set them explicitly for trilinos and see if it helps.

**Comment by davydden** [comment]
@BarrySmith :  that is what i would try 
```
 '-DCMAKE_C_COMPILER=%s'       % spec['mpi'].mpicc,
 '-DCMAKE_CXX_COMPILER=%s'     % spec['mpi'].mpicxx,
 '-DCMAKE_Fortran_COMPILER=%s' % spec['mpi'].mpifc,
```

---

In general, i think spack is flexible enough to cover all cases required by different packages. So I am personally not in favour of modifying build environment anyhow and I do no quite agree that it is problematic on macOS. But of course there could be other opinions from maintainers.

**Comment by BarrySmith** [comment]
`'-DCMAKE_C_COMPILER=%s'     % spec['mpi'].mpicc,
 '-DCMAKE_CXX_COMPILER=%s'     % spec['mpi'].mpicxx,
 '-DCMAKE_Fortran_COMPILER=%s' % spec['mpi'].mpifc,`

resolved the problem on my Mac. The Trilinos cmake was building the zoltan shared library with the C compiler and thus couldn't resolve the MPI symbols. By switching to the MPI wrapper it could resolve the MPI symbols and everything worked. I cannot understand how it works for Denis. I'll close this issue, but the xsdk pull request (still working on it) will have this change for Trilinos.
