### ISSUE TITLE
Various issues with python packages

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#217]
I am running into a few issues. This all stems from my attempt to deprecate the py-pil package, which is the Python Imaging Library, and instead create a py-pillow package, with pillow being a fork/replacement of PIL. I also updated packages that depended on PIL and this led to errors building mesa because it didn't properly depend on py-libxml2. I noticed, however, that the libxml2 package (which py-libxml2 depends on) can build the python bindings, thus deprecating py-libxml2. libxml2+python appears to build OK on it's own, but I have found 2 issues:

1) libxml2+python will install the python bindings directly into the python installation rather than the libxml2 prefix. Furthermore, activating libxml2+python will link all the libxml2 files, even those not necessary for python. The latter can probably be fixed easily with some ignore directives.

2) when installing the py-basemap package I get the following error:

==> Building libxml2.
Traceback (most recent call last):
  File "/nfs/tmp2/lee218/spack/lib/spack/spack/build_environment.py", line 278, in fork
    function()
  File "/nfs/tmp2/lee218/spack/lib/spack/spack/package.py", line 812, in real_work
    self.install(self.spec, self.prefix)
  File "/nfs/tmp2/lee218/spack/var/spack/packages/libxml2/package.py", line 20, in install
    python_arg = "--with-python=%s" % spec['python'].prefix
  File "/nfs/tmp2/lee218/spack/lib/spack/spack/spec.py", line 1419, in __getitem__
    raise KeyError("No spec with name %s in %s" % (name, self))
KeyError: 'No spec with name python in libxml2@2.9.2%gcc@4.4.7+python=chaos_5_x86_64_ib^xz@5.2.2%gcc@4.4.7=chaos_5_x86_64_ib^zlib@1.2.8%gcc@4.4.7=chaos_5_x86_64_ib'
==> Error: Installation process had nonzero exit code.

The dependence chain to get to the error above is fairly convoluted. It looks like I can install libxml2+python directly, I can install a package (i.e. mesa) that depends_on('libxml2+python'), and I can even install a package (i.e., py-pandas) that depends on mesa, but py-matplotlib+gui fails with the above error.

**Comment by lee218llnl** [comment]
I will take a first crack at some of these issues.

**Comment by sjtbham** [comment]
Hi, I was trying to build py-pandas on my systems, I get the following stack trace back when trying to activate it.

==> No patches needed for py-pandas.
==> Building py-pandas.
==> Successfully installed py-pandas.
Fetch: 0.28s. Build: 2m 36.64s. Total: 2m 36.92s.
[+] /gpfs/apps/haswell-EL7/gcc-4.8.3/py-pandas-0.16.1-xixmqcjmrdjynky4akccphmj6wbyi2oj
[~ 10:54] $ spack activate py-pandas ^python@3.5.0 ^openssl@1.0.2d
Traceback (most recent call last):
File "/gpfs/sysapps/spack/bin/spack", line 163, in <module>
main()
File "/gpfs/sysapps/spack/bin/spack", line 144, in main
return_val = command(parser, args)
File "/gpfs/sysapps/spack/lib/spack/spack/cmd/activate.py", line 52, in activate
spec.package.do_activate()
File "/gpfs/sysapps/spack/lib/spack/spack/package.py", line 978, in do_activate
if not spec.package.activated:
File "/gpfs/sysapps/spack/lib/spack/spack/package.py", line 518, in activated
exts = spack.install_layout.extension_map(self.extendee_spec)
File "/gpfs/sysapps/spack/lib/spack/spack/directory_layout.py", line 343, in extension_map
_check_concrete(spec)
File "/gpfs/sysapps/spack/lib/spack/spack/directory_layout.py", line 44, in _check_concrete
raise ValueError('Specs passed to a DirectoryLayout must be concrete!')
ValueError: Specs passed to a DirectoryLayout must be concrete!

**Comment by lee218llnl** [comment]
I haven't found the root cause of that issue, but I believe if you revert var/spack/packages/libxml2/package.py to the previous version, make it extend Python without the variant, then it should work around the problem. Let me know if that does the trick for you.

**Comment by lee218llnl** [comment]
@sjtbham were you able to work around this? I also committed a change to the mesa package in the develop branch that makes it depend on libxml2+python, which may help.

**Comment by lee218llnl** [comment]
@tgamblin I am trying to find the best way to fix this issue. I think the underlying problem is that the extends clause isn't working properly with variants. In particular, if the requested variant does not actually extend another package, the other package is being recorded as an extendee. Should we maintain extends conditions in a similar manner as with dependencies?

**Comment by tgamblin** [comment]
@lee218llnl: let me check this out.  I think i can get to it tonight or tomorrow -- extends should work similarly to dependencies so this may have been an oversight in the implementation.  Or it's a function of the fact that variants were added *after* Python merge support.

**Comment by lee218llnl** [comment]
I committed some changes to the libxml2 package. The changes point libxml2 to install the python module into the libxml2 prefix instead of directly installing to the python prefix. I also have the package ignore all the files that aren't related to the python module when activating.

**Comment by tgamblin** [comment]
@lee218llnl @mplegendre: This is my stupid bug. It's an issue with the way specs are being looked up in the packages cache.  The hash being used there is actually wrong, so an incorrect spec/package combination is getting pulled out of the cache.

Here is the problem, in `spec.py:1498`:
```
    def _cmp_key(self):
        """Comparison key for this node and all dependencies *without*
           considering structure.  This is the default, as
           normalization will restore structure.
        """
        return self._cmp_node() + (self.sorted_deps(),)
```
The comment there actually tells you the issue.  This is left over from earlier versions of Spack, which didn't look at the entire DAG structure, just the dep specs.  The `_cmp_key()` method is used to get the hash and to compare specs, and it's fast.  But we should really be using `dag_hash()` here, as it looks at full DAG structure.  

Here's a reproducer for the problem; if you put this in the `install()` command *after*:
```python
#!/usr/bin/env spack-python
import spack
from spack.spec import Spec

spec = Spec('py-basemap')
spec.concretize()

print hash(spec)      # print hash of `_cmp_key()`
print spec.dag_hash() # print the hash of the canonical yaml DAG.
print
pkg = spack.db.get(spec)
print hash(pkg.spec)
print pkg.spec.dag_hash()                                                           
```
That gives this output:
```
3395388145113120958
lcg6axkak5lgl54mnvxs5xxsg4bnqowf

3395388145113120958
snxmteyyn6qwkzj45kvvbeuaz5yxpzyn
```

Oops :flushed:.  Here is a quick fix: https://github.com/LLNL/spack/commit/7526a8946.  It just changes the package cache in `packages.py` to use the `dag_hash` instead of `__hash__()` (which uses `_cmp_key()`).

I think this issue has not arisen in testing because we haven't dealt with packages quite as complicated before.  The old hash may be sufficient to differentiate most specs, at least within a single `spack` run. I should probably add a sanity test to make sure we don't have hash conflicts between regular and concretized versions of any package's spec.

I had actually tried this change before, just to be consistent, but I didn't put it in because it makes Spack slower, and I didn't realize at the time that it was also needed for correctness.  Here's an example using `py-basemap`:
**develop:**
```
$ time  ./test.py
3395388145113120958
lcg6axkak5lgl54mnvxs5xxsg4bnqowf

3395388145113120958
snxmteyyn6qwkzj45kvvbeuaz5yxpzyn

real	0m4.932s
user	0m4.761s
sys	0m0.115s
```
**bugfix/package-cache-217:**
```
$ time  ./test.py
3395388145113120958
lcg6axkak5lgl54mnvxs5xxsg4bnqowf

3395388145113120958
lcg6axkak5lgl54mnvxs5xxsg4bnqowf

real	0m35.158s
user	0m35.036s
sys	0m0.114s
```
Yuck.  `dag_hash()` is quite slow.  I'm going to talk to @mplegendre tomorrow about ways we could improve on this. Thoughts at the moment so I don't forget:

1. I think we could at least come up with a fast, equivalent in-memory hash.  Modifying `_cmp_key()` should be pretty easy; it just has to do a full spec traverse.  The slow part is that `dag_hash` uses YAML, which is where most of the time is spent.
2. We could have Spack just install `libyaml` when it first runs.  You can seamlessly use the C library---here's what happens when you do that:
    ```
    $ time ./test.py
    3395388145113120958
    lcg6axkak5lgl54mnvxs5xxsg4bnqowf

    3395388145113120958
    lcg6axkak5lgl54mnvxs5xxsg4bnqowf

    real	0m8.806s
    user	0m8.691s
    sys	0m0.109s
    ```
Not quite as bad.
2. We may not even need to cache package instances.  Building them every time might be less expensive than hashing. I need to think about the lifecycle of a `Package` object for this.
3. There are probably way too many spec creations and hash calls in each Spack run right now.  We could go through `concretize` and `normalize` and clean some of them up.
4. An immutable Spec implementation has been on my mind for a while.  It would allow us to cache hashes, and it would get rid of many of the defensive copies currently in the code.

**Comment by lee218llnl** [comment]
OK, thanks Todd, that probably would have taken me a while to track down and your fix seems to be a lot simpler than what I was thinking might be needed. I will do some testing to make sure this resolves everything.

**Comment by tgamblin** [comment]
@lee218llnl @mplegendre: ok I pushed a way faster AND correct hash function.  Can you take a look and test with this one?

This avoids using YAML at runtime (only uses the hashed YAML for output directory names) and it reduces the number of superfluous copies when concretizing `py-basemap` from ~100,000 to ~3,500 :grimacing:.  In the one test I did this is about 2x as fast as the current `develop` branch (and it's correct).  

The old version of `_cmp_key()` would call `sorted_deps`, which would call `flat_dependencies` to get a list of dependencies so that it could sort them in alphabetical order.  This isn't necessary in the `_cmp_key()`, and in fact we want more DAG structure than that to be included in the `_cmp_key()`.

The new version constructs a tuple without copying the Spec DAG, and the tuple contains hashes of sub-DAGs that are computed recursively in-place.  This is way faster than the previous algorithm and reduces
the numebr of copies significantly. It is also a correct DAG hash.

Example timing and copy counts for the different hashing algorithms we've tried:

Original (wrong) Spec hash:
```
106,170 copies
real    0m5.024s
user    0m4.949s
sys     0m0.104s
```

Spec hash using YAML `dag_hash()`:
```
3,794 copies
real    0m5.024s
user    0m4.949s
sys     0m0.104s

New no-copy, no-YAML hash:
```
3,594 copies
real    0m2.543s
user    0m2.435s
sys     0m0.104s
```

So now we have a hash that is correct AND faster.

The remaining ~3k copies happen mostly during concretization, and as all packages are initially loaded.  I believe this is because Spack currently has to load all packages to figure out virtual dependency information; it could also be becasue there ar a lot of lookups of partial specs in concretize.  I can investigate this further.

**Comment by tgamblin** [comment]
@mplegendre @lee218llnl: I was able to build `stat` and `py-basemap` with this bug fix, on cab.  I think this is ok to merge if Greg is happy w/it.

**Comment by lee218llnl** [comment]
Todd, it looks good to me.
