### ISSUE TITLE
spack find : make it accept anonymous specs for v0.10 ?

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#2170]
Many commands already accepts anonymous specs that are used to query the db for a constraint based selection. What is the general sentiment on extending this to `spack find`, i.e. allowing for something like:

```
# finds all the installed packages that depends on openmpi
spack find ^openmpi 

# finds all the packages that are compiled with intel
spack find %intel 
```

?

**Comment by citibeth** [comment]
1. Do we have a decent algorithm for this stuff?

2. Both of the above tasks could be accomplished by grepping through the spec files that get written into package installations.

**Comment by adamjstewart** [comment]
> Do we have a decent algorithm for this stuff?

We definitely do, as `spack uninstall` already works this way. Honestly, I'm starting to get confused/worried about this because it seems like every command has its own spec algorithm:

1. `spack uninstall` works without a package but `spack find` doesn't.
2. `spack compiler` and `spack install` can handle non-specific compiler versions like `gcc@4` but specs can't handle dependencies on `python@2`.

Honestly, I don't know anything about the backend for this, but is there any way we can merge these algorithms, if just for the sake of consistency? Or are these command-specific differences necessary?

**Comment by citibeth** [comment]
I agree on merging algos.  Also, `spack module find` and `spack view` has
similar but different algos.

**Comment by alalazo** [comment]
I started a while ago collecting common arguments / algorithms that are used in commands. The file in which they are gathered is `lib/spack/spack/cmd/common/arguments.py`. The algorithm to do this search is in `ConstraintAction`.
