### ISSUE TITLE
cp2k install conflicts

### ISSUE THREAD

**Issue by mechapple** [LLNL/spack#21889]
I am trying to install cp2k with spack. However, I run into 
Error: Conflicts in concretized spec

### Steps to reproduce the issue

```console
$ spack install cp2k
```

### Error Message

```console
==> Error: Conflicts in concretized spec "cp2k@8.1%gcc@9.3.0~cosma~cuda~cuda_arch_35_k20x~cuda_blas~cuda_fft~elpa+libint~libvori+libxc+mpi+openmp~pexsi~plumed~sirius~spglib cuda_arch=none lmax=5 smm=libxsmm arch=linux-ubuntu20.04-ivybridge/atx5pps"
.....
1. "^fftw~openmp" conflicts with "cp2k+openmp"
2. "^openblas threads=none" conflicts with "cp2k+openmp"
```
I can get rid of the first conflict using:
```console
$ spack install cp2k ^fftw+openmp
==> Error: Conflicts in concretized spec "cp2k@8.1%gcc@9.3.0~cosma~cuda~cuda_arch_35_k20x~cuda_blas~cuda_fft~elpa+libint~libvori+libxc+mpi+openmp~pexsi~plumed~sirius~spglib cuda_arch=none lmax=5 smm=libxsmm arch=linux-ubuntu20.04-ivybridge/ssgitns"
.....
1. "^openblas threads=none" conflicts with "cp2k+openmp"
```
However, I'm not entirely sure if this is the right approach.

### Additional information

```console
$ spack debug report
* **Spack:** 0.16.0-1382-e66b1d4596
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** original
```

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I think this is a limitation of the old concretizer and solved when you enable clingo

**Comment by scheibelp** [comment]
> I can get rid of the first conflict using:
> `spack install cp2k ^fftw+openmp`
> However, I'm not entirely sure if this is the right approach.

When using the older concretizer, that is the right way to do it. You would also probably have to set `^openblas threads=openmp` like

`spack install cp2k ^fftw+openmp ^openblas threads=openmp`

Or

`spack install cp2k~openmp`

might work

If you are able to use the clingo concretizer, that should avoid the need for modifying your original spec (`spack install cp2k`).

**Comment by dev-zero** [comment]
Yes, doing `spack install cp2k ^fftw+openmp ^openblas threads=openmp` is the right thing (if you want openblas and fftw that is). Unfortunately I didn't find any other solution to ensure a consistent build.

**Comment by haampie** [comment]
With the new concretizer you still have to force fftw and openblas to be selected:

`spack install cp2k ^fftw ^openblas`

because otherwise it prefers a different fftw / lapack / blas providers for which it does not have to change variants. For me it defaults to `amdfftw threads=none`, `amdlibflame threads=none`, `amdblis threads=none`.

This could be solved by adding even more conflicts @dev-zero :D but not sure if that is what you want.

I'm closing this issue for now.

**Comment by dev-zero** [comment]
@haampie well, it depends on whether we get consistent results when using a non-threaded fftw and blas/lapack implementation with an OMP threaded CP2K. The reason we have a conflict with openblas threads!=openmp is because we're doing blas/lapack calls inside OMP parallel regions and need openblas to be thread-safe.
For the blis and libflame we don't know yet.
