### ISSUE TITLE
DPDK -MakefilePackage TO MesonPackage

### ISSUE THREAD

**Issue by fubingting** [LLNL/spack#22209]
According to https://github.com/DPDK/dpdk/blob/main/Makefile, the latest version can only be compiled in meson, and all historical versions can be compiled in meson. Can I submit a patch to change the package type?

**Comment by adamjstewart** [comment]
Yes, please do! The exact PR will depend on whether the current versions of the package can be built with Meson or whether they require the old makefile build. I would suggest adding `deprecated=True` to any older versions that don't build with Meson so that they can be removed in a future Spack release, but keeping them for now and allowing them to build with Makefiles. See the `gtkplus` package for a recent example where I did this.

**Comment by adamjstewart** [comment]
Closing this as the original question has been answered.

**Comment by adamjstewart** [comment]
I finally got around to documenting this! Can you see if #25174 does a good job of explaining how to support multiple build systems? If anything is unclear, let me know and I'll try to improve the docs.
