### ISSUE TITLE
Clingo should try harder to avoid deprecated packages

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#22351]
### Steps to reproduce the issue

```console
$ spack spec slurm | grep glib
    ^glib@2.53.1
```

but this version of glib is marked as `deprecated`.

I can nudge clingo into taking a newer version of glib:

```console
$ spack spec slurm ^glib@2.60: | grep glib
    ^glib@2.66.7
```
and it concretizes fine to the latest glib.

The problem is that `glib@2.66.7` depends on `meson` whereas `glib@2.53` does not, and this ultimately pulls in a virtual dependency on `uuid` only for the former.

Apparently clingo prefers fewer virtual dependencies over newer versions, so it ends up preferring `glib@2.53` even though it is deprecated.

When setting `variant('uuid',     default=False,  description='Build uuid module')` by default in Python, `spack spec slurm` concretizes to using `glibc@2.66.7` indeed.

So I think there's 2 issues:

- Clingo should try to prefer new versions over fewer virtual deps
- Clingo should avoid concretizing to deprecated packages when there is an alternative

### Information on your system

* **Spack:** 0.16.0-1812-8d2944bf77
* **Python:** 3.8.7
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Clingo does not currently take "deprecated" into account, as it was added after the new concretizer was introduced. We should add support for this, just like we support "preferred".

**Comment by alalazo** [comment]
@adamjstewart You're correct and I agree that accounting for "deprecated" should be added, but the problem here is inherently different (as I saw debugging this spec). 

We have rules to minimize weights on providers and the weights used are strictly positive at the moment (there were reasons for that, need to check if they still hold). This introduces a bias where a new vdep makes the minimization score higher. 

The optimization to select the latest version of a package kicks in at lower priority, and that's for good reasons. If e.g. OpenMPI is your preferred provider, latest version v4.0.1, and MPICH is the second best, latest version v3.2.0 we don't want that a spec that conflicts with OpenMPI v4.0.1 specifically makes the solver decide to switch to MPICH v3.2.0. We'd rather want to use OpenMPI v4.0.0.

Part of the problem is that there is no easy way (or at least I haven't found it) to reason about average quantities rather than sums over the entire DAG. I don't think that would solve all cases but it would for sure mitigate the occurrences of these issues. Another mitigation, if possible, would be to check if we can score the best possible solution at `0` which wouldn't affect the minimisation score.

**Comment by eugeneswalker** [comment]
Can the dependency count minimization aspect of the new concretizer be disabled via a setting?

**Comment by haampie** [comment]
> The optimization to select the latest version of a package kicks in at lower priority, and that's for good reasons. If e.g. OpenMPI is your preferred provider, latest version v4.0.1, and MPICH is the second best, latest version v3.2.0 we don't want that a spec that conflicts with OpenMPI v4.0.1 specifically makes the solver decide to switch to MPICH v3.2.0. We'd rather want to use OpenMPI v4.0.0.

This is more acceptable than selecting a very old version because the newer versions pull in more virtual deps... Should we just default to concretizing to new versions? The user can always force `pkg ^openmpi` if they're unhappy

**Comment by alalazo** [comment]
> This is more acceptable than selecting a very old version because the newer versions pull in more virtual deps... Should we just default to concretizing to new versions?

Not as simple as that I fear. Let me have a look at this issue again to see if I can find an easy way out.

**Comment by alalazo** [comment]
@eugeneswalker 

> Can the dependency count minimization aspect of the new concretizer be disabled via a setting?

There's no direct dependency count minimization... What is a spec that reproduces your issue? Would:
```console
$ spack solve geopm
```
be sufficient? Asking since I want to determine if it's the same issue or two different but similar ones.

**Comment by alalazo** [comment]
I am having a look at this issue. I'll solve it as suggested in https://github.com/spack/spack/issues/22351#issuecomment-802507256 and give the highest priority to the minimization of deprecated versions. This would be, in my opinion, a sensible behavior since usually versions are deprecated for good reasons (security, serious bugs, etc.).

Nonetheless, I think our ASP-based solver should select in both of the cases reported here the newest version of `glib` and `openssl`  regardless of whether the old versions are deprecated or not. More details on what makes the current logic program select old versions are in https://github.com/spack/spack/issues/22351#issuecomment-802642995. I will not address this issue in the PR that I am about to submit.
