### ISSUE TITLE
CMakePackage: Default Build Type

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#22918]
I realized the default build type for `CMakePackage` in spack is `build_type [RelWithDebInfo]`.

That's cool (I do the same for my projects) because `-g` comes with no real (runtime) cost and adds understanding on crashes; but there is an important detail: due to legacy reasons, most compilers are set up with `-O2` on that build type:
https://github.com/ECP-WarpX/WarpX/issues/1201
https://github.com/ECP-WarpX/WarpX/pull/1203

Are we aware of that and change this somewhere back to `-O3`? Otherwise `Release` might be a better default :)

More background in this thread: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/591

**Comment by ax3l** [comment]
co-assigning people that did a lot of editing in the package and might be interested :)

**Comment by sethrj** [comment]
I think for an HPC software package system the goal should eventually be the "most performant" build -- but since spack is still in development (no 1.0 tag yet) the extra debuggability of packages built using `RelWithDebInfo` could be justification for staying as-is. It's probably worth suggesting in the docs for building out HPC software stacks to add `build_type=Release` under the variants.

The other question is what to do about non-CMake build systems -- is it even worth worrying too much about the cmake packages when autoconf/makefiles add their own arbitrary flags? 😬

**Comment by haampie** [comment]
Hehe, I just made Meson use the same as CMake: #22715. But I can see the argument in favor of Release by default. I do like having at least debug symbols in CI, but of course I could add the `build_type` variant there by hand.

**Comment by jjellio** [comment]
I generally use `Release` and set `*flags=-g` - in my little world, `RelWithDebInfo` can also mean more things. (e.g., in Trilinos that means some additional 'Debug' checks can get enabled).... the dirty laundry of HPC builds (and the moral of that story, just set release + `-g` ><)

That said - I wouldn't change the default (I'd have it on par with whatever Kitware uses).

@sethrj You may want to see PR #22779 - I need to set `RelWithDebInfo` to be `-O2 -g`, but the gist is to work towards providing some kind of top-level variant that could steer all packages into a uniform direction.

**Comment by ax3l** [comment]
> That said - I wouldn't change the default (I'd have it on par with whatever Kitware uses).

I would not change the meaning of `RelWithDebInfo` inside spack either, that's too surprising. The default of [CMAKE_BUILD_TYPE](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) is undefined though, so if we go for `Release`/`RelWithDebInfo`/`Debug` by default is our choice.

I'll ask a few people for E4S if they are aware of this, I could imagine that a lot of packages get built with our default flags and thus might deliver sub-ideal performance on HPC systems as of now.

**Comment by adamjstewart** [comment]
I added this variant in #4797. I know very little about CMake, so I'm personally fine with changing the default to whatever the community agrees on.

**Comment by ax3l** [comment]
Variant looks good, but we are still defaulting to `RelWithDebInfo` instead of `Release`.
I would argue we should default to `Release`.
We can still inject `-g` if needed via a Spack-ish approach, but using `-O2` for most of the things by default (due to `RelWithDebInfo`) looks just dangerous to me.

**Comment by ax3l** [comment]
@tgamblin I see all packages on Fugaku being build with `-O2` these days, because they keep the Spack default.

**Comment by ax3l** [comment]
@chuckatkins Do you like to talk to Brad to revisit https://gitlab.kitware.com/cmake/cmake/-/merge_requests/591 using a CMake `policy` for the change?

**Comment by white238** [comment]
We recently ran into this by noticing how large our unit tests were getting.  The increase in file size is significant. PR here showing some real world size differences:

https://github.com/LLNL/serac/pull/764

**Comment by kwryankrattiger** [comment]
I don't know if changing the default is really a good plan of action. I think `RelWithDebInfo` has a lot of utility in spack builds since most environments, that I have seen at least, are being used for development or on beta/early access HPC systems. Even that aside, the fact that everything is built from source with minimal/no testing on the target system makes having debug info in stack traces extremely valuable when reporting bugs. In an ideal world all of the packages in spack would have tests to validate the build/install but that isn't the case.

Having the option, for the cases where stacks have been tested and verified using `RelWithDebInfo` builds, and are ready for production deployments, `Release` makes a lot of sense. But in that case, I think having to turn that on explicitly is not an insurmountable hurdle, and will likely only be done a handful of times per year for most sites using Spack.

As someone with a rather large number of testing environments floating around, I don't really want to have to go and fix all of those to not build `Release`. I have only a few release environments to update in comparison, and only one that will actually need `build_type=Release` since there is only one release targeting a real production environment at the moment.

**Comment by alalazo** [comment]
Here there are real numbers in terms of size reduction: https://github.com/LLNL/serac/pull/764

**Comment by blue42u** [comment]
I personally haven't found much utility in debug info for my Spack-built binaries. The source gets blown away with the build stage and I can't (and refuse to) debug someone else's code without it. (Also, the errors I debug most often involve GPU vendored libraries, which are already stripped and there's nothing that can be done for that.)

The size reduction that comes from stripped binaries is far more enticing to me than the minuscule benefit I would get from having debug info. I've whacked my head on quota limits many a time.

I don't think Spack can do this, but other package distributions are able to install the debug info "later" if needed, e.g. on Debian if I had issues with my system `libpng` I could install `libpng-dbg` to get debug info. That is a really nice feature that I wish Spack could provide, but I don't have a clear method in mind that would make it possible.

**Comment by white238** [comment]
I agree with @blue42u . If the default is to not keep the build stage around then that doesn't seem to go with having `RelWithDebInfo` as the default build type. 

Personally, if I am going to debug a package, I am going to rebuild it as a one-off and with `build_type=Debug`.

My assumption is most people don't realize how much space is being taken up by these builds, but that isn't backed up by anything. The teams I am on  (Axom and Serac) are negatively affected by this default.
