### ISSUE TITLE
Linking with virtual dependencies ex: blas/lapack

### ISSUE THREAD

**Issue by nrichart** [LLNL/spack#234]
I was wondering if there are already some thought on exporting linking information for packages providing a virtual dependency.

In the case of blas/lapack the way to link with a given package could change. For now only `netlib` and `openblas` package are providing `blas`. Openblas already has a trick to have a libblas.a

But if at a point atlas also provides `blas` it is already not so easy to link with it. Especially if you consider the shared libraries that can be build as a sequential or threaded library `libsatlas.so` and `libtatlas.so`. This becomes even more complicated if you want to link with libraries like the mkl.

For package using cmake as a make system a way would be to set the environment variable `BLA_VENDOR`. But I guess that this would cover only few packages.

For all the others, a solution would perhaps be to have a way for packages to express in there spec different {c, fc, cxx}flags and ldflags that can be used to link with them.
With variation of this flags with a default that should always be there and then variation of them for example for threaded atlas or mkl.

**Comment by tgamblin** [comment]
I've discussed this quite a bit in other contexts with @fpruvost and @markcmiller86.   I think Mark actually has a fork that implements some of this. Right now there are two ways you could do this... each requires a naming convention.  So:

1. Settle on some names for your variables, e.g. `fc_link`, `f90_link`, etc.

2. Then, do either of these:
    1. Add class properties on each implementation package that have the names you came up with and refer to them through the `spec` in the client code.  e.g.:
        ```python
        class Atlas(Package):
            provides('blas')
            ...
            fc_link = '-lsatlas -ltatlas'
            cc_link = fc_link
            # etc.
        ```

        ```python
        class LinksToAtlas(Package):
            depends_on('blas')
            ...
            def install(self, spec, prefix):
                fc_linker_args = spec['blas'].package.fc_link
                cc_linker_args = spec['blas'].package.cc_link
                # etc.
        ```
    2. Implement a `setup_depdendent_environment` method in each concrete package that sets some module variables, e.g.:
        ```python
        class Atlas(Package):
            provides('blas')
            ...
            def setup_dependent_environment(self, module, spec, dep_spec):
                module.blas_cc_linker_args = '-lsatlas -ltatlas'
                module.blas_fc_linker_args = module.blas_cc_linker_args
                # etc.
        ```

        ```python
        class LinksToAtlas(Package):
            depends_on('blas')
            ...
            def install(self, spec, prefix):
                # blas_fc_linker_args and blas_cc_linker_args are in global scope.
        ```

Both of these involve an implicit contract (the names) that `blas` providers need to follow.

I tend to like the first one better because it doesn't require me to prefix names to avoid naming conflicts.  The problem with the first one is that you can't do anything dynamic.  If you set properties on a dependency package *instance* right now, they'll be gone when the dependent builds, because the dependency builds in a child process and any instance variables set don't affect the parent process.  

The second one works because `setup_dependent_environment` is called on each dependency package before the dependent's build.  This happens after the fork, in the child process, so you could do something more dynamic.  The issue is that you really only have the `module` scope to set variables on, although I suppose you could set properties on `spec` or `spec.package`.

I would be interested in suggestions for how we might come up with a more *explicit* contract system for stuff like this.  One thought would be to make virtual dependencies actually have classes that describe what variables they need to set -- then we could enforce things like linker args contracts.  

Side note: Making vdeps have classes would probably be a nice thing to do anyway -- virtual dependencies are currently only known to be virtual because there *isn't* a package with that name. If someone adds a package with that name later, things don't work as intended.  It's not so much of an issue yet but it would be nice to have a placeholder package to "reserve" a name for vdeps.

**Comment by nrichart** [comment]
In fact, for now it is not a direct problem since we cannot easily have external package as `mkl`.
But by writing a package that depends on `blas` I saw a problem that will arise at a point for us.

In fact your second solution is nice since the value can be modified based on variants and it does not have to be in the module.

I just made a small try that is a mis between 1 and 2. (epfl-scitas/spack@56ccee9f6e06438e5400d93ec2d119f5877cd7a0) with something like
```python
def setup_dependent_environment(self, module, spec, dependent_spec):
    lib_suffix = '.so' if '+shared' in spec['blas'] else '.a'

    spec['blas'].fc_link = '-L%s -lrefblas' % spec['blas'].prefix.lib
    spec['blas'].cc_link = spec['blas'].fc_link
    spec['blas'].libraries = [ join_path(spec['blas'].prefix.lib, 'librefblas%s' % lib_suffix) ]
        
    os.environ['BLA_VENDOR'] = 'Generic'
```
And for now tests are going promising, I tested it on `netlib-lapack` by specifing the `BLAS_LIBRARIES` and by using the `find_package(BLAS)`, in shared and static configurations.

But it is true that to have a explicit contract would be nicer. I'm not so familiar with the core of spack to know what it would imply to write class for vdeps.

**Comment by tgamblin** [comment]
If we did this we'd just make a vdep a Package like any other, but with a virtual tag on the package itself.  This would actually be pretty easy:
```python
class Foo(Package):
    virtual = True
```

We could then add some directives to say that the package has required properties:
```python
class Blas(Package):
    virtual = True

    required_property('cc_flags')
    required_property('blas_libname')
```
etc. 

Then when a package `provides('blas')` it would need to have those properties and Spack could check it.  You could also think about having more complex check functions, or testing logic, but I would want the above functionality working first.

I actually think this wouldn't be so hard to add, but there are other things higher on my priority list at the moment.  I would recommend that we stick with the simple conventions for now and keep this in mind -- it will be useful to see the ways people are exporting info between packages before implementing a contract capability like this.

**Comment by nrichart** [comment]
If I got it right this can be done in too steps, first having a class for virtual packages. That in any case is useful as a placeholder. And the second step is to use this class to  enforce a contract.

If no one is currently working on this I can give a look at least for the first part.
I checked with @alalazo that already changed some part in the code of spack, and we can try to make a proposition of implementation. Most probably not before january do to the vacations.

For the second part are you interested by the try I made in epfl-scitas/spack@56ccee9f6e06438e5400d93ec2d119f5877cd7a0 in witch case after finishing the changes in openblas and scalapack I can create a PR. As a first step to defining a contract that should be defined.

**Comment by fpruvost** [comment]
Hi,

interesting discussion!
But here we are actually trying to do what nice libraries should normally do: give the way they have been built (libraries generated, header/lib dirs, compiler flags, libraries they depend on). For example generating a pkg-config file.
I do not understand why scientific libraries do not provide such important information in a generic way shared by the community.

So a good answer to this problem should certainly be to force libraries going into spack to provide a pkg-config file (.pc) so that you don't have to develop this feature and to avoid redundant work between developers of libraries and spack packagers.
Because this work seems out of the scope of spack for me.
If in a new release, the name of some libraries changes or if suddenly it requires a -lpthread in the link to work, the spack package would have to be changed. This work should be driven by the developers who know precisely those information in the course of the development.

That being said, we need a hack for now because many libraries do not provide the information the same way or do not provide any info at all!
For the packages we develop at Inria Bordeaux, we use the "setup_dependent_environment" solution which gives satisfaction for our use.

By the way, why do you plan to restrict this feature for virtual packages only?
Some packages such as scotch can be built in many different ways involving many different link variants (-lscotch, -lptscotch, -lesmumps).

For example my setup_dependent_environment function for scotch to provide the good link:

    def setup_dependent_environment(self, module, spec, dep_spec):
        """Dependencies of this package will get the libraries names for Scotch."""
        if spec.satisfies('+shared'):
            libext=".dylib" if platform.system() == 'Darwin' else ".so"
        else:
            libext=".a"
        libdir = self.spec.prefix.lib

        scotchlibname=[os.path.join(libdir, "libscotch%s") % libext]
        scotcherrlibname=[os.path.join(libdir, "libscotcherr%s") % libext]
        scotcherrexitlibname=[os.path.join(libdir, "libscotcherrexit%s") % libext]
        ptscotchlibname=[os.path.join(libdir, "libptscotch%s") % libext]
        ptscotcherrlibname=[os.path.join(libdir, "libptscotcherr%s") % libext]
        ptscotcherrexitlibname=[os.path.join(libdir, "libptscotcherrexit%s") % libext]
        esmumpslibname=[os.path.join(libdir, "libesmumps%s") % libext]
        ptesmumpslibname=[os.path.join(libdir, "libptesmumps%s") % libext]

        otherlibs=["-lm"]
        if spec.satisfies('+pthread'):
            otherlibs+=["-lpthread"]
        if spec.satisfies('+compression'):
            otherlibs+=["-lz"]
        if platform.system() == 'Linux':
            otherlibs+=["-lrt"]

        module.scotchlibname = []
        if spec.satisfies('+esmumps'):
            if spec.satisfies('+mpi'):
                module.scotchlibname+=ptesmumpslibname
                module.scotchlibname+=ptscotchlibname
                module.scotchlibname+=ptscotcherrlibname
            module.scotchlibname+=esmumpslibname
        else:
            if spec.satisfies('+mpi'):
                module.scotchlibname+=ptscotchlibname
                module.scotchlibname+=ptscotcherrlibname
        module.scotchlibname+=scotchlibname
        module.scotchlibname+=scotcherrlibname
        module.scotchlibname+=otherlibs

**Comment by tgamblin** [comment]
@fpruvost: 

> So a good answer to this problem should certainly be to force libraries going into spack to provide a pkg-config file (.pc) so that you don't have to develop this feature and to avoid redundant work between developers of libraries and spack packagers.

I think the issue here is, as you note, that we can't force them to do this.  I need to write a spack philosophy statement, but one of the things I take from other systems is the notion of "pristine source" -- i.e., we must take the distribution the way the developers put it out.  Forcing the developers to include pkg-config files is not the worst idea, but there are always going to be some who won't do it, especially in HPC :smile:  So `pkg-config` is definitely nice if it's there, but i think we need something cleaner.

I *think* you agree since your scotch example is basically making up for the lack of pkg-config in scotch :smile:.

I don't think this has to be restricted to virtual packages. I think the same conventions should apply to regular packages -- i.e. we should use the same attribute names to export things like link flags.  We were just saying that for virtual packages, we can enforce the interface by checking it, and this is useful because we could check whether new implementations of the vdep conform to the interface.

But you bring up an interesting point, which is whether things like "this package exports linker args" should be a more general interface.  I'm curious whether its worth it to check things like this or whether doing it by convention is enough.

**Comment by fpruvost** [comment]
@tgamblin: 
> I think you agree since your scotch example is basically making up for the lack of pkg-config in scotch

you're right, we can't force this ;) Many scientific libraries, it is the case at Inria :fr:, do not deliver a pkg-config or equivalent. But still, what a pity!



> We were just saying that for virtual packages, we can enforce the interface by checking it

ok, I did not get that :confused: , thanks for the clarification.

**Comment by nrichart** [comment]
I would say that in general imposing an interface would be to constraining, for most of the libraries the build systems like configure or cmake knows how to handle them.
So there are only few cases (i hope) where you need to get information from the package itself.

And most of this case have other solutions, for scotch for example you can apply the patch used by debian and build a shared library, then linking is as simple as `-L<path_to_scotch> -lscotch`. All variations are taken care by the build process at which point you have all the link information. And all this complexity is "hidden" a single library file.

@fpruvost the discussion started on virtual packages because it is where the problematic was seen at first. And the idea was to perhaps add an interface the virtual packages and check that it is implemented.

But in a more generic case we where discussing with @alalazo that perhaps what we need is to be able to "communicate" with a package the perform some action based on some configurations. Actions could be to of the type provide the compile and link flags, or configure the variants based on what other packages need, as discussed in #391

**Comment by davydden** [comment]
> One thought would be to make virtual dependencies actually have classes that describe what variables they need to set -- then we could enforce things like linker args contracts.

I would like to share some experience extending Homebrew/Linuxbrew to build with MKL Blas-Lapack. Here is the currrent Ruby class which works on OS-X (clang/gnu fortran) and Ubuntu (GNU compilers) with MKL https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/requirements/blas_requirement.rb . 
It would be good if Spack will indeed have a base class for blas-lapack which specifies: `fc_link`, `c_link`, but also names of the libraries: for system provided `{blas;lapack}`, for openblas `{openblas}` and for MKL `{mkl_intel_lp64;mkl_seuqntial;mkl_core}`; as well as  `lib` and `include` folders. Unfortunately, not every software can be built with, say, MKL only by providing linker flags. Sometimes Blas/Lapack has to be provided in a very different ways (links are to the relevant parts of the ruby code): 

* semicolon separated names [Trilinos](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/trilinos.rb#L122-L130)   ; 
* ldflags [superlu_dist](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/superlu_dist.rb#L33) and [p4est](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/p4est.rb#L34) and [mumps](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/mumps.rb#L107-L108) and [arpack](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/arpack.rb#L36-L37); 
* full path [petsc](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/petsc.rb#L98-L99) and [deal.ii](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/dealii.rb#L63-L64); 
* space separated names [hypre](https://github.com/davydden/homebrew-dealiisuite/blob/mkl_extra_param/hypre.rb#L36-L43) .

Then, if every blas-lapack packaged derived from the interface implements those required fields, it can be used as a dependency in other packages without
```
if blas == mkl

else if blas == openblas

else if blas == system

end
```
It would also be easy to add other Blas-Lapack implementations such as `atlas`.

On a related issue, Scalapck is also complicated in this sense. Self-compiled version `2.0.2`, AFAIK, has a single library `scalapack` that includes blacs, whereas MKL ships them as two separate libraries `mkl_scalapack_lp64;mkl_blacs_mpich_lp64`. I suspect same issues could apply to `FFTW`. I guess in these cases you can't really ask for a `pkg-config` file.

**Comment by davydden** [comment]
i came across my old notes on how to build `Trilinos` with `atlas` and saw this part of CMake config related to `blas`, so I thought I mention it here as it illustrates the usage scenario
```
 -D BLAS_LIBRARY_NAMES:STRING="cblas;f77blas;atlas" \
 -D BLAS_LIBRARY_DIRS:PATH=/opt/local/lib \
```

**Comment by davydden** [comment]
oh, and here's how `EasyBuild` use different blas's/lapack in trilinos https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/t/trilinos.py#L108-L120
