### ISSUE TITLE
Clingo bootstrapping: reinstalling already installed packages

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#23890]
If I tell Spack to use the new concretizer but don't have `clingo` in my `PATH`/`PYTHONPATH`, Spack will bootstrap it for me. However, it doesn't seem to check whether `clingo` or its dependencies are already installed. This leads to Spack wasting time reinstalling the same hashes of dependencies.

### Steps to reproduce the issue

1. Set `clingo` as the default concretizer, make sure `clingo` is not in your `PATH`
2. `spack install` anything, this will cause Spack to try to bootstrap clingo
3. Spack will try to install `libiconv`, `libsigsegv`, `berkeley-db`, etc. even if they are already installed
3. Hit <kbd>Ctrl</kbd>+<kbd>C</kbd> during the install
4. Run again and notice that Spack tries to reinstall `libiconv` and friends.

### Information on your system

$ spack debug report
* **Spack:** 0.16.1-2888-a284edb852
* **Python:** 3.8.10
* **Platform:** darwin-catalina-ivybridge
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@adamjstewart Bootstrapping is done in a separate store to keep the software that Spack needs for itself separated from the one that was requested by the user. This also permits to have more control over what gets installed when bootstrapping, rather than picking specs that have been installed by the user and may or may not be compatible with what Spack needs.

This is to say that the behavior is "by design" and while long,  it's a one time installation per Spack instance. Also, build time from sources can be improved a lot if you:
```console
$ spack external find cmake bison
```
Hopefully #22720 will improve this aspect of bootstrapping once it lands.

**Comment by adamjstewart** [comment]
Alright, as long as this is by design. Binaries will definitely help with this.

**Comment by alalazo** [comment]
BTW, if you have some time and want to try #22720 instructions are in the PR description :smirk:
