### ISSUE TITLE
Error on using last commit of develop branch

### ISSUE THREAD

**Issue by thiagotei** [LLNL/spack#2417]
Get the error whenever I call spack:

```
-bash: ZSH_VERSION: unbound variable
```
Using commit  from  8f0b91edaaaa6a29aa57dbb099a9a444f4e2a46f develop branch.

**Comment by adamjstewart** [comment]
Let me guess. You're using Bash. And you're sourcing `share/spack/setup-env.sh`. But you have something like `set -u` in your `~/.bashrc`, which puts Bash into strict mode:

> Treat unset variables and parameters other than the special parameters "@" and "*" as an error when  performing parameter  expansion.   If  expansion is attempted on an unset variable or parameter, the shell prints  an  error message,  and, if not interactive, exits with a non-zero status.

I wouldn't recommend setting `set -u` in your `~/.bashrc` because it breaks expected functionality in most shell scripts. But I think we can accommodate you without too much trouble. Let me write up a PR.

For anyone interested, check out [this article](http://redsymbol.net/articles/unofficial-bash-strict-mode/).

**Comment by alalazo** [comment]
:+1: for the article
