### ISSUE TITLE
intel-oneapi-compilers does not correctly interact with hierarchical (lmod) modulefiles system

### ISSUE THREAD

**Issue by manomars** [LLNL/spack#24195]
Loading the `intel-oneapi-compilers` module does not correctly unlock the path to packages compiled with it in the `lmod` module system.

### Steps to reproduce the issue

I installed the `intel-oneapi-compilers` package and used it to compile `openmpi-4.1.0`.
Then I re-generated the `lmod` module files.

```console
$ spack install intel-oneapi-compilers target=x86_64
$ spack compiler add /opt/intel/oneapi/compiler/latest/linux/bin/intel64
$ spack compiler add /opt/intel/oneapi/compiler/latest/linux/bin
$ spack install openmpi+legacylaunchers@4.1.0 %intel@2021.2.0 target=x86_64
$ spack module lmod refresh
```

### Error Message

Loading the `intel-oneapi-compilers/2021.2.0` module works just fine
```console
$ module load intel-oneapi-compilers/2021.2.0
```
but a subsequent `module avail` does not show the `openmpi/4.1.0` module to be unlocked by the previous load.

I have looked into the module files created for `intel-oneapi-compilers`: `share/spack/modules/linux-centos8-x86_64/Core/intel-oneapi-compilers/2021.2.0.lua` and the problem appears to be that this module file does not prepend `share/spack/modules/linux-centos8-x86_64/intel/2021.2` to $MODULEPATH.

Adding:
```console
prepend_path("MODULEPATH", "/opt/share/spack/share/spack/modules/linux-centos8-x86_64/intel/2021.2.0")
```
to `share/spack/modules/linux-centos8-x86_64/Core/intel-oneapi-compilers/2021.2.0.lua` solves the problem.

### Information on your system

* **Spack:** 0.16.2-3000-e4a559a571
* **Python:** 3.6.8
* **Platform:** linux-centos8-cascadelake
* **Concretizer:** original

I've used the following `modules.yaml` file:
```console
modules:
  default:
    lmod:
      core_compilers:
      - clang@10.0.1
      - gcc@8.3.1
      hierarchy:
      - mpi
      hash_length: 0
      whitelist:
      - gcc
      - intel-oneapi-compilers
      blacklist:
      - '%gcc@8.3.1'
      projections:
        all: '{name}/{version}'
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by ilbiondo** [comment]
This was discussed in the Slack modules channel but sadly as it's the free version we can no longer see it :-(

The problem is that the name of the compiler has no relation to the name of the package (unlike intel and gcc) so the special treatment for compilers in lib/spack/spack/modules/lmod.py is ignored.

A workaround (that I haven't yet made a PR for) is to add the following to `lmod.py` - there's already a special case for llvm/clang

```
# Special case for OneAPI
 if self.spec.name == 'intel-oneapi-compilers':
     provides['compiler'] = spack.spec.CompilerSpec(str(self.spec))
     provides['compiler'].name = 'intel'
```

This is okay if one wants to use the classical intel (icc/ifort) compilers but breaks things for  `%oneapi` as the package provides 2 compiler families:

```
-- intel rhel8-x86_64 -------------------------------------------
intel@2021.2.0
-- oneapi rhel8-x86_64 ------------------------------------------
oneapi@2021.2.0 
```

According to @alalazo and @becker33 fixing this in a permanent way so that one spec can provide multiple compilers isn't at all obvious.

As an aside, I also add a projection so that the compiler is still available via `module load intel`

```
 projections:
   intel-oneapi-compilers@2021.2.0: intel/2021.2.0
```

**Comment by manomars** [comment]
Many thanks for the quick reply! Works perfectly for me (I'm using the classical compilers)!
