### ISSUE TITLE
Can I use URLFetchStrategy w/out a checksum?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2494]
The texlive distribution seems to roll out new tarballs at the drop of a hat.

I thought about just deleting the digest and treating it like 'develop' (even renaming the version) but URLFetchStrategy seems to insist on a digest.

So two questions:

1. is there a directive/interface that I can use to specify "Here is the URL for a tarball, it's untrusted."

2. Should I, or should we just keep trying to keep up with them?  The distribution is called Tex*live*, after all...

**Comment by adamjstewart** [comment]
@citibeth

**Comment by citibeth** [comment]
The short answer is "no."

Does TeXLive roll out new tarballs on the same URL?  That would be a problem we need to think about...

**Comment by citibeth** [comment]
MacPorts can install TeXLive.  What do they do in their recipe?

**Comment by citibeth** [comment]
You probably want to mirror/download the TeX repo as a Spack resources.  The standard network install for TeXLive would not be legal in Spack.

https://www.tug.org/texlive/acquire-mirror.html

Then again, much of what Spack is built to do isn't so necessary for TeX.

**Comment by hartzell** [comment]
> Does TeXLive roll out new tarballs on the same URL? That would be a problem we need to think about...

Yes.  Sigh...

I used to support TeX installations from first principles but it's become such a circus (and I use TeX tools much less seriously than I used to) that I'm not particularly interested in crafting a *de novo* install, they've simply made it too hard.  It's another instance of "instead of cleaning up stuff, we'll just hide it all behind a shower curtain (Docker, I'm looking at you...)" aka "We build binaries, just use them...".

If there were a lot of folks who were interested and could test out the exotic bits, I'd collaborate on it.

In the meantime....

> The standard network install for TeXLive would not be legal in Spack.

There's already a Spack package for the standard network install.  Sounds like @becker33 should be flogged with a damp noodle for letting that guy @hartzell sneak it in.

It's currently broken.  I can either update the digest (again), let you delete it (:sad:), or figure out someway to treat it like a head checkout of a git repo.

**Comment by becker33** [comment]
I’ll consider myself suitably flogged.

@tgamblin do you have an opinion on this? For now I think it would be fine to update the digest. In the long run I think we want to figure out a way to treat it like a head checkout of a github repo.

**Comment by citibeth** [comment]
I've spent some time looking at the TeXLive distro, and thinking about it.  My more informed thoughts are:

Spack provides the service of coordinating a bunch of packages in a DAG, in which you know exactly what is depending on what.  Builds are repeatable (with the same Spack, `packages.yaml`, etc).  It can download and install 1000+ pieces of software.

The TeXLive network install is an installer that can install TeX packages.  Like other foreign installers, it exists outside the purview of Spack and will not use Spack packages for its dependencies.  Unlike many such installers, it gives you particularly poor control over versions: nothing more than "you'll get the latest versions of everything."

As with other foreign installers (Lua stuff, PIP, etc), Spack and TeXLive just don't mix.  Even if the TeXLive installer were versioned, Spack wouldn't be able to keep track of what's been installed inside it.

Clearly, the theoretically right way to approach this problem is to do the TeXLive install using Spack.  This would require porting the underlying TeX packages on by one; maybe start by looking at what MacPorts has done with its `texlive-basic`: https://github.com/macports/macports-ports/blob/master/tex/texlive-basic/Portfile .  Or look at the TeXLive installer script (80K+ of Perl; maybe better to look at MacPorts or Fedora packaging).

This approach would be a lot of work.  But if/when it matures and works well, it would be a better installer than the bespoke one currently shipped with TeXLive.  In an ideal world, Spack would become the official installer for the TeXLive distro, and the TeXLive folks would become enthusiastic Spack packagers.

--------

Now thinking of use cases... I find it highly unlikely that TeXLive will be used as part of a big job in a supercomputer cluster that is disconnected from the Internet.  In reality, I see this as a way for existing Spack users to get a package they need.  In spite of all its flaws (in the Spack world), maybe having TeXLive installer do its own thing isn't such a bad idea.  **It would be nice if there's a way to declare to Spack that "this package downloads stuff during its install() phase**.

As for the digets... unless TeXLive computes checksums on the things IT downloads, checksums on the installer itself will be of minimal benefit.  If we've come this far, why don't we break Spack all the way and let it download the TeXLive tarball without any verification...  At least we should warn the user / prevent her from doing it unless she says "Yes I really want to do this."

**Comment by citibeth** [comment]
BTW... if `rename` needs `perl` as a build dependency, then `texlive` should probably have it as well (I don't know if it does already).

**Comment by tgamblin** [comment]
Would it be reasonable to piggyback on one of the TeXLive versions maintained by the various distros already out there?

* https://www.tug.org/texlive/distro.html

We would not have the "latest" version, but we would at last have a stable version in Spack.

**Comment by citibeth** [comment]
I think it would be great if Spack could use the recipes from one or more
of those distros.  If that were possible (and in theory it is possible),
then we could get a lot of new Spack packages for "free" (or at least for
cheap).

**Comment by tgamblin** [comment]
I think in this case we could just use the distro URLs instead of the "official" (but broken) URL.  If we want the latest develop version to function like a develop version, we can put it in as `svn` via https://www.tug.org/texlive/svn/.  Then you at least have SSL protecting you for the SVN checkout, and we label it `develop` per convention so people know what they're getting.

Sound good?

**Comment by citibeth** [comment]
I like your idea of downloading from distros.  I doubt anyone needs a
Spack-installed latest-development version of TeXLive.

**Comment by tgamblin** [comment]
I guess we need to choose a distro to follow -- `pkgsrc` looks like a decent option, but I am not sure how current any of them stay or how reliable their releases are.  Might be good to look into that.

FWIW, homebrew doesn't bundle TeXLive because of exactly this crap, and they just recommend you install `mactex` instead, which is available [cask-only](https://caskroom.github.io).

**Comment by citibeth** [comment]
I've been happy so far installing TeXLive with MacPorts (on my Mac) and
CentOS7 (on my Linux machine).  But I suppose that someone stuck with an
ancient Linux machine who needs LaTeX might be out of luck.  Maybe they can
just install using the TeXLive installer script?

I'd be interested in understanding the motivation behind Spack's `texlive`
package.

**Comment by hartzell** [comment]
@citibeth -- 
> I'd be interested in understanding the motivation behind Spack's `texlive`
> package.

Speaking only for myself (though I am the perpetrator...), I'm looking for tooling that will let me set up computational biology/bioinformatics computing environments.  Within an organization, my concern spans "HPC" clusters (managed by sun/univa grid engine) + individual linux boxes that share storage, stand alone systems on site, and various systems spun up in the cloud (clusters using e.g. cfncluster, individual systems, etc...).  OS varies across the mix from CentOS5 to CentOS7 + various debian based distros.  Some of the users are sophisticated linux-oids while others spend their entire life in a Java IDE.

I want a well principled tool to organize and systematize building and installing "all of the things".  I look to the base OS for things that the OS controls and for things that people are willing to have change on the OS's schedule.  Beyond that, we need to install our own.

With a reasonable amount of effort on "my" part (ps, thanks again to @everyone who keeps helping me!) I'm hoping to use Spack to manage the "cattle" among my applications and minimize the set of "pets" that I need to manage individually (I have this crazy image of me, in the light of a kerosene lamp, bottle-feeding a young TeXLive deployment...).

If a group/system is going to have a non-repeatable deployment of a tool (perhaps e.g. TeXLive), I'd like to see that deployment encapsulated in familiar tooling.  The fewer one-offs I make teams deal with, the more likely it is that we'll have consistent installations, even if they're not strictly repeatable.   Perhaps my use case values *consistency* a bit more than *repeatability*.

So, that brings me (*finally*) to TexLive.  Various folks here need TeX stuff.  TeXLive seems to be the accepted standard for that community and Spack's texlive package was just a r{iff,ip-off} of LinuxBrew's.  Doing "better" seems to require a lot of work (*I will look into the MacPorts and etc... package brought up earlier in this thread*).

I'd rather have a completed set of apps that install confidently and consistently than a highly repeatable TeX deployment, so that's where my effort is going.  I have had precisely *one* end-to-end build of my prototype set of apps (see below) work (and that blew up when I uninstalled and tried to reinstall (#2497)); that's where I'm focussing my effort (I'd like to contribute it to the test suite discussion).

F.W.I.W., here's the build script I'm trying to get working (the compiler bit will become smarter...)

```
# Compiler
spack install gcc@5.4.0

# This might not do what you want if there's already
# a 5.4.0 on the system....
# Now all of the things will be built with %gcc@5.4.0
spack compiler add --scope site $(spack location -i gcc@5.4.0)

# R things
spack install R@3.3.1
spack install r-devtools@1.11.1
spack install r-shiny@0.13.2
spack install r-xml@3.98-1

# python things
spack install python@2.7.12
spack install py-flake8@3.0.4
# what other packages to we want to install?

spack install ack@2.14
spack install ant@1.9.7
spack install bcftools@1.3.1
spack install boost@1.62.0
spack install bwa@0.7.15
spack install cask@0.8.1
spack install cmake@3.6.1
spack install emacs@24.5
spack install emacs@25.1+X
spack install fastx_toolkit@0.0.14
spack install git@2.9.3
spack install go@1.7.4
spack install hdf5@1.8.15
spack install htop@2.0.2
spack install htslib@1.3.1
spack install jdk@8u92-linux-x64
spack install lapack@3.6.1
spack install lmod@6.4.5
spack install maven@3.3.9
spack install nextflow@0.20.1
spack install openblas@0.2.19
spack install parallel@20160422
spack install perl@5.22.2
spack install perl@5.24.0
spack install prank@150803
spack install samtools@1.3.1
spack install seqtk@1.2
spack install swig@3.0.10
spack install texlive@live
spack install tmux@2.3
spack install tree@1.7.0
spack install unison@2.48.4
spack install valgrind@3.11.0
spack install xauth@1.0.9
```

**Comment by citibeth** [comment]
Thank you for taking the time, that was really interesting.  As I said
before... I think you should just finish the TeXLive stuff in the most
expedient way, and forget about doing it in a theoretically "correct" way.
I would just add warnings explaining what's going on in the TeXLive
`package.py`.

**Comment by tgamblin** [comment]
@hartzell: Thanks from me too.  Use cases are always good to have.  I wonder how often @everyone gets mentioned in random threads on github 😄 

To answer your original question, though:

1. No, you can't have a URL version without a checksum -- we don't allow that.
1. You *can* use the `--no-checksum` argument to `spack install` if you want to explicitly disable checksumming.  You can also globally change this in [`config.yaml`](http://spack.readthedocs.io/en/latest/config_yaml.html) (see the `checksum` option).
