### ISSUE TITLE
Allow multiple versions of the same package in the DAG in some situations.

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#2510]
Part of my goal here: #2320 is to make `py-jupyter_notebook` work for both python 2 and python 3. The problem is that `node-js` (a dependency of `py-jupyter_notebook`) requires python 2 and not python 3 for their build system to work. When I change the `node-js` speciifcation to reflect this, I get the error

```
spack install py-jupyter_notebook ^python@3.5.2~ucs4
==> Error: Invalid spec: 'python@3.5.2~ucs4^bzip2^ncurses^openssl^readline^sqlite^zlib'. Package python requires version 2.7:2.7.999, but spec asked for 3.5.2
```

Likely because concretization has selected 3.5.2 as 'the' python package to use so it won't use a separate python for a build dependency of one of the packages.

I believe that spack's DAG needs to be more flexible to allow situations like this.

This is related to the discussion here: #2448 about how build dependencies are 'promoted' to run dependencies if that package is listed as a run dependency for a superior package. This is another example why this is bad behavior.

**Comment by adamjstewart** [comment]
I agree that instead of preventing the same package from being used twice, we should prevent the same spec/hash from being used twice. This would also fix the problem I ran into in #2495 where `libxext` depends on Python, and I have `+tk` enabled, but tk depends on python as well. If I could simply build with `python~tk`, the problem would go away.

There are orthogonal discussions going on in #2504 that you may want to take a look at. Probably elsewhere too.

**Comment by krafczyk** [comment]
Is there a DAG improvements general issue where we can talk about and aggregate all the DAG improvement we want?

**Comment by becker33** [comment]
#839 is designed to address this, as does #1770. Both are still WIP.

**Comment by krafczyk** [comment]
Thanks for pointing these out to me.

**Comment by citibeth** [comment]
See also #2504 #2498 #2495 #2098 

As a workaround, temporarily remove the build dependencies for Python.  Then `node-js` should build with the System Python.
