### ISSUE TITLE
Document how to display loaded modules

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#25249]
### Summary

We should do a better job of documenting how to display a list of all modules loaded by `spack load`. This may require documentation in multiple places, including references in other commands, tutorials, and reference docs. Basically anywhere that we mention that `spack load` exists.

### Rationale

This is probably the second most common question I see on Slack/GitHub after #22287.

### Description

The correct command is `spack find --loaded`, but this isn't obvious to a lot of people, myself included.

### Additional information

N/A

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ravil-mobile** [comment]
Hi,

I guess `spack find --loaded` is not so intuitive for many people because `spack --help` says that `find` lists and searches installed packages.
Maybe adding a new command (e.g., `spack show --loaded`) will make it clear. What do you think?

**Comment by adamjstewart** [comment]
We could also add the flag to `spack list` for people who are familiar with `module list`.

**Comment by ravil-mobile** [comment]
I guess the original `spack list` command was a bit ambiguous for users because it is actually searching for available packages. I would rename this command to `spack search` and use `spack list` to display currently loaded modules. Then `spack list` will be a complete analogue of `module list` and there will be no question because, as I suspect, the most of Spack users are HPC people.

**Comment by adamjstewart** [comment]
See #4159 and #2867 for some historical discussions on Spack command names. We've certainly thought about this before, but Spack isn't just for HPC and thinks like `apt`, `dnf`, `brew`, etc. use very different command names. It's hard to be consistent with other tools when all other tools use different names.

**Comment by mwkrentel** [comment]
I recall wanting to do this a few months back.  Since this is a
question about modules and spack already has a "user environment"
section on modules, I read everything there was about spack load,
unload and module.  Didn't find anything.  Never thought to try spack
find.

IMO, `spack find --loaded` is misplaced.  Spack find is a question
about what is/not installed.  This is more a question about the
current state of modules.  So the logical place to look is spack
load, unload, and module.

It's not unload, and module is about format syntax, so `spack load`
seems the logical place.  I suggest:

```
spack load --list
```

I would even say `spack load` with no arguments should do --list,
but whatever.
