### ISSUE TITLE
rocsolver 4.3.0 build fails: ld: failed to convert GOTPCREL relocatio

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#25416]
### Steps to reproduce the issue

`rocsolver@4.3.0` build fails using:
* `spack@develop` (b008d2b1fe03273156b37bab4f388bc738aaddb2 from `Thu Aug 12 22:37:56 2021 +0800`)
* Ubuntu 20.04, GCC 9.3.0
* Ubuntu 18.04, GCC 7.5.0
* RHEL 7, GCC 9.3.0
* RHEL 8, GCC 8.4.1

Concrete spec: [rocsolver.spec.yaml.txt](https://github.com/spack/spack/files/6983175/rocsolver.spec.yaml.txt)

Reproduced here using Docker container image `ecpe4s/ubuntu20.04-runner-x86_64:2021-07-01`
```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it
OK

$> spack install --cache-only --include-build-deps --only dependencies -f ./rocsolver.spec.yaml
OK

$> spack install --no-cache -f ./rocsolver.spec.yaml
...
==> Installing rocsolver-4.3.0-rt7xrwdpvapar7hbxebnwtrzfxcwp4lf
==> Warning: Suspicious requests to set or unset 'CXX' found
==> Warning: 	    	env.set('CXX', os.path.join(link_dir, compiler.link_paths['cxx'])) at /spack/lib/spack/spack/build_environment.py:252
==> Warning: 	--->	unknown context at unknown file:unknown line
==> Fetching https://mirror.spack.io/_source-cache/archive/63/63cc88dd285c0fe01ec2394321ec3b4e1e59bb98ce05b06e4b4d8fadcf1ff028.tar.gz
==> No patches needed for rocsolver
==> rocsolver: Executing phase: 'cmake'
==> rocsolver: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12'

3 errors found in build log:
     274    crtbegin.c:(.text.__do_init+0x34): relocation truncated to fit: R_X
            86_64_PC32 against `.eh_frame'
     275    /spack-software/__spack_path_placeholder__/__spack_path_placeholder
            __/__spack_path_placeholder__/__spack_path_placeholder__/__sp/linux
            -ubuntu20.04-x86_64/gcc-9.3.0/llvm-amdgpu-4.3.0-4xy4in54xmi4bzcorop
            yafmwlo3b7vcg/lib/clang/13.0.0/lib/linux/clang_rt.crtbegin-x86_64.o
            : in function `__do_fini':
     276    crtbegin.c:(.text.__do_fini+0xb): relocation truncated to fit: R_X8
            6_64_PC32 against `.bss.__finalized.1741'
     277    crtbegin.c:(.text.__do_fini+0x19): relocation truncated to fit: R_X
            86_64_PC32 against `.bss.__finalized.1741'
     278    crtbegin.c:(.text.__do_fini+0x21): additional relocation overflows 
            omitted from the output
     279    ld: failed to convert GOTPCREL relocation; relink with --no-relax
  >> 280    clang-13: error: linker command failed with exit code 1 (use -v to 
            see invocation)
  >> 281    make[2]: *** [library/src/CMakeFiles/rocsolver.dir/build.make:1766:
             library/src/librocsolver.so.0.1] Error 1
     282    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-rocso
            lver-4.3.0-rt7xrwdpvapar7hbxebnwtrzfxcwp4lf/spack-build-rt7xrwd'
  >> 283    make[1]: *** [CMakeFiles/Makefile2:134: library/src/CMakeFiles/rocs
            olver.dir/all] Error 2
     284    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-rocso
            lver-4.3.0-rt7xrwdpvapar7hbxebnwtrzfxcwp4lf/spack-build-rt7xrwd'
     285    make: *** [Makefile:159: all] Error 2
```

### Information on your system

* **Spack:** 0.13.3-9117-d2694d0119
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** original

### Additional information

Build log: [rocsolver-spack-build-02-build-out.txt](https://github.com/spack/spack/files/6983397/rocsolver-spack-build-02-build-out.txt)
CMake output: [rocsolver-spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/6983394/rocsolver-spack-build-01-cmake-out.txt)
Configure log: [rocsolver-spack-configure-args.txt](https://github.com/spack/spack/files/6983393/rocsolver-spack-configure-args.txt)

@arjun-raj-kuppala @haampie @srekolam

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
yesterday , i got an update that  rocFFT and rocSOLVER were having trouble with their debug builds in rocm-4.3.0. Appears Linking will begin to fail with relocation errors once the binary size would exceed 2GiB. I did not face this issue when i was testing it. But trying to confirm if the above signature matches this issue internally.

**Comment by cgmb** [comment]
That does indeed look like the binary size problem. There's a number of different ways to reduce the binary size to get it under the 2GiB limit.

The two workarounds that don't require changing anything in Spack are:
1. Use `rocsolver build_type=Release` rather than the default `RelWithDebInfo`
2. Use `rocsolver ~optimal` to omit kernels optimized for small matricies (generic fallbacks will be used instead)

If we change the spack recipe for rocsolver, there's a few more possibilities:

3. Spack could introduce architecture-specific variants. If you pass `-DAMDGPU_TARGETS=<target-id-list>` to CMake, you can choose exactly what GPUs you want to support. See the [LLVM AMDGPU User Guide](https://llvm.org/docs/AMDGPUUsage.html#processors) for a mapping of target-ids to GPU product names. By default, rocsolver on rocm-4.3.0 is built for seven architectures:
  - gfx803
  - gfx900
  - gfx906:xnack-
  - gfx908:xnack-
  - gfx1030
  - gfx90a:xnack-
  - gfx90a:xnack+

Most users probably don't need all of those, so they can significantly reduce the binary size and compile times by choosing a subset. (You could probably also use that same functionality to build rocSOLVER for gfx1010, gfx1011, or gfx1012. There's no architecture-specific code paths in rocSOLVER, so it should work on any architecture rocBLAS supports.)

4. Spack could add `-gsplit-dwarf` to the build flags for the Debug and RelWithDebInfo build_type variants, [as rocBLAS recently did](https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/a65e8e7f784413014cf9c52716743385dc7264d1), to move the debug symbols out of the `.so` file.

5. Spack could backport the change where [we de-inlined the OPTIMAL kernels](https://github.com/ROCmSoftwarePlatform/rocSOLVER/commit/22e94fd40ef390cfce410dc9bb8cefc8f7239c45), which was a major binary size optimization. That change should fix this problem without any packaging compromises, though, it is not currently scheduled to land in a release until _after_ rocm-4.4.0.

**Comment by eugeneswalker** [comment]
> 1. Spack could introduce architecture-specific variants. If you pass `-DAMDGPU_TARGETS=<target-id-list>` to CMake, you can choose exactly what GPUs you want to support. See the [LLVM AMDGPU User Guide](https://llvm.org/docs/AMDGPUUsage.html#processors) for a mapping of target-ids to GPU product names. By default, rocsolver on rocm-4.3.0 is built for seven architectures:
> 
> * gfx803
> * gfx900
> * gfx906:xnack-
> * gfx908:xnack-
> * gfx1030
> * gfx90a:xnack-
> * gfx90a:xnack+
> 
> Most users probably don't need all of those, so they can significantly reduce the binary size and compile times by choosing a subset. (You could probably also use that same functionality to build rocSOLVER for gfx1010, gfx1011, or gfx1012. There's no architecture-specific code paths in rocSOLVER, so it should work on any architecture rocBLAS supports.)

Wow! I would love to be able to do that. In my case `rocsolver` was being built as a dependency of `strumpack +rocm ~slate ~shared amdgpu_target=gfx906` -- clearly `amdgpu_target=gfx906` is not being used by rocsolver to select the architecture!

**Comment by srekolam** [comment]
the PR @25423 resolves this issue. hence closing it
