### ISSUE TITLE
Doxygen does not build with flex v2.6.2

### ISSUE THREAD

**Issue by jppelteret** [LLNL/spack#2554]
See https://github.com/westes/flex/issues/113 . Is it possible to blacklist this version of flex?

**Comment by davydden** [comment]
maybe add `preferred=True` to the version which is known to build? Or to specify this in doxygen requirements.

**Comment by adamjstewart** [comment]
Apparently Scotch also doesn't work with flex 2.6.2. @svenevs, https://github.com/westes/flex/issues/113 explains why you ran into the problem discussed in #2521. I think the appropriate solution here is to specify that doxygen `depends_on('flex@:2.6.1')`, as was done in #2523. `preferred=True` should be used lightly, as it can confuse a lot of new developers who are always expecting the latest version to install. It makes sense for Python, since most people are still running Python 2, and it kind of made sense during the HDF5/NetCDF incompatibility phase, but I'm not sure if it makes sense here. Maybe others can weigh in.

**Comment by adamjstewart** [comment]
Hmm, I guess if the developers themselves recommend against using `2.6.2` for compatibility reasons, then maybe we should use `preferred=True` on `2.6.1`. There isn't really a way to blacklist, aside from commenting out the version directive. Should we remove `2.6.2` altogether? I think I was the one who added it, and I only added it because I saw a new version was available.

**Comment by citibeth** [comment]
I vote for "blacklisting" 2.6.2 by commenting it out, and adding a short comment (with URL link) in the `package.py` explaining the problem.

**Comment by tgamblin** [comment]
We don't currently have an attribute for blacklisting a version, but `2.6.2` seems like a real disaster.  I like @citibeth's idea.  If people really want it they can uncomment it.

**Comment by davydden** [comment]
same here, we should just comment it out and add a short comment say that it breaks a lot of things.

**Comment by citibeth** [comment]
I'm adding the `ready` flag to indicate that discussion is about done, and this Issue is ready for a PR.
