### ISSUE TITLE
impossible python tk variant

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#2565]
I cannot seem to get any python to accept the `+tk` variant.
```
sven:~> spack spec python+tk
Input spec
--------------------------------
python+tk

Normalized
--------------------------------
python+tk
    ^bzip2
    ^ncurses
    ^openssl
        ^zlib
    ^readline
    ^sqlite
    ^tcl
    ^tk

Concretized
--------------------------------
==> Error: +tk does not satisfy ~tk
sven:~> spack spec python@3.5.2+tk
Input spec
--------------------------------
python@3.5.2+tk

Normalized
--------------------------------
python@3.5.2+tk
    ^bzip2
    ^ncurses
    ^openssl
        ^zlib
    ^readline
    ^sqlite
    ^tcl
    ^tk

Concretized
--------------------------------
==> Error: 3.5.2 does not satisfy 2.7.12
sven:~> spack spec python@2.7.12+tk
Input spec
--------------------------------
python@2.7.12+tk

Normalized
--------------------------------
python@2.7.12+tk
    ^bzip2
    ^ncurses
    ^openssl
        ^zlib
    ^readline
    ^sqlite
    ^tcl
    ^tk

Concretized
--------------------------------
==> Error: +tk does not satisfy ~tk
```
looking at the actual package, I think this was something that was only half edited out?

1. The variant [still exists](https://github.com/LLNL/spack/blob/eb645a8e46a9e0144149991d486593ca825b0b6c/var/spack/repos/builtin/packages/python/package.py#L57) and [two dependencies](https://github.com/LLNL/spack/blob/eb645a8e46a9e0144149991d486593ca825b0b6c/var/spack/repos/builtin/packages/python/package.py#L74) are incorporated if this variant is true.
2. A commented out [testing suite](https://github.com/LLNL/spack/blob/eb645a8e46a9e0144149991d486593ca825b0b6c/var/spack/repos/builtin/packages/python/package.py#L161) since an X window is needed for their tests.

I couldn't figure out much beyond that though, in #2065 it was stated that others aren't having any trouble with `tk` and python.

**Comment by hartzell** [comment]
Two observations:

1. It's funny to me that the `python` package depends on `tcl` directly.  It seems like it should depend on `tk` and pick up `tcl` via's `tk`'s dependency on it.  Commenting out the dependency on `tcl` doesn't change the outcome.

2. If I change the `tk` variant's default to `true`, then `~tk` and `+tk` all work (independent of change #1 above).  That's not really a solution, but perhaps it's a hint for someone more familiar with the internals....

**Comment by adamjstewart** [comment]
Duplicate of #2495 and many other issues. The problem is in the dependency chain:

`python+tk` -> `tk` -> `libx11` -> `libxcb` -> `python`

Spack sees the build dependency on `python` at the end, knows that it should default to `~tk`, and continues concretization. Then it gets back up to the top and sees that you requested `python+tk`, which obviously doesn't satisfy `python~tk`. But the way the concretizer currently works, is that you can't have the same package multiple times, or else it may result in an infinite loop. The question becomes, if `python` depends on `python`, which do you build first? In this case, the only way to build `python+tk` is to build it with `python~tk`. Since it is a build dependency and not a link dependency, it shouldn't really be a problem, but Spack currently doesn't allow that. #2548 is an attempt to solve this.

In the meantime, can you try adding the following to your `~/.spack/packages.yaml`? This allows `spack spec` to work for me:
```yaml
packages:
  python:
    variants: +tk
```

**Comment by hartzell** [comment]
@adamjstewart -- Is there an argument to `spack spec` that you used to generate the path above?

I was pretty sure this was "that same old problem", but couldn't dig deep enough to catch it.

**Comment by adamjstewart** [comment]
@hartzell Nope, I wish. The way I debug this particular problem is to look at the package for which `spack spec` fails. Then, run `spack spec` for all dependencies. I keep working my way down until I find the culprit. In this case, it was pretty easy because `python+tk` failed, but `python~tk` and `tk` didn't. Since `tk` depends on `python~tk` according to `spack spec`, it's the source of the conflict.

**Comment by svenevs** [comment]
Oh dear, that's quite subtle. Ok thank you, sorry for the duplicate :/
