### ISSUE TITLE
Ship latest `config.{guess,sub}` with Spack

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#25784]
### Summary

In autotools packages we have some logic to replace outdated `config.{guess,sub}` files with recent ones, so that `./configure` works on architectures unknown at the point where the configure script was generated.

This logic requires the package to depend on `automake`, so it pulls these files from there.

### Rationale

Unfortunately automake pulls in a lot of dependencies:

![Screenshot from 2021-09-03 17-09-02](https://user-images.githubusercontent.com/194764/132028539-504777ea-1489-44b6-8b7e-3684a87ca91f.png)

and the whole point of autotools is not to have automake as a dependency.

### Description

We can do 2 things:

- Put a recent `config.guess` and `config.sub` in `spack/share/spack` and pull the files from there.
- Create a Spack package for https://git.savannah.gnu.org/cgit/config.git/tree/, and make packages depend on this as a build dependency, and have our autotools build system use that instead. Unfortunately, it seems like they don't provide proper versioned tarballs for this (but I might be looking wrong?)

This reduces build times for autotools with ./configure scripts on new platforms.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
~@tgamblin mentioned that in some cases an exotic machine may provide a system `automake` which provides customized `config.{guess,sub}`, and the current approach allows one to mark `automake` as external, so that spack picks up these custom files (iiuc).~

~Shipping a recent config.guess/config.sub with Spack would not really support that case :(~

~Unless we make the paths to `config.guess` / `config.sub` configurable, but well... that's awkward too.~

Okay, I got this wrong as was pointed out by @joennlae: spack actually explicitly looks in system paths for config.sub and config.guess, which is very unexpected to me, since we try so hard to NOT rely on system paths at all:

https://github.com/spack/spack/blob/c309adb4b3a3d278fef89b32e6ad6fe677748ecb/lib/spack/spack/build_systems/autotools.py#L154

Instead, can't we ship our own versioned package with config.guess / config.sub files, simply redistributing the ones from upstream in a proper package instead of a git repo. Then *if* a user really needs a system version of config.guess / config.sub, they can always mark this package as external, and spack will find the config files from the external prefix = system.

**Comment by haampie** [comment]
Ok, new idea;

Can't we create a minimal package that we maintain ourselves containing config.sub/config.guess, so that the user can just mark it as external if they need the system version of config.sub/config.guess?

**Comment by bernhardkaindl** [comment]
I can tell you how Debian-based distros do it:

They have a package `autotools-dev` which provides 
```
/usr/share/misc/config.guess
/usr/share/misc/config.sub
```
Until some time ago, it also had the script to update these files in the source tree of a package.
This script has since been moved to the package `debhelper`: `/usr/bin/dh_update_autotools_config`
```perl
for my $basename (qw(config.guess config.sub)) {
	my $new_version = "/usr/share/misc/$basename";
	open(my $fd, '-|', 'find', '-mindepth', '1',
```
I don't know, but maybe you can make it so that for destination architecture aarch64 and ppc64le,
the calss AutotoolsPackage has a depends on the new `autotools-dev`-like package with the `config.{sub,guess}`

The automake tarball has the latest released `config.{sub,guess}` files, and to not pull the entire automake dependency tree into the build, we could add a BaseClass to `var/spack/repos/builtin/packages/automake/package.py`.

The BaseClass(derived from GNUMirrorPackage) would have the homepage, gnu_mirror_path and the versions, and "class Automake" derives from it, adds the depends_on lines and all the other properties and methods.

Then the class autotools-dev (or in this case likely automake-dev, or rather automake-files) package could derive from the BaseClass as well and just provide the `config.{sub,guess}` directly without adding any dependencies.

**Comment by haampie** [comment]
Yeah, it's highly similar then. So our `autotools-dev` would be `gnuconfig` https://github.com/spack/spack/blob/59a2594d153325e47cfac546212f6dd7e71956c3/var/spack/repos/builtin/packages/gnuconfig/package.py which just pulls sources from a mirror of the gnu config.git repo from tags I've added manually when they bump the timestamp.

The `dh_update_autotools_config` is written in python in `lib/spack/spack/build_systems/autotools.py`.

And I don't think it hurts to add `depends_on('gnuconfig', when='target=ppc64le:', type='build')` unconditionally (and the same for aarch64:).
