### ISSUE TITLE
Install fail on hdf5 linux-ubuntu14-x86_64/gcc-6.2.0

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2586]
>   FCLD     libhdf5_fortran.la
> /usr/bin/ld: cannot find -l-L/nfs/software/linux-ubuntu_trusty_amd64/apps/packages/gcc/gcc-6.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/6.2.0
> collect2: error: ld returned 1 exit status

[spack-build.env.txt](https://github.com/LLNL/spack/files/650822/spack-build.env.txt)

[spack-build.out.txt.gz](https://github.com/LLNL/spack/files/650824/spack-build.out.txt.gz)

**Comment by BarrySmith** [comment]
@tgamblin I know your dream is that spack installs all the dependencies to insure consistent compilers, versions  etc and this is why spack does not care much about allowing one to use "system" installs of some packages (in fact that functionality is pretty much broken now). Unfortunately, some packages such as hdf5, are so damn temperamental that their spack builds will often fail which leaves the user unable to build the packages they actually care about with spack that depend on hdf5, for example. If spack was "friendly" with "system" installed packages then when something like hdf5 won't build for me with spack I can just bypass it and use the system one, instead I have to mark this machine as off limits for spack which is super annoying.

**Comment by BarrySmith** [comment]
@tgamblin this is real blocker for xSDK now. Multiple people trying to install xSDK never get there because they get stopped by this.

**Comment by tgamblin** [comment]
@BarrySmith: This is fixed by #2772.  Can you try it out?

Is there some reason you need HDF5 `1.8.12` specifically, and not a later `1.8` release?  This bug happens on Ubuntu 14 no matter if I build inside Spack or outside Spack, and it seems to be something with how HDF5 `v1.8.14` and earlier use `libtool`.  `1.8.15` - `1.8.18` build fine, as does  `1.10-0-patch1`.

The extra `-l` comes from the `postdeps` variable in the `libtool` script generated by `configure`.  I think it's querying the implicit compiler libs the wrong way, but I didn't dig deep enough to figure out why exactly it's generated the way it is.

**Comment by tgamblin** [comment]
>  If spack was "friendly" with "system" installed packages then when something like hdf5 won't build for me with spack I can just bypass it and use the system one, instead I have to mark this machine as off limits for spack which is super annoying.

Have you seen @mamelara's #2550?  It's a step in that direction.  It's not completely automatic, but you can add an external without having to edit a file.
