### ISSUE TITLE
package SU2 version and configuration upgrade

### ISSUE THREAD

**Issue by kjrstory** [LLNL/spack#25899]
I want to become a maintainer of SU2, a CFD package.
Currently, SU2 is package in Spack, but the version is not being updated, and it does not support additional installation options such as MPI or BLAS.
First, I aim to replace the current version of 7.0.3 in Spack with the latest version of 7.2.0.
After that, I try to add the following options and dependent packages that fit those options.
<html>
<body>

Option | Default value | Description
-- | -- | --
-Denable-autodiff | false | enable AD (reverse) support (needed for discrete adjoint solver)
-Denable-directdiff | false | enable AD (forward) support
-Denable-pywrapper | false | enable Python wrapper support
-Dwith-mpi | auto | Set dependency mode for MPI (auto,enabled,disabled)
-Dwith-omp | false | enable MPI+Threads support (experimental)
-Denable-cgns | true | enable CGNS support
-Denable-tecio | true | enable TECIO support
-Denable-mkl | false | enable Intel MKL support
-Denable-openblas | false | enable OpenBLAS support
-Denable-pastix | false | enable PaStiX support
-Denable-mpp | false | enable Mutation++ support
-Denable-mixedprec | false | enable the use of single precision on linear solvers and preconditioners

</body>
</html>

If anyone can help, please help this package.

**Comment by alalazo** [comment]
Feel free to go ahead with PRs and submit the proposed changes to the package. To become a maintainer of the package, simply add yourself to the list of "maintainers" (it's an attribute at class level). I'm going to close this since we usually don't require to have proposed changes to a package be stated upfront in an issue. Looking forward to your PRs.
