### ISSUE TITLE
Installation issue: llvm-amdgpu

### ISSUE THREAD

**Issue by pghysels** [LLNL/spack#26861]
### Steps to reproduce the issue

```console
spack install llvm-amdgpu
```

### Information on your system

* **Spack:** 0.16.3-4955-fc7178da17
* **Python:** 3.9.7
* **Platform:** linux-ubuntu21.10-zen2
* **Concretizer:** clingo

uname -a
Linux cs-it-7098760 5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[spack-build-env.txt](https://github.com/spack/spack/files/7385415/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7385416/spack-build-out.txt)

### Additional information

@arjun-raj-kuppala  @haampie  @srekolam

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
I just checked with the internal team on this ticket - from log file it shows that the compilation failed because the header file linux/cyclades.h is missing.  It looks like a newer version of the linux kernel headers has removed the cyclades support.  Here the LLVM commit that fixes the issue: https://github.com/llvm/llvm-project/commit/68d5235cb58f988c71b403334cd9482d663841ab
you could try this fix or wait for ROCm 5.0.

**Comment by pghysels** [comment]
Applying the patch worked, thanks.
