### ISSUE TITLE
There should be two Python packages

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#275]
It is customary to have both `python2` and `python3` installed simultaneously. There are many software packages that work only with one of these two. Thus there should be two Python packages in Spack, e.g. `python2` and `python`, that could be installed simultaneously.

**Comment by lee218llnl** [comment]
This was briefly discussed in issue #215 and it was decided then to keep them in a single package. You should be able to maintain a python2 and python3 installation simultaneously under spack. I suggest submitting an issue if you see otherwise. Also, I think the topic is still open for debate if you have a strong reason to separate the versions.

**Comment by eschnett** [comment]
Yes, it is possible to have Python 2 and Python 3 installed at the same time, but only one can be active at any time.

LLVM requires Python 2 for building. Spack does not distinguish between build-time and run-tim dependencies, so every package that uses LLVM (i.e. many packages that use JIT translation) will see Python 2 active, and cannot use Python 3.

For example, if there is a package using Python 3, and I want to access this package from Julia via its "pycall" mechanism, then this will fail because Julia uses LLVM which requires Python 2. (There is a way around this -- install Python 2 manually outside of Spack, and have Julia build its on LLVM using this version of Python, but this circumvent doesn't really count.)

We could have Spack packages "python2" and "python3" that are not full-fledged Python packages, but only provide `python2` and `python3` executables that can be used to satisfy build-time dependencies.

**Comment by tgamblin** [comment]
Ok so the real problem is that we need build dependencies that are not link dependencies, right?  If Spack had build deps (which is planned along with now so many things :smile:) then you could compile LLVM with Python 2, but it wouldn't get pulled in as an indirect dependency of Julia.  Wouldn't that fix this?

I don't want to separate the python packages for a few different reasons.  First, I think other package managers actually do this poorly... MacPorts and EB resort to prefixing or suffixing all the python packages with versions, and I don't really want to go there.  If we had two python packages, we'd also need to duplicate all the python module packages (or implement a kludgy variant of some sort) to get them working with both pythons.  In Spack, you just get this for free because you can type:
```
  spack install numpy ^python@3.5
  spack install numpy ^python@2.7
  etc...
```
Compare MacPorts, which has packages for `py-numpy`, `py26-numpy`, `py27-numpy`, `py33-numpy`, `py34-numpy`, and `py35-numpy`.  Homebrew gives you `python` and `python3` and I think their philosophy is that you should use `pip` to manage your deps within each of those, which I find kind of clunky.

We do the same thing for `qt` -- some packages depend on `qt@4`, some on `qt@5`, and one on `qt@3`, and it works well so far.  Qt doesn't have this issue b/c it's not frequently used as a build dependency.

How about I increase the priority on build dependencies in Spack?  This is something we need a lot...

**Comment by eschnett** [comment]
At the moment I'm still stuck actually building Python (any Python) with gcc on OS X, and the Julia work-around above is working, so it's not urgent. Thanks!

**Comment by tgamblin** [comment]
Ok closing this for now.  Open if we need to discuss again, but I think this will be fixed by having proper build dependencies.

**Comment by dzhang-b** [comment]
Hi I have a meta-package uses both python3 and python2. `python3` and `python2` are really different packages. Is it possible to support multiple python version at the same time?

Or How can I escape the spack to use system python2/python3 by default?

By the way, `python3.5` and `python3.8` are also very different in that different level support of type annotation. It is total possible for package to use both syntax at the same time.

**Comment by tgamblin** [comment]
@dzhang-b: Not in a single meta-package, but you can easily make an environment that installs both: 

* https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html
* https://spack-tutorial.readthedocs.io/en/latest/tutorial_stacks.html

We will be making it possible over the next few months to have python2 as a *build* dependency in the same DAG that uses python 3 as a run or link dependency.

It's not possible to sanely combine multiple python 3 versions in the same run or link environment, as they use the same executable and library names.

**Comment by dzhang-b** [comment]
@tgamblin Cool! Thanks. Looking forward to see python2 support in when building the package that requires python2 installation.

But I still think python and python3 should be named differently and allowed to be list as dependencies at the same time. Debian/Ubuntu manually used `python3` binary name instead of `python` even when python2 is not presented in the system. 

Who knows if in future python4 comes out and become incompatible again, right? 
The problem with python is that it also has a package manager (pip) that depends on the python version and the set of packages that are used in the same repo have both versions.
