### ISSUE TITLE
Tarball downloads for `prce2` will eventually fail

### ISSUE THREAD

**Issue by vchuravy** [LLNL/spack#28538]
https://github.com/spack/spack/blob/9ac207c901c46d005a8cce1460fa110192af6cb5/var/spack/repos/builtin/packages/pcre2/package.py#L15

The FTP server https://ftp.pcre.org/pub/pcre/ went permanently offline, these releases have moved to Github (https://github.com/PhilipHazel/pcre2/releases), but no tarballs to releases prior to 10.37 are on Github. @PhilipHazel could you potentially upload prior releases to tags on Github?

> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

**Comment by PhilipHazel** [comment]
In reply to your question, I suppose it might be possible but: (a) The only
GitHub mechanism I can see is "create release from tag", which I'm not sure
I want to do for a non-current release. (b) How many previous releases
would people actually use? (c) The previous release tarballs are available
elsewhere on the net, though I do not want to encourage their use,
especially not the obsolete PCRE1 releases (8.xx).

**Comment by giordano** [comment]
@PhilipHazel Uploading the tarballs to GitHub releases would be ideal, at very least for version 10.36, ideally for all versions listed in https://github.com/spack/spack/blob/9ac207c901c46d005a8cce1460fa110192af6cb5/var/spack/repos/builtin/packages/pcre2/package.py#L17-L20 (10.20, 10.31, 10.35, 10.36).

In particular, using github releases like you did for 10.37 onward would make it possible to use the same URL scheme for all releases, instead of having to special-case different releases.  Also, re-uploading to the release pages the original release tarballs would be preferable, so that the current checksum hashes can be kept.  You can read about how to manage GitHub releases at https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository.

> The previous release tarballs are available
> elsewhere on the net, though I do not want to encourage their use

Exactly, so if you could please upload them to GitHub releases that'd avoid downstream packagers (here in spack and everywhere else) to rely on third-party unmaintained websites.

**Comment by PhilipHazel** [comment]
I have uploaded 10.36 and 10.35. Your list then had 10.31 and 10.20 but it
doesn't seem right to offer 10.31 without 10.32, 10.33, and 10.34, and all
the others in between 10.31 and 10.20. Do you really need these old
versions? 10.31 is 4 years old and 10.20 is ancient in software terms
(2015).

**Comment by haampie** [comment]
As a data point: CentOS 7 provides 10.23 by default and will continue to do so until their EOL date 2024-06-30, so there are still users of ancient software versions, and it would be good if builds remained reproducible, and one aspect of that is availability of sources

**Comment by PhilipHazel** [comment]
OK, I will try to do a few each day back to at least 10.20.

Regards,
Philip

**Comment by PhilipHazel** [comment]
I have now uploaded all existing PCRE2 releases, right back to 10.00. I
hope I've done it right...

Philip

**Comment by tgamblin** [comment]
Thanks @PhilipHazel!

All: note that we do also upload artifacts in Spack to our source mirror, hosted on cloud front -- were these showing up there?

It's still nice to have the original URLs work, though.

**Comment by tgamblin** [comment]
I think we can close this now -- feel free to continue discussion.

**Comment by vchuravy** [comment]
> All: note that we do also upload artifacts in Spack to our source mirror, hosted on cloud front -- were these showing up there?

Yeah that's why I titled it "eventually fail", since I didn't know your eviction policy.

**Comment by tgamblin** [comment]
Currently it’s “never” so we’d have to decide to evict this.  For reproducibility I’m not usr Edgar we would do that. Our costs aren’t currently dominated by storage at all — if anything they may become dominated by bandwidth, so at least for now I think we are safe in both scenarios.

Having an official policy and checking that the source urls still work semi-routinely are things we should probably do, but we haven’t gotten quite that far yet.
