### ISSUE TITLE
URL rebuild in fetch mangling package

### ISSUE THREAD

**Issue by trws** [LLNL/spack#286]
This url base is getting mangled, presumably because of the date in the middle of the package filename.  Adding an explicit URL to the version line fixes it.

```python
class Libedit(Package):
    """An autotools compatible port of the NetBSD editline library"""
    homepage = "http://thrysoee.dk/editline/"
    url      = "http://thrysoee.dk/editline/libedit-20150325-3.1.tar.gz"

    version('3.1', '43cdb5df3061d78b5e9d59109871b4f6')
```

**Comment by mathstuf** [comment]
Not sure how best to fix this; some packages do use a date as their version numbers.

**Comment by trws** [comment]
Especially when they're right together, I'm not sure there's a good way to do it reliably without user input.  Could we perhaps have a package property for "version pattern" or similar so the user can split out particularly hairy ones for spack, rather than having to individually override?

**Comment by tgamblin** [comment]
You can implement a `url_for_version` method already -- would that work?  @adamjstewart has implemented these quite assiduously for his packages.

**Comment by adamjstewart** [comment]
I'm not sure if this one can be done with `url_for_version`. There's no way to predict the date string, right? You'll probably just have to include the url in `version()`

**Comment by adamjstewart** [comment]
I think this issue can be closed. For packages that use a date in their URL, it is impossible for Spack to predict the correct URL, unless we include the date in the version number. But if we include the date, Spack can no longer tell which version is newest. `self.url` is meant to be a url at which all versions can be downloaded by swapping out the version number. Instead of specifying `self.url`, the correct way to handle packages like this is to always specify `version('1.2.3', 'superlonghash', url='http://www.ugly.date.url.tar.gz')`.
