### ISSUE TITLE
Installation issue: All of Intel's packages

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#28891]
### Steps to reproduce the issue

Install a bunch of Intel's packages back-to-back.  E.G.: intel-mpi intel-mkl intel-oneapi-compilers

Some will succeed, some will fail, some will fail silently and spack will think they succeeded.

This seems to be due to the intel installer detecting "other" installations of intel packages (within or outside of spack) and doing the wrong thing (failing the install or moving the install location to the prefix of another intel package).

Can we do something about this?  At a minimum, I'd prefer for spack to detect when the installation failed to put any files into the prefix.

### Information on your system

Redhat-ish 7 x86_64

### Additional information

```
==> intel-ipp: Executing phase: 'configure'
==> intel-ipp: Executing phase: 'install'
==> [2022-02-10-18:17:45.460910] './install.sh' '--silent' 'silent.cfg'
Another instance of the installation program has been detected. Please quit the 
other instance and try again.
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
Can you try with intel-oneapi-mpi instead of intel-mpi and intel-oneapi-mkl instead of intel-mkl?  New releases all come in the intel-oneapi-* packages. The intel-oneap packages check if the nothing was installed in the prefix and have better support for the case when spack root installs interfere with external root installs.

If you continue to get the 'another instance of the ..' problem, you may have to reboot the system to clean up.

**Comment by G-Ragghianti** [comment]
Yes, the oneapi installers do seem to work better, but we need the older library versions as well.  Rebooting the system whenever a user has this issue isn't really viable on large HPC systems.  I am hoping that spack may be able to detect this issue and at least notify the user appropriately.  As is, we get "ghost" installs that don't contain anything under the prefix.

Do you know how the intel installer is determining that there is another instance running?

**Comment by rscohn2** [comment]
I asked the installer team for help on recovering from the 'Another instance of the installation program has been detected.' without reboot. Root installs put things in /var/intel/installercache and non root uses ~/.intel. There will also be files in /tmp/intel*. Something similar happened to me a few days ago and I had to reboot.

I will see if I can add a check for empty prefix. I did that for the oneapi packages because the installer was not reliably returning error codes.

Are you installing with spack as root?

**Comment by G-Ragghianti** [comment]
This is for installs as a non-root user. 

In the past, I've tried to avoid this problem by removing the ~/.intel and /tmp/intel directories after every install, but it currently is still failing sometimes.

**Comment by G-Ragghianti** [comment]
My preference would be for spack itself to detect whether a package has failed to install anything.  I don't think it is realistic to expect every package to police itself in that way.

**Comment by npf** [comment]
I agree. I faced the issue today when trying to install py-torch that depends on intel-mkl in the v0.19 branch at least.

**Comment by G-Ragghianti** [comment]
@tgamblin Is this something that would be OK to add to spack (detecting if a package failed to install anything)?

**Comment by G-Ragghianti** [comment]
https://github.com/spack/spack/pull/30773

**Comment by alalazo** [comment]
#30773 has been merged today :slightly_smiling_face:

**Comment by G-Ragghianti** [comment]
Thanks for update!
