### ISSUE TITLE
bmi versions

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#29094]
@carns please have a version for bmi its tied to `main` branch for time being and this causes issues when trying to put specs in buildcache since it cant find version. See https://github.com/spack/spack/blob/9e2d78cffc1beaec2c6e4c3a379c17f25a35b31f/var/spack/repos/builtin/packages/bmi/package.py#L17. 

spack will give a warning because its not a version. 

```
==> Warning: Missing a source id for bmi@main
```

Please consider having a release i dont see any in https://github.com/radix-io/bmi/releases.

**Comment by carns** [comment]
Sure thing @shahzebsiddiqui .  I'm on vacation through the end of this week but I'll get on it shortly after that.  It's not difficult (the code hasn't changed in years) but I want to make sure to get the naming etc. right.

**Comment by shahzebsiddiqui** [comment]
Thanks @carns. Yeah this also causes an issue for us when we ttrying to update buildcache because there is no version in addition to fact that building of `main` branch is not good practice as spack builds will be affected if main branch is changed over time.

**Comment by scheibelp** [comment]
Thanks @carns for #29274 but @shahzebsiddiqui I think Spack should be able to tolerate packages without versions: in that case, we should just not make a binary cache of the package.

If the issue is that a missing version for this package causes our binary cache generation to fail, then I think this bug should stay open. If we already handle such packages, and the issue was just created because folks thought we should be generating a binary for `bmi` specifically, then I misunderstood and this should be closed again.

**Comment by shahzebsiddiqui** [comment]
The intent of this issue was to pin a version, we generally don't like to install packages based on a branch as part of facility deployment because `spack install bmi` can change as master branch changes over time which is not good. Yes i know that spack doesn't write specs to buildcache that are not specified as version. I am not sure if there is an open issue for that and if it makes sense to keep it open then we should have one open. Let me know if this worth mentioning.

This causes an issue where we do spack deployments where one pipeline will push all specs to buildcache and then our production pipeline will install from buildcache and some specs will be installed from source.
