### ISSUE TITLE
Wrong use of 'command -v' in setup-env.csh

### ISSUE THREAD

**Issue by a-denis** [LLNL/spack#29510]
### Steps to reproduce

The code to detect SPACK_PYTHON in setup-env.csh uses "command -v", which is a bash command. As a result, we get spurious error messages in terminals at shell initialization, and SPACK_PYTHON is not set:
```
% set printexitvalue
% source share/spack/setup-env.csh 
Exit 1
Exit 1
Exit 1
Exit 1
% echo $SPACK_PYTHON
```

Indeed, "command -v" is a Bourne shell / Posix thing and is not available in (t)csh. In (t)csh, it is ok to use "which", which is a builtin.

```
% command -v
command: Command not found.
Exit 1
```

When replacing both occurrences of "command -v" with "which", the script works fine.

### Information on your system

```
% echo $SHELL
/usr/bin/tcsh
% spack debug report
* **Spack:** 0.17.1-829-0b2507053e
* **Python:** 3.9.10
* **Platform:** linux-debianunstable-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@tgamblin I'm surprised our tests didn't catch this, do we only test sh/fish?

**Comment by tgamblin** [comment]
@adamjstewart it looks like on most systems where `bash` is actually installed, `command -v` will work in `csh` or `tcsh`, because `/usr/bin/command` is a binary. We don't have great ways to test `csh` on systems where that isn't the case, and there isn't much tooling to lint `csh` or `tcsh`. I did find [stank](https://github.com/mcandre/stank/releases/tag/v0.0.12), which is used by FreeBSD, where I guess `tcsh` is the default shell.  I suppose we could try using that.

**Comment by a-denis** [comment]
On Debian Linux, even with bash installed, there is no `/usr/bin/command`.
