### ISSUE TITLE
installation of dealii with specified trilinos version fails

### ISSUE THREAD

**Issue by futuretristan** [LLNL/spack#3001]
I would like to install the dealii package version 8.3.0 linked with the trilinos package version 12.4.2. I'm on a virtual machine (VirtualBox) running LinuxMint 18. Spack version is 0.10.0. Standard compiler is GCC 5.4.0.

When I type `spack spec dealii@8.3.0^trilinos@12.4.2` then spack complains that "Error: dealii does not depend on trilinos". I then compile Trilinos first running `spack install trilinos@12.4.2` which fails as well. In the compiler log I find 
"[...] Trilinos-trilinos-release-12-4-2/packages/amesos2/src/Amesos2_Superludist.cpp:92:27: error: duplicate explicit instantiation of ‘class Amesos2::Superludist<Tpetra::CrsMatrix<double, int, int>, Tpetra::MultiVector<double, int, int> >’ [-fpermissive] [...]". But I guess that is a Trilinos problem, not a Spack one.

I manage to compile Trilinos with the command `spack install trilinos@12.4.2~superlu-dist`. I then find the associated hash key with `spack find --long trilinos@12.4.2`, in my case it is "sttp4e7". If I then try to execute `spack spec dealii@8.3.0^/sttp4e7`, then Spack sais "Error: dealii does not depend on hypre, hwloc, glm, hdf5, trilinos, netlib-scalapack, libpciaccess, openmpi, netcdf, mumps, matio, boost, or parmetis".

**Comment by davydden** [comment]
@futuretristan  `0.10` has a bug with fetching of `oce`, so i would recommend using `develop` branch. As for the original question you need to help spack a bit in here by doing
```
spack spec dealii@8.3.0+mpi+trilinos ^trilinos@12.4.2
```
that's because
```
depends_on("trilinos",         when='+trilinos+mpi')
```
and in this context conretization does not take default values for variants, which is a known issue.

Please re-open if the issue persist.

General advise: in Spack one should not try to install packages separately (first trilinos, then deal.II with trilinos, etc). Everything starts from the root node in a graph of packages, in your case -- deal.II.

For build error of trilinos, please open a separate issue. Trilinos was limited to `superlu-dist@4.3` prior to `12.6.2`, which is reflected in
```
    depends_on('superlu-dist@:4.3', when='@:12.6.1+superlu-dist')
    depends_on('superlu-dist', when='@12.6.2:+superlu-dist')
```
so i can't see immediately why do you have those errors.

**Comment by futuretristan** [comment]
Again,

`spack spec dealii@8.3.0+mpi+trilinos ^trilinos@12.4.2`

yields

`==> Error: dealii does not depend on trilinos`

**Comment by davydden** [comment]
No, it's not again. Check out the 'depends_on' statement in dealii package, IIRC there is now an extra option for 64bit index sets, which u need to specify in the spec so that concretization algorithm sees the dependency.

**Comment by futuretristan** [comment]
Okay,
`spack spec dealii@8.3.0+mpi+trilinos~int64^trilinos@12.4.2`
works. I didn't know that you even have to explicitly disable options when not needed. For users not that familiar with the spack python scripts this is hard to find out.

**Comment by davydden** [comment]
This is a know issue with concretization algorithm when you want add command-line constrains. Main developers are working on the fix. 

You can avoid all those troubles by adding custom configuration in ~/.spack/packages.yaml See docs for more details.
