### ISSUE TITLE
Shell completions

### ISSUE THREAD

**Issue by aprokop** [LLNL/spack#3003]
Does Spack have any shell completion? I'm mostly interested in bash.
If there is not, is anybody interested in or thinking about developing one?

**Comment by davydden** [comment]
did you see https://github.com/LLNL/spack/pull/2356 , looks relevant.

**Comment by adamjstewart** [comment]
That's for Zsh, here's one for Bash (https://github.com/adamjstewart/dotfiles/blob/master/.spack-completion.bash). I tried merging it into Spack once upon a time (see #459) but it got rejected.

**Comment by aprokop** [comment]
Thanks @adamjstewart. So, to summarize, #459 was not merged in favor of `argcomplete`, but the work on that was not done. The two pertinent questions then are:

1. Is there still enough interest in adding the feature?
2. Is `argcomplete` still the best way to go?

Regarding 2., it seems that it has limited support for zsh, which may pose an issue considering the audience of spack.

**Comment by adamjstewart** [comment]
> Is there still enough interest in adding the feature?

A big yes from me!

> Is argcomplete still the best way to go?

No idea. I'm fine with editing my bash script by hand though. So if we want to reverse policy and merge #459/#2356 then that would be fine by me too. I was going to look into `argcomplete` more, but I'm probably too busy for the foreseeable future.

**Comment by tgamblin** [comment]
I'd be ok with adding manually written completions if others are willing to maintain them. I think they'd be helpful to people (including me).  We do still rework commands rather frequently though.  Thoughts?

**Comment by adamjstewart** [comment]
If it's good enough for git completions, it's good enough for Spack 😝 

Let me rework mine. I'll update it to the current develop commands/option flags. Another thing I was considering doing is saving tab completion responses. For example, every time I run `spack install [TAB]`, it runs `spack list`. I would rather save the response the first time. It means that if you add a new package, tab completion won't pick it up. But it makes it way faster, so I think it's worth waiting until you open a new terminal to detect it.

**Comment by aprokop** [comment]
@adamjstewart It seems like you haven't updated your completion branch since last May. Does it mean it's been working for you, or have you simply not used it?

Overall, I'd be glad to help with completions. I see two potential usability pitfalls:
1. I think it has to be all or nothing approach. If the support for completions is only partial, I think it would be quite frustrating for a user. I don't think the maintenance cost is high, I think it is more about responding quickly to changes.
2. The speed is very important. Completions taking longer than a second become frustrating. We could update the proposed cache by @adamjstewart and update it at the end of the commands that may change it. For instance, updating the response after spack install and such.

**Comment by tgamblin** [comment]
How long does list take for you now and what's the most time acceptable for completions?  We can probably speed the commands up quite a bit.

**Comment by aprokop** [comment]
For me `spack list` takes about 0.5s. But I have SSD. I'd like to hear from @adamjstewart.

**Comment by adamjstewart** [comment]
> It seems like you haven't updated your completion branch since last May. Does it mean it's been working for you, or have you simply not used it?

Both really. I only use tab-completion for a few commands; especially the ones that take a package name (as if I'm going to type out `py-backports-shutil-get-terminal-size` 😆). It has been working marvelously for those commands. But some of the commands have been neglected, and some I don't even know what they do lol.

> it may also be possible that in some situations the spack will be NFS-mounted which would be quite slow.

That's my exact situation. Honestly, the speed really isn't that bad, especially on my laptop. I'll submit a PR as is (once it is up-to-date) and we can worry about speed later. But I think it is reasonable to only update the cache every time you source the file. Maybe I can `ls var/spack/repos/builtin/packages` instead of `spack list`.

As far as making sure it gets updated, that's really up to @tgamblin and I (and anyone else) to call people out when they add options/change commands to make sure they update the tab-completion script. As long as someone remembers, it will be fine.

One thing I would like to avoid is having too many scripts. If I add a new command, I don't want to edit separate bash, zsh, csh, and tcsh scripts. If we could merge the bash and zsh scripts, that would help a lot. I'm assuming we'll also have ones for csh/tcsh someday. Unfortunately, tab-completion is one of those highly shell-specific things...

Of course, there's no reason we can't decide to switch to argcomplete later. But since no one has the time/energy to work on that, why not use what @Falkor and I already wrote?

**Comment by pramodk** [comment]
> Is there still enough interest in adding the feature?
👍

**Comment by davydden** [comment]
> Is there still enough interest in adding the feature?

:+1:

**Comment by aprokop** [comment]
Thanks to everyone involved! Especially @adamjstewart !
