### ISSUE TITLE
Can't build bootstrap in Python 3.10 Conda environment (missing libpython3.10.a)

### ISSUE THREAD

**Issue by bryank-cs** [LLNL/spack#30513]
### Steps to reproduce

This is only noticeable if the bootstrap can't find something in the build-cache for the current environment. You should be able to reproduce it with the following commands, but note there is some package that if installed with apt (tried in an effort to save time not having spack build it) that will cause it to find a pre-built binary, but I didn't track down which (i.e., of the list of packages that spack will install trying to get to clingo-bootstrap-spack; it could be any of `cmake bison bzip2 mc perl` (or their dependents))

```
docker run --rm -it ubuntu /bin/bash
apt update && apt install -y curl git gcc g++ make
curl -O https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh
bash ./Miniconda3-py39_4.11.0-Linux-x86_64.sh -b
root/miniconda3/bin/conda init
source /root/.bashrc
conda create -n python310 -y python=3.10
conda activate python310
git clone --depth 1 https://github.com/spack/spack
spack/bin/spack -d spec zlib
```

This should yield the indicated error message.

@adamjstewart  and @alalazo asked to be notified about this bug.

### Error message

```
Error: RuntimeError: Unable to locate libpython3.10.a libraries in /root/miniconda3/envs/python310/lib

/spack/var/spack/repos/builtin/packages/python/package.py:1060, in libs:
       1057                return LibraryList(os.path.join(win_bin_dir, ldlibrary))
       1058            else:
       1059                msg = 'Unable to locate {0} libraries in {1}'
  >>   1060                raise RuntimeError(msg.format(ldlibrary, libdir))
       1061        else:
       1062            library = self.config_vars['LIBRARY']
       1063
```

### Information on your system

* **Spack:** 0.18.0.dev0 (e6d1c2d9f315d929e3a3bf2474b1d9fa7ff68ad5)
* **Python:** 3.10.4
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Thanks for the docker steps to reproduce! This is really helpful.

From what I can tell, the issue is that our external package detection doesn't detect the `+shared` variant. In the case of miniconda, only shared libraries are installed, not static libraries. But our `libs` property relies on whether or not `+shared` is in the spec to decide which libraries to look for.

@alalazo can you confirm that this is how bootstrapping works? If that's the case, I'll write up a PR to detect `+shared` and that should hopefully solve this.

**Comment by adamjstewart** [comment]
Also pinging other Python maintainers: @scheibelp @skosukhin @varioustoxins

**Comment by alalazo** [comment]
Can you retry using:
```
apt update && apt install -y curl git gcc g++ make file
```
? With `file` you can bootstrap from our binaries (we use that application when relocating binaries).

**Comment by alalazo** [comment]
I know it's probably not very well known, but this command:
```console
root@96d2ee604dd2:/# spack/bin/spack bootstrap status
Spack v0.18.0.dev0 - python@3.10 

[FAIL] Core Functionalities
  [-] MISSING "unzip": required to compress/decompress code archives

[FAIL] Binary packages
  [-] MISSING "file": required to analyze files for buildcaches
  [B] MISSING "gpg2": required to sign/verify buildcaches


Spack will take care of bootstrapping any missing dependency marked as [B]. Dependencies marked as [-] are instead required to be found on the system.
```
might be useful when diagnosing bootstrapping errors.

**Comment by adamjstewart** [comment]
@alalazo installing `file` does indeed solve the issue. So we now have a quick workaround for @bryank-cs. 

I would still like to fix things so that they don't crash when `file` is missing. If we detect `+shared` in the `python` package, will that fix things? Does bootstrapping use the same external package detection mechanisms to build clingo, or is there separate logic somewhere else that lacks variant support?

**Comment by adamjstewart** [comment]
Might also be helpful to add warning messages saying "file" or "cmake" aren't found so we need to build things from source instead. Just getting to the point where the above steps would result in an error message took 30+ minutes of building.
