### ISSUE TITLE
gmsh python bindings are not installed

### ISSUE THREAD

**Issue by bosmacs** [LLNL/spack#30757]
Installing gmsh with spack does not put the python bindings (gmsh.py) in a location where they are importable by the environment's python by default.

All that needs to be done is to create an additional symlink to gmsh.py (which is installed in the environment's `lib/` directory) in `lib/pythonX.Y/` (or `lib/pythonX.Y/site-packages`). 

Is there a function in spack packages for this kind of thing already?

Would it be better to add this to the base `gmsh` package, or add a new `py-gmsh` package?

**Comment by adamjstewart** [comment]
Lot of great questions here.

> Installing gmsh with spack does not put the python bindings (gmsh.py) in a location where they are importable by the environment's python by default.

There are actually a couple of options here in addition to the one you proposed. Another option would be to add the location where `gmsh.py` is to `PYTHONPATH`. This would look like:
```python
def setup_run_environment(self, env):
    env.prepend_path('PYTHONPATH', self.prefix.lib)
```
I think this might actually be the better option since it works better for external packages where we have no control over the installation prefix.

> All that needs to be done is to create an additional symlink to gmsh.py (which is installed in the environment's `lib/` directory) in `lib/pythonX.Y/` (or `lib/pythonX.Y/site-packages`).
>
> Is there a function in spack packages for this kind of thing already?

If you instead want to go down this route, I think the latter site-packages directory is better. You can get this using the `python_purelib` variable. I haven't tested this, but it would look something like:
```python
@run_after('install')
def symlink_python(self):
    mkdirp(python_purelib)
    symlink(join_path(self.prefix.lib, 'gmsh.py'), join_path(python_purelib, 'gmsh.py'))
```

> Would it be better to add this to the base `gmsh` package, or add a new `py-gmsh` package?

This is actually the hardest question you've asked. My thinking is along the lines of the last paragraph in https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#choosing-a-package-name. 

I see that `gmsh` is available on PyPI. If it's possible to install `gmsh` on its own, then install the `py-gmsh` package that only builds the Python bindings and links to `gmsh`, I think it's okay to have separate packages, and we've done this in other cases. But if it's possible to build the Python bindings in `gmsh` directly, and it's not possible to build `py-gmsh` without rebuilding `gmsh`, then I think it's best to keep things as is.

I'll leave the final decision to you since I don't use `gmsh` and it currently has no official build recipe maintainer.

**Comment by cessenat** [comment]
Solved by PR https://github.com/spack/spack/pull/30923
