### ISSUE TITLE
`Spack mirror --all` now takes so long to run it's infeasible to do so.

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#31985]
### Steps to reproduce

1. Run `spack mirror --all`
2. Wait at least 3 days.
3. ...
4. Profit

### Error message

@alalazo Patch to fix the issues with `spack mirror --all` have added a concretization step for each package to be mirrored. Instead of taking less than a second to check if a package@version has already been mirrored, for the average package it takes about 20 seconds. 

I started a run of `spack mirror --all` yesterday to see how long it took. It used to take about 10 minutes to run, given that our mirror already had just about everything and only a few package changes needed syncing. It's now been running for over 20 hours, and is only at the letter F in the alphabet.

### Information on your system

# spack debug report
* **Spack:** 0.19.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@Paul-Ferrell I hoped I could get by with a small fix, but I think I'll look into refactoring the way we create mirrors and differentiate when `--all` is given from cases where we mirror single specs.

**Comment by Paul-Ferrell** [comment]
Do we really have to concretize all these specs? The computational load is huge.  Even with a 10x speedup, we're looking at hours and hours to do this.

**Comment by alalazo** [comment]
> Do we really have to concretize all these specs? The computational load is huge. Even with a 10x speedup, we're looking at hours and hours to do this.

With single specs I think so, even though I am currently trying to read the mirror internals to get a better sense of when that is needed. The rationale is that there might be patches or resources that need to be mirrored too, and since they can be conditional on variants etc. we need concrete specs to be sure we need them. Same applies when we create a mirror for a spec with dependencies.

When we use `--all` we don't need to concretize in principle, so I'll try to refactor to something that takes that into account. From a user perspective that was the case it worked before (sorry for the regression!), except we were abusing the internals and treating abstract specs like they were concrete (e.g. we were staging them into a hashed directory). I'll try to achieve the same without having hacks in the code. I'll get back here when a PR is ready.

**Comment by Paul-Ferrell** [comment]
The big question for me is: Are there any patches, sources, etc that would need to be pulled down that they aren't available from the class (or an instance of the class)?

**Comment by Paul-Ferrell** [comment]
Accidentally closed it...
