### ISSUE TITLE
libelf virtual package?

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#3222]
@mplegendre @tgamblin Dyninst 9.3.0 requires libelf.so.1, otherwise it may seg fault on attach (https://github.com/dyninst/dyninst/issues/336). It looks like the libelf package does not supply this, but the elfutils package does. Would it make sense to make libelf a virtual package and have the libelf and elfutils packages provide it? The virtual package could be named something different too if the conflict causes issues.

This also leads to another issue, which is how to deal with the fact that elfutils packages up utilities like ar and ld.When a package depends_on elfutils, it brings those versions of the utilities into the PATH, which can cause issues.

**Comment by tgamblin** [comment]
@lee218llnl: I would make `elf` a virtual package to avoid a name conflict with `libelf`, and then update `etc/spack/defaults/packages.yaml` to set a sensible default to prefer.  I dunno if `libelf` or `elfutils` should be preferred, or if they are actually as interchangeable as we think.  @mplegendre can comment on that.

If you look at [`set_build_environment_variables`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L234) in `build_environment.py`, you can see how we set things up in the build environment, and which env vars get set for which types of dependencies.  We should probably document this better, but there are two things relevant to your question.

1. `PATH`s only gets updated for `bin` directories of `build` dependencies.
2. We set `CMAKE_PREFIX_PATH`, `PKG_CONFIG_PATH`, and add `-L` and `-I` arguments to the compiler wrappers for `link` dependencies.  There will soon be an `include` deptype, as well, so that we can better handle header-only libs, but that's not relevant here.

The default dependency type is `('build', 'link')`, mostly because that used to be the only dependency type in Spack, and it frequently doesn't hurt to add a build dep.  So if you do this:

```python
    depends_on('elf')
```

You'll pull in the `elfutils` `PATH` when it's the selected `elf` implementation.  But if you do this:

```python
    depends_on('elf', type='link')
```

You shouldn't get the `PATH`, and you won't get the issues with the `elfutils` command line tools.

**Comment by lee218llnl** [comment]
@tgamblin I'm working on getting an elf virtual package created. I am having one problem when trying to install libdwarf based on elfutils, though. The problem is that elfutils includes a dwarf.h and the libdwarf build is picking this up instead of its own (from the cwd). Is there any way to get Spack to append its compiler args instead of prepend them or was there an explicit reason for always prepending?

**Comment by alalazo** [comment]
> Is there any way to get Spack to append its compiler args instead of prepend them or was there an explicit reason for always prepending?

@lee218llnl My guess for the ordering is that *if the arguments were flags with the current order they can be overridden*. But I see how this may cause problems with include directories in a few corner cases.

**Comment by lee218llnl** [comment]
I might pursue an alternative option since this may be a corner case. In particular, I may have the libdwarf package temporarily move the elfutils dwarf.h when it builds and then put it back after building.

**Comment by tgamblin** [comment]
I think there are actually other issues with the way we currently prepend includes.  An example would be #3185 -- @davydden had issues because there was a conflicting header in a dependency of `gnuplot`.

The arguments in the original compiler wrappers were inserted, I believe, after any local project includes, but I believe that was causing some problems for @eschnett, who redid the `cc` wrapper with simpler parsing and changed the args to prepend.

@eschnett: I am blanking on whether there was a particular issue that this solved.  Do you remember?  Could we go back to putting injected includes *after* root project includes?

**Comment by lee218llnl** [comment]
Addressed by https://github.com/LLNL/spack/pull/3317/.
