### ISSUE TITLE
spack external find curl emits an empty file

### ISSUE THREAD

**Issue by tasmith4** [LLNL/spack#33318]
### Steps to reproduce

```console
$ spack external find curl
```

### Error message

This command works as expected, but afterwards, an empty file named `str` appears in the directory where I ran the command.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.18.1
* **Python:** 3.6.8
* **Platform:** linux-rhel7-zen3
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by psakievich** [comment]
Pinging @tgamblin @haampie and @adamjstewart based on the git history since there is no maintainer for this package.  
I've noticed this too and it is really annoying.  Since curl is a dependency of so many things I think we should fix this soon and not let it linger. EDIT: Simple fix. see associated PR
