### ISSUE TITLE
GitHub `/archive/` tarballs hash changes

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#35250]
### Steps to reproduce

Spack has a lot of `/github.com/…/archive/…` URLs. These are *not* stable and cannot be trusted to never change because they are made on-the-fly by `git archive`. Spack should prefer using actual source tarballs uploaded as artifacts instead (and prod upstreams to provide such).

Cross references:

- https://github.com/bazel-contrib/SIG-rules-authors/issues/11 (GitHub employee is here responding)
- `vcpkg`: https://github.com/microsoft/vcpkg/issues/29288

### Information on your system

N/A

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mathstuf** [comment]
FYI: @tgamblin

**Comment by crtrott** [comment]
Official announcement after the fact: https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/
Big discussion: https://github.com/bazel-contrib/SIG-rules-authors/issues/11

**Comment by crtrott** [comment]
They are reverting.

**Comment by tgamblin** [comment]
I am curious to see what they do as this made it to [the top of Hacker News](https://news.ycombinator.com/item?id=34586917).  It would be nice if we could rely on the tag URLs as some GitHub PMs have apparently said we could.  Depending on what they end up announcing we should either ban these URLs as @mathstuf suggests, or we should make sure they're all the stable ones.

I don't know what to do, if we ban them, for projects that do not provide actual release tarballs.  We could require them to provide git commits for versions instead, but that poses issues for mirroring (because we have no way to verify a tarred up git archive if we have to bundle these to send over an air gap).

**Comment by tgamblin** [comment]
I put a milestone on this as we should really have a policy (since GitHub doesn't)

**Comment by tgamblin** [comment]
GitHub is soliciting input here: https://github.com/orgs/community/discussions/46034

**Comment by mathstuf** [comment]
Prior history: #5411.

**Comment by giordano** [comment]
For reference, update blog post which outlines the new policy: https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by tgamblin** [comment]
Based on this, from GitHub's announcement:

> 1. GitHub will hold the source downloads byte-for-byte stable for no less than a year from today (February 21, 2023). This covers both tarball (.tar.gz) and zipball (.zip) formats.
> 2. In the future, if we intend to change either archive format, we’ll provide six months’ notice in documentation, and on the blog and changelog. (If we discover a critical vulnerability in the compression path, we reserve the right to shorten or omit the notice period in order to protect our systems and our customers. We don’t expect this outcome, but you never know.)
> 3. We presently have no intent to change either format, as we have a new appreciation for the magnitude of the impact this change would have. In full transparency, there are a few deficiencies we wish we could fix (timestamps embedded in zipballs; dependency on system gzip for tarballs), but for the foreseeable future, we’ll engineer around these minor problems.

I do not think we need to change *right now*.  I agree that they should hold *all* the hashes stable, but they aren't committing to that.  On the other hand, they will be stable for *at least* 6 months.

It's not actually feasible for us to switch all projects to stable tarball hashes from the archive hashes, because *not all projects upload stable archives*.  So if GitHub decides to change this, we will need to re-hash tarballs.  There are things we can consider to make that easier to do, for example, recording both the tar.gz hash and a content hash of what was in it, so that we can easily verify any new tarball that comes along. I think if GitHub *is* going to change hashes in the future, we'll need to develop tooling to handle it automatically.

At the moment, we have enough priorities that this one doesn't bubble up to the top, but I think if GItHub one day makes an announcement that the hashes will change in 6 months, we can implement tooling for re-hashing at that time.  I think 6 months is enough time to react.

So, closing this for now, pending any future change announcement by GitHub.

**Comment by mathstuf** [comment]
> recording both the tar.gz hash and a content hash of what was in it, so that we can easily verify any new tarball that comes along

Recording the hash of the inner `tar` should be sufficient (not that `git` makes that stable either, but it is *far* less likely to change IMO).
