### ISSUE TITLE
Spack ABI check doesn't work properly with Apple gcc 4.2.1 (which is clang)

### ISSUE THREAD

**Issue by kielfriedt** [LLNL/spack#3529]
libdwarf failure when building it with elfutils for elf. I tried to install 'libdwarf@20130207%gcc@4.2.1'
and encountered an issue. I believe this is because of the recent changes @lee218llnl did with elf. Stack trace is below and gave multiple examples of how to cause the issue.

```
./bin/spack install libdwarf@20130207%gcc@4.2.1
==> Error: ProcessError: Command exited with status 1:
    '/Users/friedt2/wip/spack/var/spack/stage/elfutils-0.168-nbsfzimkr72rsdiavgwcbilsg7whg6gw/elfutils-0.168/configure' '--prefix=/Users/friedt2/wip/spack/opt/spack/darwin-elcapitan-x86_64/gcc-4.2.1/elfutils-0.168-nbsfzimkr72rsdiavgwcbilsg7whg6gw' '--enable-maintainer-mode'
/Users/friedt2/wip/spack/lib/spack/spack/build_systems/autotools.py:264, in configure:
     257      def configure(self, spec, prefix):
     258          """Runs configure with the arguments specified in :py:meth:`.configure_args`
     259          and an appropriately set prefix.
     260          """
     261          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     262  
     263          with working_dir(self.build_directory, create=True):
  >> 264              inspect.getmodule(self).configure(*options)
```
```
./bin/spack install libdwarf@20130207%gcc@4.2.1 ^libelf

spack/lib/spack/spack/abi.py", line 71, in _gcc_get_libstdcxx_version
    libpath = os.readlink(output.strip())
OSError: [Errno 2] No such file or directory: 'libstdc++.dylib'
```
```
./bin/spack install libdwarf@20130207%gcc@4.2.1 ^libelf

KeyError: 'No such spec in database! libelf@0.8.13%gcc@4.2.1 arch=darwin-elcapitan-x86_64'
```
@lee218llnl Should we set the default elf implementation *back*  to libelf

**Comment by lee218llnl** [comment]
@kielfriedt perhaps we should try to debug this rather than work around it. Based on the errors you get, I'm not seeing how this could be related to the libelf/elfutils modification. For the configure error, can you send the config.log output?

For the second one, can you send the output of the command "gcc --print-file-name=libstdc++.dylib". I don't have a Mac, so I am not going to be able to reproduce the problem.

The third one may be a concretization issue that would be beyond me and again is something I can't reproduce myself. I'll ask others though, particularly @tgamblin.
