### ISSUE TITLE
Installation of Python package doesn't recognise the Python version

### ISSUE THREAD

**Issue by mkowsiak** [LLNL/spack#35399]
### Steps to reproduce

I am looking for a solution when it comes to installing multiple `Python` releases inside `SPACK` based environment. For each `Python` version I'd like to have a dedicated installation of `Python` packages.

For example:

```
spack install python@3.11.0 %gcc@7.3.0
module load python/3.11.0
spack install py-numpy %gcc@7.3.0
spack install python@3.10.0 %gcc@7.3.0
module unload python/3.11.0
module load python/3.10.0
spack install py-numpy %gcc@7.3.0
```

After this sequence I'd like to have two installations of `numpy` - each inside `lib/python#.##` according to currently loaded `Python`.

Is it possible? Does `SPACK` support this kind of the installation? Or should I take some different approach - e.g. multiple `SPACK` environments, each dedicated to one `Python` release?

### Information on your system

```
* **Spack:** 0.19.1
* **Python:** 3.10.0
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Spack does not use environment variables to determine configuration, so the module loads above have no meaning and can be removed. By default, Spack uses Python 3.10, and since you never tell it otherwise it will always build numpy with the same version. The correct way to get what you want is:
```console
spack install py-numpy ^python@3.11
spack install py-numpy ^python@3.10
...
```
Also, I wouldn't recommend 3.X.0 as there are known security vulnerabilities in all versions other than the latest patch release for each minor release. If you don't specify the patch version (like I did above) Spack should choose the latest, unless an older version is already installed, in which case it will be reused.

**Comment by mkowsiak** [comment]
Thanks!

It looks like this is what I was looking for. Now, I can have `py-numpy` for both: `Python 3.10` and `Python 3.11`.

```
gcc-7.3.0/py-numpy-1.23.4-qgzl.../lib/python3.11/site-packages
gcc-7.3.0/py-numpy-1.23.4-y7q5.../lib/python3.10/site-packages
```
