### ISSUE TITLE
Confusion about dependencies of m4

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#3720]
I am using the development branch + PR: 2548, 2972:

```
[sfux@develop02 ~]$ spack find
==> 3 installed packages.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
bzip2@1.0.6  libsigsegv@2.11  patch@2.7.5
[sfux@develop02 ~]$ spack install m4@1.4.18 ^libsigsegv@2.11
==> Error: m4 does not depend on libsigsegv
[sfux@develop02 backup]$ spack info m4 | grep -A1 "Dependencies"
Build Dependencies:
    libsigsegv
--
Link Dependencies:
    libsigsegv
--
Run Dependencies:
    None
[sfux@develop02 ~]$
```

Best regards

Sam

**Comment by davydden** [comment]
that's a known issue with conretizer similar to https://github.com/LLNL/spack/issues/3001 . 
The issue is that it does not take into account default values for variants.
You need to do

spack install m4@1.4.18+sigsegv ^libsigsegv@2.11

ps. @tgamblin we definitely need a new conretizer and a FAQ page with known issues

**Comment by tgamblin** [comment]
@davydden: concretizer is being worked on! 😁  PRs welcome for a "known issues" section for the docs, or I'll see when I can get to it.

**Comment by davydden** [comment]
> PRs welcome for a "known issues" section for the docs

i guess i missed the presence of this section, will have a look.
