### ISSUE TITLE
tmux 2.3 cannot use ncurses package

### ISSUE THREAD

**Issue by sknigh** [LLNL/spack#3849]
spack's ncurses package uses ```--enable-widec``` which builds ncursesw and suppresses building of ncurses and curses libraries. widec support was added tmux in this January 19 [commit](https://github.com/tmux/tmux/commit/61af9d7cc27f9999e4f6e3dab9f786a074a97dee) which post-dates v2.3 by several months.

**Comment by adamjstewart** [comment]
It looks like develop has diverged too much from 2.3 and the patch doesn't apply. Someone will have to update the patch to work with 2.3.

**Comment by eschnett** [comment]
I think we should build `ncurses` in such a way that it provides an `ncurses` pkgconfig file and library.

**Comment by sknigh** [comment]
yum's ```ncurses-devel``` package puts ncurses and ncursesw into separate directories and places the pkgconfig files into a common directory.

**Comment by adamjstewart** [comment]
Homebrew's `ncurses.rb` only builds `ncursesw`:
https://github.com/dajobe/homebrew-dupes/blob/master/ncurses.rb

Our package used to build with `--enable-widec` and `--disable-lib-suffixes` so that the result would be `libncurses.so`, but I found a package that only searched for `libncursesw.so` so I went with how Homebrew does things. In hindsight, it might be better to add a variant...

**Comment by davydden** [comment]
Agreed about the variant

**Comment by sknigh** [comment]
Would a variant work? Suppose a dependency used ncurses+wide and another used ncurses~wide.

**Comment by davydden** [comment]
Well in this case the two are incompatible, but it does not mean that variant does not work

**Comment by KineticTheory** [comment]
FYI - cmake suffers this same issue.  `ncurses+wide` isn't recognized by cmake's build system and without `ncurses~wide`, the `ccmake` application will not be built.
