### ISSUE TITLE
External system packages may hide spack compiler wrappers

### ISSUE THREAD

**Issue by mjwoods** [LLNL/spack#3861]
I followed the advice in spack's Getting Started guide about preferring a vendor-supplied openssl for improved security. This involved creating a packages.yaml file with the following contents:

```
packages:
  openssl:
    paths:
      openssl@1.0.1e: /usr
    buildable: False
```

This seemed to work for many packages, but then I tried to build `qt@4.8.6`. One of the link steps failed with an unresolved symbol from libpng, even though libpng is listed as a dependency by the qt package. I eventually found the problem - `spack env qt@4.8.6 which c++` was resolving to `/usr/bin/c++`. After removing my customised packages.yaml file, spack's `c++` wrapper was found correctly.

What is the best way to force spack to use specified system packages (e.g. openssl) without breaking spack's build environment?

**Comment by adamjstewart** [comment]
Hmm... I thought we had fixed this. Spack is supposed to add all build dependencies to your `PATH` so that the build process can find them. Of course, this includes external packages that may or may not be in `/usr`. At some point we noticed that this caused problems with linking (things were linking to installations in `/usr` even if they were built by Spack) so we made sure that Spack didn't add things like `/lib` or `/usr/lib64` to the link line. Maybe we forgot to do this for the `PATH` too?

**Comment by davydden** [comment]
can you please look in `build.env` and copy-paste `PATH` and `SPACK_DEPENDENCIES`? 

@adamjstewart we do filter here https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L272  and here https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L332 . I have a feeling that the problem is elsewhere...

**Comment by mjwoods** [comment]
Hi @davydden, here are the PATH and SPACK_DEPENDENCIES variables from the spack-build.env produced by `spack install qt@4.8.6`, with packages.yaml forcing the use of openssl from `/usr`. The main thing I notice is that `/usr/bin` occurs in PATH before `/data/mwoods/spack2/lib/spack/env`.

`PATH=/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/glib-2.49.7-6mvzrhcdryemn67ahp3ia4k7x5gc4b5m/bin:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libxml2-2.9.4-yk4fnt3lwvjsjkcewj35yvxotu7irlak/bin:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libtiff-4.0.6-4hwzr2lg34urtkfv6jwebo3rkdkbk6xc/bin:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/jpeg-9b-7mdezufg3chiskzd2y66ckxsehqlabwu/bin:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/icu4c-58.2-52crcjkhyy5g3bbxlpc2pt3ygamw43cs/bin:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libpng-1.6.27-4zz3phez54ulf7j3qaxy2qa52nlkmymv/bin:/usr/bin:/data/mwoods/spack2/lib/spack/env:/data/mwoods/spack2/lib/spack/env/case-insensitive:/data/mwoods/spack2/lib/spack/env/gcc:/data/mwoods/spack2/bin:/home/mwoods/opt/netcdf-4.1.1/bin:/home/mwoods/opt/udunits-2.1.10/bin:/home/mwoods/opt/udunits-1.11.7/bin:/home/mwoods/bin:/home/mwoods/opt/bin:/home/mwoods/opt/ssvnc/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin`

`SPACK_DEPENDENCIES=/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/glib-2.49.7-6mvzrhcdryemn67ahp3ia4k7x5gc4b5m:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/autoconf-2.69-wce2lz6nmutlrgyx67ofm54r7p7t4cy4:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/m4-1.4.18-uxuflkbdlyu53rs2usnvlh36ktyz2t7f:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libsigsegv-2.11-hp5fmaqw3e6e6y237kdmavr5gzb4ub43:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/automake-1.15-f4w47vogfk4nn6d7ukoksbovcrxyvuic:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/gettext-0.19.8.1-jvn64ebtlbievt32fa43mjdrof5ej6c4:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/bzip2-1.0.6-kleqq4isxniiwo2s7ctgb3gcjbls66kp:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libxml2-2.9.4-yk4fnt3lwvjsjkcewj35yvxotu7irlak:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/pkg-config-0.29.2-gvreigcsvldfiweh5qe37uu63mgevo7n:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/xz-5.2.3-p5kdjwwvkrbu6ddr4xx7nzfnoymg7iyt:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/zlib-1.2.11-p354t3uhiqf7btobzka3lphuh2x6ic5w:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/ncurses-6.0-tfbllisfhb2cauoaxevjk6qqzx6lkdqz:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/tar-1.29-ipcximnmozbcjvlwguztrryv4xzbt4qy:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libffi-3.2.1-5tualc4wpkzavyta546sttkoxjitmspn:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libtool-2.4.6-v7uc7asl44a5kacx2yr5lr2klgym4ddf:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/pcre-8.40-e6mwkklabmfe7yuifljfloipdpp3hxes:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/icu4c-58.2-52crcjkhyy5g3bbxlpc2pt3ygamw43cs:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/jpeg-9b-7mdezufg3chiskzd2y66ckxsehqlabwu:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libmng-2.0.2-2ltbe47nhl7ur42mphhlmlommkur6f25:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/lcms-2.6-gxcu5a2ecfh4m6iwej4oncrwrslro6gt:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libtiff-4.0.6-4hwzr2lg34urtkfv6jwebo3rkdkbk6xc:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libpng-1.6.27-4zz3phez54ulf7j3qaxy2qa52nlkmymv:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libxcb-1.12-5igo3baejurwam4trqwclttc36fdcmlf:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libpthread-stubs-0.3-6n2oinitdtkpuoxlgxgnf6nlq2t5umyb:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libxau-1.0.8-lvcfo5ahhj4cnukank3xtxg76jailgpo:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/util-macros-1.19.1-f35wwh47zyshnbap35icfbfwipwkjeru:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/xproto-7.0.29-mqpamn3rlhr7e4rwcslse2kcdwwczrui:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/libxdmcp-1.1.2-ylbihrhciylhzwefgncr2jwlln2kfnpu:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/python-2.7.13-5mif4q7uecrq3zeqiw4uzs2vdo533htc:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/readline-7.0-glm7nakfazghmuid2gb3gwsg3x4lb4lb:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/sqlite-3.8.5-wew6vi2uxfonfiqawra5pxn5t2iomus2:/apps/spack/opt/linux-centos6-x86_64/gcc-4.4.7/xcb-proto-1.12-gsjaibejapm7t7fh47m3mjc5otytfs2g`

**Comment by davydden** [comment]
>  /usr/bin occurs in PATH before /data/mwoods/spack2/lib/spack/env

@tgamblin @alalazo @adamjstewart do you recall where compiler wrappers are appended to PATH? From the post above it looks like this is done **after** `def set_build_environment_variables(pkg, env, dirty=False):` where we filter out system paths to external packages.

**Comment by adamjstewart** [comment]
I'm running into this problem now too. A lot of packages don't build with the old `ld` installed on CentOS 6 so I have a newer Spack installed version in my `PATH`. I also have a few external packages like `/usr/bin/m4` in `packages.yaml`. Spack is prepending `/usr` to my `PATH` and the build is picking up `/usr/bin/ld` instead. I'll try to track this down.

**Comment by adamjstewart** [comment]
I think I found the problem.

As @davydden pointed out, [`set_build_environment_variables`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L238) is where Spack sets `PATH`. On [line 266](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L266), we prepend Spack's compiler wrappers to the `PATH`. Then, on [line 344](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L334), we prepend dependencies to the `PATH`.

As @davydden mentioned, immediately before both lines, we are checking for system paths `['/bin', '/usr/bin', '/usr/local/bin']`. But here's the catch. On [line 263](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L263), we call [`filter_system_paths`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/util/environment.py#L34,L35), but on [line 332](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/build_environment.py#L332) we instead call [`filter_system_bin_paths`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/util/environment.py#L38,L44), which has a completely different specification. The former removes system paths from the list while the latter puts system paths _after_ non-system paths. In my case, I was trying to install `gmp` which only had a single dependency (`m4`). Since I added `m4` as an external package, `/usr/bin` was at the beginning of my `PATH`.

I see a couple potential solutions to this problem. First of all, I see no reason to add dependencies to the `PATH` if they reside in system directories. These values should already be in the `PATH`. Of course, someone could theoretically have multiple copies of a dependency in their `PATH` and want to build with the system one, not the first one. But I don't see any other way to prevent the aforementioned problem. The problem with system paths is that they usually contain hundreds of installations in the same directory, so there's no easy way to control which ones get used and which don't.

Second, I think we should always ensure that Spack's compiler wrappers are at the front of the `PATH`, even before dependencies. I don't see why we would do it any other way.

**Comment by davydden** [comment]
> First of all, I see no reason to add dependencies to the PATH if they reside in system directories.

I actually don't remember why we decided to do in first place. But I agree that we may as well filter out system paths completely. @tgamblin @alalazo do you agree?

> Second, I think we should always ensure that Spack's compiler wrappers are at the front of the PATH, even before dependencies. I don't see why we would do it any other way.

fully agree on this account.

**Comment by adamjstewart** [comment]
It looks like this was all done in #2083. @tgamblin had some arguments for why system paths should be in `PATH`.

**Comment by davydden** [comment]
indeed, here is the link to @tgamblin 's post https://github.com/LLNL/spack/pull/2083#discussion_r84586534

**Comment by davydden** [comment]
i would go for the second solution, and keep the discussion around the first solution for another day.

**Comment by adamjstewart** [comment]
The second solution will solve @mjwoods' problem, but not mine. Go big or go home!

**Comment by davydden** [comment]
oh, i see. Then I am fine with applying both, and add a comment why we really need this (explain your problem) + regression test.

**Comment by adamjstewart** [comment]
We also don't seem to be filtering system paths from `get_rpath_deps`...
