### ISSUE TITLE
Installation issue: neovim libluv

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#39563]
### Steps to reproduce the issue

Working on retooling/updating my machine.  Trying to install the latest neovim on my M1 mac. @albestro @trws 

```console
$ spack install neovim
...
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Error: ProcessError: Command exited with status 2:
    '/Users/psakiev/soft/dotfiles-spack/opt/spack/darwin-monterey-armv8.4a/apple-clang-14.0.0/gmake-4.4.1-2vkvhimmfpgrtax52czg7ghq6ceeidys/bin/make' '-j10'

7 errors found in build log:
     1125      ' (no such file), '/usr/local/liReason: tried: 'libluv.1.dylib' b/libluv.1.dylib' (no such file), '/usr/lib/libluv.1.dylib' (no such file)
     1126    (no such file), '/usr/local/lib/libluv.1.dylib' (no such file), '/usr/lib/libluv.1.dylib' (no such file), '/private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4/runtime/pack/dist/opt/matchit/libluv.1.
             dylib' (no such file), '/usr/local/lib/libluv.1.dylib' (no such file), '/usr/lib/libluv.1.dylib' (no such file)
     1127    /bin/sh: line 1: 29383 Abort trap: 6           /private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4/bin/nvim -u NONE -i NONE -e --headless -c helptags\ doc -c quit
     1128    /bin/sh: line 1: 29385 Abort trap: 6           /private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4/bin/nvim -u NONE -i NONE -e --headless -c helptags\ ++t\ doc -c quit
     1129    /bin/sh: line 1: 29377 Abort trap: 6           ../../../bin/nvim -u NONE -i NONE -n --headless --cmd "set cpo+=+" -S /var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-src/src/nvim/po/tojavascript.vim /private/var/folde
             rs/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4/src/nvim/po/nvim.pot /var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-src/runtim
             e/optwin.vim
     1130    /bin/sh: line 1: 29382 Abort trap: 6           /private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4/bin/nvim -u NONE -i NONE -e --headless -c helptags\ doc -c quit
  >> 1131    make[2]: *** [runtime/CMakeFiles/runtime.dir/build.make:91: runtime/pack/dist/opt/vimball/doc/tags] Error 134
     1132    make[2]: *** Waiting for unfinished jobs....
  >> 1133    make[2]: *** [runtime/CMakeFiles/runtime.dir/build.make:81: runtime/doc/tags] Error 134
  >> 1134    make[2]: *** [src/nvim/po/CMakeFiles/translations.dir/build.make:418: src/nvim/po/nvim.pot] Error 134
     1135    make[2]: Leaving directory '/private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4'
  >> 1136    make[2]: *** [runtime/CMakeFiles/runtime.dir/build.make:86: runtime/pack/dist/opt/matchit/doc/tags] Error 134
     1137    make[2]: Leaving directory '/private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4'
  >> 1138    make[1]: *** [CMakeFiles/Makefile2:2432: src/nvim/po/CMakeFiles/translations.dir/all] Error 2
     1139    make[1]: *** Waiting for unfinished jobs....
  >> 1140    make[1]: *** [CMakeFiles/Makefile2:2541: runtime/CMakeFiles/runtime.dir/all] Error 2
     1141    make[1]: Leaving directory '/private/var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-m2zlku4'
  >> 1142    make: *** [Makefile:159: all] Error 2

See build log for details:
  /var/folders/ln/1_3kxbwd35s_ylsjlm3zmqmc00307v/T/psakiev/spack-stage/spack-stage-neovim-0.9.1-m2zlku4egizhq3ni4hhbvkrk7qnvvlju/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (2cb66e6e44aacca9ea81517031223d662cea23b9)
* **Python:** 3.9.6
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/12403950/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12403952/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by psakievich** [comment]
Hmm wondering if this is related: https://github.com/NixOS/nixpkgs/pull/95364

**Comment by psakievich** [comment]
This seems to be just an issue when using `libluv@1.44.2-1`. If I roll back to `@1.43` then I can install.

**Comment by albestro** [comment]
Sorry for the delay, but I've been super busy in the last months.

Today I had the chance to investigate a bit the problem and I'm pretty sure to have identified it (I opened an issue about it in https://github.com/neovim/neovim/issues/25770).

Starting from `libluv@1.44` they changed library names, which resulted in not using anymore `libluv` static library in favour of the dynamic one...which unfortunately does not work nicely on macOS due to RPATH problem (it is set but not used, I speculate it needs `@rpath` tag in library name, but not sure).

Anyway, the point here is that I confirm that limiting `libluv@1.43` solves the problem as you already experienced, so for the time being until `neovim` will fix the problem with RPATH on macOS, I would add a conflict (I'm going to open a PR soon™).

**Comment by albestro** [comment]
I think it is valuable to add it here for future reference.

The problem is exactly as described above and it is due to `libluv` not installing correctly the dynamic library on macOS (it does not use `@rpath` in the install name) due to a quite old CMake minimum requirement.

From the `libluv` repo, it seems they are going to fix this with https://github.com/luvit/luv/commit/9091cdd5bbcad33236334ea64fb04b116304bb55 in the next release (it is already fixed on `master`).

I'm considering moving the conflict from `neovim` to `libluv` itself.
