### ISSUE TITLE
concretizer: reuse + lookup cause two instances of dag-hash equivalent spec in link-run subdag

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#39570]
### Steps to reproduce

To reproduce:

```
$ cd $(mktemp -d)
$ spack -c config:install_tree:root:./here install py-setuptools
$ spack -c config:install_tree:root:./here spec py-joblib ^/hash-of-just-installed-python
```

This somehow causes python to appear twice with a different Spec instance (different object id) in the same link-run subdag, once through the path:

```
py-joblib -[br]-> py-setuptools -[br]-> python
```

and once directly

```
py-joblib -[br]-> python
```

this confuses Spack internals that rely on `id` instead of `dag_hash` as a key.

It would be better though to ensure that `id(s) == id(t)` for any `s` and `t` in the link/run subdag where `s.dag_hash() == t.dag_hash()`, instead of duplicating the instance.

This causes problems, such as the assertion here, which doesn't traverse with `dag_hash` as a key:

https://github.com/spack/spack/blob/143146f4f3a01b430540530f70afdaa1bbd1c706/lib/spack/spack/package_base.py#L1231

* **Spack:** 0.21.0.dev0 (0e27f0561182e21c838606074ff3eeba0543d6ce)
* **Python:** 3.11.4
* **Platform:** linux-ubuntu23.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Thanks for the reproducer. Confirmed on:

* **Spack:** 0.21.0.dev0 (ab87b4b1a39c64a2185133af6a87c4def33c45e4)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

**Comment by alalazo** [comment]
I'm tracking the origin of the issue.  First fact is that, since we started reusing specs, we got:

https://github.com/spack/spack/blob/00a3ebd0bb8f819c544a066cf1547c3b1e524e0a/lib/spack/spack/solver/asp.py#L2783-L2789

meaning that the concrete spec nodes added in:

https://github.com/spack/spack/blob/00a3ebd0bb8f819c544a066cf1547c3b1e524e0a/lib/spack/spack/solver/asp.py#L2563-L2565

are implicitly assumed to satisfy:
```
s1.dag_hash() == s2.dag_hash() ==> id(s1) == id(s2)
```
This is clearly not the case with the reproducer above.

**Comment by alalazo** [comment]
Ok, I might have a clue - this probably started failing in #39251 because lines like:

https://github.com/spack/spack/blob/00a3ebd0bb8f819c544a066cf1547c3b1e524e0a/lib/spack/spack/solver/asp.py#L2937

create the concrete spec first. Then, reading the DB and such might create concrete specs for dependents of the hash we have on the command line - but with a different object `id`.

**Comment by haampie** [comment]
The issue was reported on commit 477a3c0ef6c6b049284912be7b89583962a449ac before #39251.

**Comment by alalazo** [comment]
Correct, even there we would have the same mechanics - just harder to spot since the lookup is far away from gathering the rest of reused specs (since it happens in the parser)

**Comment by alalazo** [comment]
Also, the same might happen with partially shared specs from DB and from a buildcache

**Comment by alalazo** [comment]
So, I think a possible solution is to ensure, both here:

https://github.com/spack/spack/blob/00a3ebd0bb8f819c544a066cf1547c3b1e524e0a/lib/spack/spack/solver/asp.py#L2939

and here:

https://github.com/spack/spack/blob/00a3ebd0bb8f819c544a066cf1547c3b1e524e0a/lib/spack/spack/solver/asp.py#L2963

that `reusable_specs` contains only specs where the same dag_hash corresponds to the same object in memory.
