### ISSUE TITLE
Add global 'source' variant to install source code

### ISSUE THREAD

**Issue by junghans** [LLNL/spack#4083]
Sometimes it would be useful to have the source code together with the build, so I would like to add a variant (`+source`) in somewhere in the package base class (`spack/spack/package.py`) to trigger a copy of the source code (after patching, before configure/cmake/build) to `<prefix>/src`.

Any suggestions?

**Comment by tgamblin** [comment]
@mplegendre and I have talked about this a bit before -- we'd like to keep the source around for debugging.

Some questions:
1. Were you planning to just keep the source tarball around, or do you want an expanded source directory?
2. Do we need a global variant, which modifies the hash for no reason related to the artifact, or would it make sense to just make this an install option and put the source in the `$prefix/.spack/` directory?  If you did the latter you could always add the source to already-installed things, as it's not an interface guarantee in the spec.
3. What about debug information?  This is the part we never fully hashed out.
    1. Ideally, you'd build the binary against the already installed source, so the debug info would already point to the right place.  (1) only really works well for out-of-source builds, as otherwise you end up with a bunch of .o files and things in the source directory.  That, or it forces you to do the build on a potentially slow shared filesystem instead of `$TMP`.
    1. The other option would be to do the build as usual and patch the debug info on install.  This would be my preference -- but I don't think there is currently a similarly robust analog to `patchelf` for DWARF.

Thoughts?

**Comment by davydden** [comment]
> add a variant (+source)

most certainly should not be a variant as this does NOT change the functionality of behaviour of the installed package. It's more like a `--run-tests` flag, which does some extra steps. 

Btw, there was a discussion somewhere on debugging and keeping the source or patching the installed libs so that you can rug though source during debugging. I could not find it, however....

**Comment by davydden** [comment]
@tgamblin damn, you wrote about debugging just 41 seconds before myself :smile:

**Comment by markcmiller86** [comment]
Is there already precedent for "global" variants? If so...didn't know that and I have always been in the market for a few...

- debug vs. optimized builds
  - and can't a debug build imply the meaning of the proposed 'source' variant here?
- pic vs. no-pic
- 32 vs. 64 bit indexing (used in many HPC solver libs, I/O libs, etc.)
- static vs. dynamic libs (or dynamic and static vs. static only)
- required, common-optional, all dependent libs
  - required is for required dependencies (e.g UNconditional depends_on)
  - common-optional are dependencies that are optional but frequently used (e.g. zlib)
  - all is the whole kitchen sink of dependencies
  - of course, having per-dependency variant controls is probably still useful but a global mechanism for trimming dependency tree would be extremely useful IMHO.

**Comment by junghans** [comment]
> Were you planning to just keep the source tarball around, or do you want an expanded source directory?

I would like the expanded source with all patches applied.

> Do we need a global variant, which modifies the hash for no reason related to the artifact, or would it make sense to just make this an install option and put the source in the $prefix/.spack/ directory? If you did the latter you could always add the source to already-installed things, as it's not an interface guarantee in the spec.

I would like to use `depends_on(package+source)` as a mechanism to distribute binaries incl. their sources to hardware vendors. (/cc @richards12).

**Comment by junghans** [comment]
@davydden: After thinking about it some more make it, making it an option for `install` seemed more reasonable - see #4102.

**Comment by citibeth** [comment]
> Do we need a global variant, which modifies the hash for no reason related to the artifact, or would it make sense to just make this an install option and put the source in the $prefix/.spack/ directory?

I think maybe it should be a variant.  After all, if somebody needs `mypackage+source` and the source is not installed, then that would be a problem.  OTOH, if packages (inside or outside of Spack) never depend on source being installed, then it would not need to be a variant.

>  After thinking about it some more make it, making it an option for `install` seemed more reasonable

Can you further elucidate?  Can you explain the specific use case / problem that is driving this discussion?  I'm not convinced yet.  Maybe a variant is appropriate.  Maybe an option for `install` is appropriate.  Mabye neither is the most appropriate, and we just have a single package that should install (at leas some of) the source but doesn't; `googletest` for example.

> Is there already precedent for "global" variants?

Yes, we already have conventions on certain variants.  But it is not generally done by adding to the `Package` superclass.  Instead, we just add the variant to packages that can use it; and make sure it's named the same in every case.  That way, we don't end up with usless variants (meaning, variants that have no effect) on packages that don't use it.  That said... if the code to use a `+source` variant were in `Package`, and it worked for every package, then that would be a good reason to put it in the `Package` superclass.  Still... if you just want it to work for your package, just add it to your package for now.  And note that adding a variant to `Package` would change all hashes (annoying, but not the first time this has happened).

@markcmiller86 yes, there are precedents.  In answer to the specifics you brought up:

> - debug vs. optimized builds
>   - and can't a debug build imply the meaning of the proposed 'source' variant here?

This will go into a variant on `CMakePackage`, since CMake supports
these build types for all packages, out-of-the-box.

> - pic vs. no-pic
> - static vs. dynamic libs (or dynamic and static vs. static only)

These two will be turned into a single multi-valued variant that applies across most or all packages.  We already have a way to specify a variant "globally", meaning it is applied everywhere that packages can accept it.  Comining those two features, this would allow us to set static/dynamic properties globally in `packages.yaml`.

> - 32 vs. 64 bit indexing (used in many HPC solver libs, I/O libs, etc.)
> - api language bindings (for libs) c, cxx, fort

There's been less work thinking about how to standardize these, thanks for bringing it up.

> - required, common-optional, all dependent libs
>   - required is for required dependencies (e.g UNconditional depends_on)
>   - common-optional are dependencies that are optional but frequently used (e.g. zlib)
>   - all is the whole kitchen sink of dependencies
>   - of course, having per-dependency variant controls is probably still useful but a global mechanism for trimming dependency tree would be extremely useful IMHO.

Trimming dependency trees is a different issue from setting variants; and one we've discussed elsewhere recently.

**Comment by junghans** [comment]
> I think maybe it should be a variant. After all, if somebody needs mypackage+source and the source is not installed, then that would be a problem. OTOH, if packages (inside or outside of Spack) never depend on source being installed, then it would not need to be a variant.
> Can you further elucidate? Can you explain the specific use case / problem that is driving this discussion? I'm not convinced yet. Maybe a variant is appropriate. Maybe an option for install is appropriate. Mabye neither is the most appropriate, and we just have a single package that should install (at leas some of) the source but doesn't; googletest for example.

My use case is the following: I want to make a docker container using Spack, which has e.g. `flecsi` and its dependencies in it, but the container should also incl. the source, so that it is easy to look at all pieces, which are part of the stack. Such a container is especially useful to give to hardware vendors, so they have a starting point incl. build receipt and code.

And yes you are correct, nothing depends on the source and hence I made it an `install` option instead of a variant.

**Comment by citibeth** [comment]
Thanks, sounds good to me.
