### ISSUE TITLE
Gromacs: wrong detection of intel-oneapi-mkl as mkl provider

### ISSUE THREAD

**Issue by gabrielctn** [LLNL/spack#40985]
This line will not detect when `mkl` is provided by `intel-oneapi-mkl`
https://github.com/spack/spack/blob/7e6aaf9458bfc5d42b0c7da1f500a17eef16907c/var/spack/repos/builtin/packages/gromacs/package.py#L597

For example:
```
spack install gromacs@2019.6+cuda~mpi~shared cuda_arch=61,70,75,80,86 ^cuda@11.8 ^intel-oneapi-mkl
```
will set `-DGMX_FFT_LIBRARY=fftw3` instead of `-DGMX_FFT_LIBRARY=mkl`

@danielahlin @eirrgang @junghans @haampie

**Comment by haampie** [comment]
Yeah, I think the issue is that gromacs does not depend on the virtual `mkl` (and obviously should not), only on `blas` / `lapack` / `fftw-api`. Basically the `mkl` virtual is abused to talk about two packages at once, and for a while now Spack no longer implicitly makes a package depend on all virtuals provided by the dependency. Gotta depend on the virtual explicitly.

**Comment by alalazo** [comment]
I'll search and update the packages using this idiom
