### ISSUE TITLE
Updated to newest develop and now am getting openmpi dependence

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4131]
So, I freely admit I could have done something wrong, but...

I just did a git pull upstream develop

and am now trying to re-install a package that I have installed many times this week with mpi and now all of the sudden I am getting openmpi installed too. If I am reading graph output correctly, its comming from hdf5?

|\
| |\
| | |\
| | o |  hdf5
| |/| | 
|/| | | 
o | | |  openmpi
o | | |  hwloc
|\ \ \ \
| o | | |  libxml2
|/| | | | 
| |\ \ \ \
| | |_|/ /
| |/| | | 
| o | | |  zlib
|  / / /
| o | |  xz
|  / /
o | |  pkg-config
 / /
o |  openblas
 /
o  gmake

**Comment by markcmiller86** [comment]
Well, maybe I am not understanding what I am seeing but I don't know why Spack is re-installing MPI for me. I am guessing something has changed in the spec that is causing it to think it needs to re-build MPI ...which I assume will cause it to rebuild all the mpi dependent targets in my uber package.

**Comment by markcmiller86** [comment]
Suspect this is related to #4119

**Comment by citibeth** [comment]
Have you set your preferred MPI in `packages.yaml`?  I would suggest trying that, and see if the problem still persists.  If it does, it's probably because some package is explicitly depending on `openmpi`, rather than just `mpi`.  If that package really only works with `openmpi`, then c'est la vie.  Otherwise, it should be changed to depend on `mpi`.

**Comment by markcmiller86** [comment]
Ok will try that. Thanks.
