### ISSUE TITLE
`spack find -b` is not recognized

### ISSUE THREAD

**Issue by runiq** [LLNL/spack#43052]
### Steps to reproduce

```sh
spack find -b
```

### Error message

```
==> Error: unrecognized arguments: -b
```

### Information on your system

[The docs state](https://spack.readthedocs.io/en/v0.21.1/bootstrapping.html#the-bootstrapping-store) that this should work in this version of Spack (and in v0.21.2, and in v0.22).

`spack debug report`:

* **Spack:** 0.21.1
* **Python:** 3.6.6
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I think it's `spack -b find`

**Comment by runiq** [comment]
Argh, it didn't even occur to me to look there. Sorry for the noise!

**Comment by haampie** [comment]
Let's reopen cause the docs are wrong

**Comment by runiq** [comment]
For the record, the `spack --help` output doesn't mention `-b` either, as of 0.21.2. What's more, `spack clean -b` works, and the `-b` arg is shown in the output of `spack clean --help`.

**Comment by haampie** [comment]
I think `spack -b` is not usually advertised much, maybe too "advanced".

I'm reasonably sure the docs should have originally said `spack -b find` since it is a global toggle, probably `spack find -b` only worked by accident. (Or not @alalazo?) It "regressed" after #17229 

But you're right that `spack find -b` sounds sensible, especially if the person writing the docs assumed that to be the signature too.

**Comment by alalazo** [comment]
I think it was originally `spack find -b` and then moved to `spack -b find`. Not updating the doc was a leftover.
