### ISSUE TITLE
Installing R: Package cairo requires variant ~X, but spec asked for +X

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4312]
Hi all,

I tried to install R 3.3.3 with spack, using the following command (to avoid that spack rebuilds any dependency that is already available on the system, I list all dependencies explicitly):

[spackapps@lo-login-02 bin]$ spack install r@3.3.3+X+external-lapack ^openblas@0.2.19 ^bzip2@1.0.6 ^cairo@1.14.8+X ^curl@7.53.1 ^freetype@2.7 ^glib@2.49.7+libmount ^icu4c@58.2 ^jdk@8u92 ^jpeg@9b ^libtiff@4.0.6 ^ncurses@6.0 ^pcre@8.40 ^readline@7.0 ^tcl@8.6.6 ^tk@8.6.6 ^zlib@1.2.11 ^gettext@0.19.8.1+bzip2+curses+git+libunistring+libxml2+tar+xz ^python@2.7.13+tk ^xproto@7.0.29 ^libpthread-stubs@0.3 ^libx11@1.6.3 ^util-linux@2.29.1 ^libpng@1.6.27 ^fontconfig@2.11 %gcc@4.8.5 arch=linux-centos7-x86-64

The command results in the error:

Package cairo requires variant ~X, but spec asked for +X

Why is this a "hard" requirement to have cairo without +X and if this is the case, why is this not reflected in the output of "spack info r" ?

Best regards

Sam

**Comment by adamjstewart** [comment]
This is a known issue with the concretizer. If you search for issues/pull requests with the `concretization` label, you'll find dozens of similar issues. The problem is that the default variant value is overriding the one required by the dependency. In your case, you can reproduce the issue with a simple:
```
$ spack spec r+X ^cairo+X
```
to work around this issue for now, you need to explicitly activate the `X` variant for `pango` too:
```
$ spack spec r+X ^cairo+X ^pango+X
```
I'll add a note to the documentation.

**Comment by samfux84** [comment]
@adamjstewart Thank you for your help. Adding ^pango@1.40.3+X solved the problem.
