### ISSUE TITLE
[Question] Why don't you split package repo and spack command?

### ISSUE THREAD

**Issue by onokatio** [LLNL/spack#44218]
### Summary

like homebrew, splitting package repository from command repository is useful for maintainance and also stay stable release spack command.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wdconinc** [comment]
This is indeed the plan for the spack v1.0 release (currently v0.22) when the package specification interface is stable. There are a few technical requirements ahead of that being possible. Until then it is easier to be able to apply package specification changes in one repository.

(Closing since question was answered.)
