### ISSUE TITLE
Option to disable sorting of variants in `spack info ...`

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4529]
Spack appears to alphabetically sort variants when it displays them in a `spack info` command. I don't think it should. Or, maybe sorting should be default but have an option to disable it and then list in the order they are defined in the package. Why? When variants are related to each other and/or there are many variants, its better for them to appear next to each other in the `spack info` command. I've added a number of variants to MFEM (coming in a new pull request), and here's what I get...

```
Variants:
    Name [Default]        Allowed values    Description


    debug [off]           True, False       Build debug version

    hypre [off]           True, False       Required for MPI parallel features

    lapack [off]          True, False       Use external blas/lapack routines

    mesquite [off]        True, False       Enable MESQUITE mesh quality
                                            features

    metis [off]           True, False       Required for MPI parallel features

    mpfr [off]            True, False       Enable multi-precision floating
                                            point features

    mpi [on]              True, False       Enable MPI parallel features

    netcdf [off]          True, False       Enable Cubit/Genesis reader

    openmp [off]          True, False       Enable OpenMP parallel features

    petsc [off]           True, False       Enable PETSc solvers,
                                            preconditioners, etc..

    suite-sparse [off]    True, False       Enable serial, sparse direct solver
                                            features

    sundails [off]        True, False       Enable Sundials time integrators

    superlu-dist [off]    True, False       Enable parallel, sparse direct
                                            solver features

    threadsafe [off]      True, False       Enable thread safe features.
                                            Required for OpenMP.

```

**Comment by davydden** [comment]
Maybe should be a per package setting

**Comment by markcmiller86** [comment]
Sure, that is what I think too...a package can decide if it variants should be sorted or not

**Comment by adamjstewart** [comment]
I don't think sorting is incredibly important. We either sort or we don't. We don't need to make this that complicated. How many people vote for sorted and how many people vote for unsorted? I'm indifferent.

**Comment by davydden** [comment]
I am fine with either sorting all or not sorting at all. I kind of agree with @adamjstewart that sorting is not a big deal

**Comment by tgamblin** [comment]
I agree -- not sorting lets the package author pick the order to highlight variants they care most about.  If we *do* want to enforce something, package maintainers can do it for the general case by reordering variants, and still allow exceptions.

**Comment by alalazo** [comment]
@tgamblin On the other hand for packages that have a lot of them (e.g. `boost`) lexicographical ordering won't astonish anyone, while searching for a variant among many in an arbitrary order can be a pain.

> the package author pick the order to highlight variants they care most about

Many packages have more than one author, and they may disagree on which variants they care most about. Lexicographical is lexicographical, and makes everybody *equally unhappy*.

**Comment by markcmiller86** [comment]
@alalazo, @adamjstewart FWIW...I don't view variant ordering or their descriptions in `spack info` as content cognizant package authors care as much about as non-cognizant package installers (e.g. package users and computing center support staff). For them, they are much less familiar with packages and will probably hope to learn *a lot* from `spack info`.

@tgamblin It isn't so much about putting variants they *care about* earlier as it is having variants that are related to each other *next* to each other and, maybe in the future, even grouping variants into categories. The `spack info` command is more or less a poor man's man page or package `INSTALL` or `README` file. Package developers ought to have a tad more control over how it appears.

That said, I can live with lexicographical, but I will be less than equally unhappy.

**Comment by tgamblin** [comment]
@markcmiller86: Thinking about this, I actually agree with @alalazo that this will impact packages with lots of variants, and that `boost`, `trilinos`, and friends are going to be less readable/understandable after the change.  I grepped around a bit and there are quite a few packages with lots of variants:

```
     38 trilinos/package.py
     21 octave/package.py
     16 pagmo/package.py
     15 graphviz/package.py
     15 dealii/package.py
     14 fenics/package.py
     13 petsc/package.py
     13 openspeedshop/package.py
     12 blast-plus/package.py
     11 opencv/package.py
     11 llvm/package.py
     11 intel-parallel-studio/package.py
     11 elemental/package.py
     10 mumps/package.py
     10 cdo/package.py
      9 symengine/package.py
      9 openfoam-com/package.py
      9 hpx5/package.py
      9 gmsh/package.py
      9 foam-extend/package.py
      9 flann/package.py
      9 eccodes/package.py
      9 adios/package.py
      8 vim/package.py
      8 qt/package.py
      8 netcdf/package.py
      8 mfem/package.py
      8 meep/package.py
      8 ibmisc/package.py
      8 hdf5/package.py
```

So, what do we do about the packages where no one's going to reorder the variants? I was actually wrong above that package authors can cleanly reorder.  Packages like boost actually use loops and things to set up different parts of their variant lists (boost actually isn't shown above because of this -- is actually has 27 variants).  There are ~70 packages with 5 or more variants.  Should their order really be arbitrary?  Personally I think that's kind of annoying when I write `spack info`.

Are you sure ordering is what you want, or is it just a stopgap?  I think it would make more sense to add something like an optional category or a basic/advanced tag to variants, and group them by tag in the `spack info` output.  To some extent this is like what we did to `spack -h` in #3033; it worked well there.  It's way more readable now that only a few commands are shown by default.

So, proposal: what if instead of just removing sorting (which will affect other packages), we add an optional `category=` argument to `variant()`, and let `spack info` use it.  If there are no categories, we just display the variants like they are now.  If there are categories, we'll show the command categories first.  e.g., you could add `category='basic'` to some of your variants and get something like this:

```
Variants:
    Name [Default]      Allowed values    Description

  basic variants:

    cxx [on]            True, False       Enable C++ support

    fortran [on]        True, False       Enable Fortran support

    mpi [on]            True, False       Enable MPI support

    pic [on]            True, False       Produce position-independent code
                                          (for shared libs)

  other variants:

    debug [off]         True, False       Builds a debug version of the
                                          library

    shared [on]         True, False       Builds a shared version of the
                                          library

    szip [off]          True, False       Enable szip support

    threadsafe [off]    True, False       Enable thread-safe capabilities
```

That would let you set some stuff apart (with potentailly multiple groups) but would not require packagers who don't care to do anything, and they'd still get alphabetical order.

Thoughts?

**Comment by markcmiller86** [comment]
> @tgamblin So, what do we do about the packages where no one's going to reorder the variants?

Doesn't this question _assume_ lexicographical ordering output by `spack info` was somehow desirable and that without it, package maintainers will have to take action to somehow _correct_ things?

While I do indeed like what @tgamblin proposes here, for some reason I am finding it less than credible that some arbitrary ordering was chosen in the past (lexicographical) and that has somehow miraculously resulted in a more *readable/understandable* output from `spack info` for some packages than an equally arbitrary, but also controllable, _declarative_ ordering I am proposing now.

So, +1 for adding `category=` to `variant()` declarations. But, while we're at it, how about a single declarative `variant_ordering('declarative')` a package can optionally set which causes `spack info` to output in declarative ordering rather than lexicographical.

**Comment by markcmiller86** [comment]
Apologies for wording in previous comment...I've re-worded.

The one case that I think lexicographical ordering is useful for is having to _search_ for a given variant among _many_ variants. Then, yes, I can see how lexicographical ordering could be helpful.

But, I would solve the problem of _searching_ for variants among _many_ a different way. I would just have an option in `spack info` to display those variants matching a given string either in the variant name or the description.

`spack info` would display variants in lexicographical order.

`spack info -v foo PKG` would display all variants for package `PKG` with `foo` either in the variant name or in its description.

`spack info -d` would display variants in declarative order.

**Comment by davydden** [comment]
As a user, I think filtering Spack info's variants via a string would be less useful/helpful than adding categories and grouping variants. I like that Spack info gives everything about the package (variants, dependencies, info, etc) in one go, it's a good overview of everything about a package. It's just the variants are not visually not well organized.

In the long run, I think @tgamblin 's idea of categories + lexicograpkic ordering within each category is the best solution to packages with many variants. I'm in favor of this solution instead of custom ordering.

**Comment by alalazo** [comment]
Honestly I don't like the idea of binding the way we show variants to users to their order of declaration in a `package.py` file. I think *categories* gives enough semantic power to organize them better. So:

- :+1: on categories
- :-1: on using the order of declaration to display information

> for some reason I am finding a little hard to believe that some arbitrary ordering was chosen in the past (lexicographical) and that has somehow miraculously resulted in a more readable/understandable output from spack info for some packages than an equally arbitrary, but also controllable, declarative ordering I am proposing now

Somebody decided on purpose to do that, as the `sorted` function was used in `spack info` and dictionaries are not sorted in python (plus their implementation varies a lot among python versions, see [this talk](https://youtu.be/p33CVV29OG8?list=PLfD5XQ7Sh9P_xMi7hzFSXdUpwr-H4VcqK) for more details). 

I also don't find that strange that lexicographical ordering is considered readable by people... just my two cents, though.

**Comment by markcmiller86** [comment]
Ok, so I think I will simply give up on this.
