### ISSUE TITLE
Conduit build fails to link due to missing MPI libraries

### ISSUE THREAD

**Issue by benjaminjeliot** [LLNL/spack#4629]
When building conduit, the build fails at the linking stage due to missing MPI routines.

I can hack around it by changing line 266 of conduit's package.py from
```python
cfg.write(cmake_cache_entry("MPI_CXX_COMPILER", spec['mpi'].mpicc))
```
to
```python
cfg.write(cmake_cache_entry("MPI_CXX_COMPILER", spec['mpi'].mpicxx))
```
From package.py, it looks like it was set to 'mpicc' for a good reason:
```python
            # we use `mpicc` as `MPI_CXX_COMPILER` b/c we don't want to
            # introduce linking deps to the MPI C++ libs (we aren't using
            # C++ features of MPI) -- this happens with some versions of
            # OpenMPI
            cfg.write(cmake_cache_entry("MPI_CXX_COMPILER", spec['mpi'].mpicc))
```

Build failure was observed on Ubuntu 16.04.

**Comment by adamjstewart** [comment]
@cyrush It looks like you wrote this package. Any thoughts?

**Comment by cyrush** [comment]
Hi All -- thanks for the report & I recognize this issue. 

The existing solution is trying to be defensive about not introducing a mpi c++ interface link dependency (since we don't use the mpi c++ interface in conduit). 

However, I have found some builds of MPI themselves introduce a link dependency on mpi c++ interface  - even if you are only using the mpi c interface.  To make things worse, the mpicc wrappers don't provide the linker flags that add the c++ libs (even though they are really required)

I think this is the case that is hitting @benjaminjeliot.

I think the only real solution in this case is to just use the cxx wrappers for MPI_CXX_COMPILER.
