### ISSUE TITLE
+system variant for OpenSSL

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#478]
The problem: In many cases, it is desirable to use the system's OpenSSL, rather than compiling your own.  Spack needs a way to make this happen.  Possible solution:

> Make a variant of the OpenSSL package, maybe called "+system". This variant would "do nothing" in the install method, except create one file or directory in the install directory to acquiesce Spack.

But... what if this same behavior is desired for other packages as well?  Maybe we should make "+system" be a variant that can be applied to ANY package (by hacking class Package).

**Comment by citibeth** [comment]
I'll volunteer to be assigned to this one.  Just need guidance on:
  a) Whether we think having '+system' as a default variant that can be applied to any package is a good idea, or whether we should keep this just for OpenSSH.
  b) If (a), then pointers on where to hack.

**Comment by becker33** [comment]
Take a look at PR #120, I think it does what you want.

Specifically, you can set a config file of external installs to use. If they match perfectly it will use the system version, but you can also set it as ‘nobuild’ so that only the system version can be used.

Are you looking for something that isn’t provided by this PR?

-Greg

**Comment by citibeth** [comment]
Ah yes... PR #120 strikes again, I think it's going to provide so many really useful things.
