### ISSUE TITLE
flux builds errors with libarchive

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#48197]
Hi! We are getting build errors across the board (for previously working versions) for libarchive:

![image](https://github.com/user-attachments/assets/a8fd1fa5-3239-4ee7-ab22-4cfc353c00a3)

It happened in several places for flux-core last night, and most recent is flux-pmix here: https://github.com/flux-framework/spack/actions/runs/12397521722/job/34608084380.

I was trying to look for some change, either to libarchive or something to flux, but I don't see anything. I'm hoping someone might have insight, because most of the automation is broken not being able to build a previously working version. Thank you!

**Comment by haampie** [comment]
> but I don't see anything

Your runner updated from ubuntu 22.04 to 24.04, and you're using tons of externals.

**Comment by vsoch** [comment]
Aside from downgrading the runner, what is the fix for spack? Why is spack not flexible to the update?

**Comment by haampie** [comment]
Reduce this issue to something smaller and report back. Share what spec Spack concretized to, share the build log / config.log file of flux configure (you're asked to share those when opening an issue). See if `spack build-env <flux> -- pkg-config libarchive` reports errors.

> Why is spack not flexible to the update?

Likely because of 

>  you're using tons of externals

If you use externals, you're telling Spack that the system provides exactly whatever Spack would have installed for those packages. That may not be the case in practice cause sometimes distros install only half of the files of the packages (e.g. `apt install x` vs `apt install x-dev`).

**Comment by vsoch** [comment]
So you are saying if I _don't_ use externals then the problem would be more scoped to spack and you might be more interested to help?

**Comment by vsoch** [comment]
Testing without externals now: https://github.com/flux-framework/spack/actions/runs/12418840422

**Comment by haampie** [comment]
exactly.

you can also significantly speed up these actions by using a build cache on github packages.

See for example the readme here https://github.com/spack/github-actions-buildcache or the action itself https://github.com/spack/setup-spack

**Comment by vsoch** [comment]
I started with the cache and removed it because it wasn't testing the current state of things and led to other problems.

**Comment by haampie** [comment]
--fresh

**Comment by vsoch** [comment]
Errors are fixed! The builds take a long time, but that's OK - if they error next time we can debug in spack. Thanks @haampie, closing.
