### ISSUE TITLE
spack locking system does not make sense

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#5221]
The `.lock` file created in the staging area doesn't seem to be used.  In my specific scenario we have a virtualized head node, so we are using `qsub` to submit installation jobs.  There's a shared filesystem, some voodoo, etc.

This specific use case is obtuse (I wish I could do it directly via `ssh`...), but is analogous to a shared filesystem across servers that have the same `spack` managing each other.

1. I farm out a job compiling `openmpi %gcc@7.2.0`.  Suppose this is PID `A` on Node `B`.
2. A lock file `.lock` in my staging directory is made, stating `pid=A,host=B` has the lock.
3. I farm out a job compiling `openblas %gcc@7.2.0`.  Suppose this is PID `X` on Node `Y`.
4. The `.lock`is deleted, and now states `pid=X,host=Y`.

Solution (?)  Create a `.lock` on the package being compiled, not the staging directory.

P.S. Regardless of the locking system, this hasn't seemed to prevent me from installing anything.  It did once catch it trying to install a dependency that was currently being compiled elsewhere, but there was one time (I think) that it did not.

**Update**: in trying to understand a different error, I (somehow just NOW) learned of the formidable `spack -d` feature.  It seems there is a **lot** more going on with locking than meets the eye:

```
==> READ LOCK: /home/sjm324/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/sjm324/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/sjm324/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Acquiring]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Acquired]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Released]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Acquiring]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Acquired]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[3131744984018514903:1] [Acquiring]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[3131744984018514903:1] [Acquired]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[3131744984018514903:1] [Released]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[3131744984018514903:1] [Acquiring]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[3131744984018514903:1] [Acquired]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[3131744984018514903:1] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/var/spack/stage/.lock[532956495437800316:1] [Acquiring]
==> WRITE LOCK: /share/apps/spack/spack_all/var/spack/stage/.lock[532956495437800316:1] [Acquired]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Acquiring]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Acquired]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/prefix_lock[8903578251265676733:1] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/var/spack/stage/.lock[532956495437800316:1] [Released]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /share/apps/spack/spack_all/opt/spack/.spack-db/lock[0:0] [Released]
```

I still stand by the initial suggestion, though.  Either

1. The locks don't actually do anything (hence why I can `qsub` multiple packages at once and they install correctly).
2. I really don't understand what is actually being locked here.

Locking the specific package being compiled seems to make sense, but definitely feel free to close this if I'm missing the point.  I just sort of observed this, and thought I'd point out the locks may not be doing all they are supposed to.  I have no idea where / how to update anything though.

**Comment by alalazo** [comment]
@svenevs Don't have time right now to check al the details in your issue, but regarding:

> Create a .lock on the package being compiled, not the staging directory.

and

> I really don't understand what is actually being locked here.

We have a very clever locking mechanism thank to @tgamblin. The hash of a package is mapped to a byte in a file, and only that byte is locked. Until you write - never in our case - the file is allowed to stay of size zero. That's why we have a single lock file for all the stages.

**Comment by svenevs** [comment]
> The hash of a package is mapped to a byte in a file, and only that byte is locked

**WOAH**.  Very clever indeed!

I'm willing to bet that the `stage` root directory `.lock` exists for "who should cleanup" purposes?  That would explain why I could `cat .lock` and get something sensible, given the locking scheme you describe.

So if job `A` creates a `.lock` in the `stage` root directory, **and** job `X` (launched before job `A` completes) **is** supposed to overwrite the `.lock` in the `stage` root directory, things are working as expected indeed!

**Comment by tgamblin** [comment]
I would ignore the contents of the `.lock` in the stage directory -- that's somewhat vestigial in that locks were first implemented *without* byte range support, and the hostname and pid written to the lock files were supposed to help with debugging distributed locks.  *With* byte locking, the contents will reflect whoever took *a lock* last, but they'll blow away whatever other host was recorded there.  That's not ideal, and maybe we should write more debug info, but we don't currently use the host information for anything and it is probably too costly to track host/pids for all locked bytes.  I think we should probably write *nothing*.  Sorry that's confusing.

Some more explanation: Both the stage directory and the install root use a *single* lock file to manage *all* their subdirectories (`$stage/.lock` and `$install_tree/.spack-db/lock`).  We lock single bytes in these files like @alalazo said.  [Details here](https://github.com/harlowja/fasteners/issues/26#issuecomment-253543912).  

The advantages of this approach are:

1. We don't have to clean up zillions of lock files for each hash we build.
2. We use fcntl locks instead of file locks (`O_EXCL` locks) which means that locks are released automatically by the OS when processes die, so you don't run into issues like, say, `svn` does where stale lockfiles end up sitting around.
3. `fcntl` locks have readers-writer semantics; `O_EXCL` locks don't support that.

Disadvantages:

1. There is a small risk of false positives, which comes from the SHA-1-to-byte mapping scheme.  A spack run *may* wait for a build it doesn't need to wait for.  I think I worked out the odds of that happening with 100 concurrent builds were like 1 in 400,000.
2. There is one lock file; it's not intended to be cleaned up.  If Spack removed `.lock` when all locks were released, we'd get races between the initial lockfile creation and deletions.  I haven't been able to figure out a decent way around that.  But, again, it's just one file and not lots.

Anyway, @svenevs are you seeing issues with qsubbing more than one Spack build, or are you just noticing that  debug output in the lock file could use some work?  If you are interested in testing your lock support, have a look at #4671 and try to run the lock test in parallel.

**Comment by svenevs** [comment]
Wow, thanks for explaining all of that!

> I think I worked out the odds of that happening with 100 concurrent builds were like 1 in 400,000.

Yeah, I'm definitely OK with those odds!

> Anyway, @svenevs are you seeing issues with qsubbing more than one Spack build, or are you just noticing that debug output in the lock file could use some work? Seems like the latter.

Correct, though I was actually more confused (it seems) about the fact that the PID and hostname are in _the same file_ as where you're doing all this stuff!

I'm closing this as it all definitely seems to be working very well.  While I would love to test it out for you, I'm not 100% on the MPI setup for this cluster.  I'll pass it along to who I'm doing this for, but realistically we probably won't have the capacity to test any of this until after the semester ends.  We're uhhh...kind of cutting it close to when the students need these utilities :scream:

Thank you @alalazo and @tgamblin for explaining what's going on here.  It seems the more I learn about `spack`, the more magical it becomes!!!

**Comment by tgamblin** [comment]
> I was actually more confused (it seems) about the fact that the PID and hostname are in the same file as where you're doing all this stuff!

Oh right.  Locks on files in POSIX are advisory and don't actually have anything to do with what is in the file or whether you can write to it.
