### ISSUE TITLE
Spack doesn't clean up in /tmp directory

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#529]
When I install packages using the standard `spack install ...` commands, it often leaves staging directories in `/tmp/eschnett` behind. Over time, these become very large. Spack should clean up automatically.

For example, after installing PETSc successfully, Spack should clean all previous PETSc staging directories that it left behind.

Or maybe it should only using a single staging directory for PETSc, and not a new one for each attempt.

As is, the amount of disk space used is a trap; people might not even be aware of it.

**Comment by tgamblin** [comment]
I agree.  Two things:

1. The first thing we ought to do is to consolidate the tarballs, as suggested in #281.  That would at least move the archives to a common place (they're currently duplicated per stage).  Users might also want to preserve the archives separately from the source directories.

2. I am not sure about the policy you suggest.  It might be an ok policy for a single-user spack instance, but some sites have several users deploying packages with a common Spack user, in which case you might end up cleaning up someone else's stuff.  Instead of that, how about a config option to set the length of time a stage can stick around unmodified in Spack's staging area?  We could set it to, I dunno, a few days or a week by default.  Spack could touch any top-level stage directory that it works with, each tim hit builds.  We can then remove any stage that hasn't been touched in the specified amount of time.

This is more inline with the way sites typically configure their /tmp directories.  LLNL, for example, purges /tmp if it's close to full or after a certain amount of time.  It prefers to purge older stuff. Thoughts?

**Comment by adamjstewart** [comment]
For reference, #579 addresses point 1.

**Comment by adamjstewart** [comment]
Is this issue still relevant? I think `spack install` automatically deletes the staging area after a successful installation. Although I could be wrong, because I run `spack purge` religiously.

**Comment by scheibelp** [comment]
> I think spack install automatically deletes the staging area after a successful installation.

It will unless the user specifies ```--keep-stage``` or if the install fails.
