### ISSUE TITLE
Putting packages on PATH (MANPATH...) permanently

### ISSUE THREAD

**Issue by dlukes** [LLNL/spack#5346]
A newcomer to spack here, so sorry in advance if this is a dumb question :)

When I install e.g. `vim`, I know I can then put the binary on my PATH (the manpage on the MANPATH, etc.) with `spack load vim`. But is there a preferred/recommended way to do this permanently and for multiple packages, so that I don't have to do this manually each time I want to use them? Or should I just roll my own solution (e.g. symlinking the files installed under `spack/opt/spack/` to directories which are already on my `PATH`, `MANPATH` etc.)?

I'm not in the HPC trade, I'm looking for an alternative to Linuxbrew, which I just spent a whole afternoon in frustration trying to install on an older Ubuntu system. So far, `spack` seems to do a much better job at coping with older compilers and generally "weird" environments, all the `install` commands have been painless. The only missing piece of the puzzle is how to put the packages permanently on the `PATH`, `MANPATH` etc.

I realize my use case for `spack` is somewhat atypical, so there may be no "standard" way of doing this. But if there is, could someone please point me to the place in the docs where this is explained? Thank you very much :)

**Comment by tgamblin** [comment]
So, Spack was designed for deployment on clusters with lots of users, which is why modules are the  current way to do things.  But we are working on something that would much more closely resemble environments in something like `conda` or `virtualenv`, where you could create an environment, install a bunch of packages into it, and have them on your `PATH`.  We're shooting for later this year (thanks to @scheibelp and @mathstuf).

In the meantime you could try using the `spack view` command -- it lets you manually link packages and their dependencies into a common prefix (like `brew` does in `/usr/local`).  It doesn't guarantee you anything w.r..t consistency (you can link two conflicting packages) but it might let you set your environment up once and add to a view when you need to.

**Comment by dlukes** [comment]
> In the meantime you could try using the spack view command

This is perfect, thank you so much for the quick reply! This means I don't even have to tinker with the various path settings, I just put the view under the old brew prefix and everything just works :) Thanks again!
