### ISSUE TITLE
REALLY, Maybe There Should be Two Python Packages

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#556]
This is a continuation of: https://github.com/LLNL/spack/issues/275
@eschnett @lee218llnl @tgamblin 

Adding build dependencies will be a good start, but I don't think it will solve all the problems we're encountering with Python 2 vs. 3.  Consider the following:

Suppose we have Library A and Library B, both of them are C/C++/Fortran libraries that do useful things.  They also come with Python bindings, provided as Python extension modules.  For whatever reason, Library A provides only Python 2 bindings, and Library B provides only Python 3 bindings.

Now I want to build Application C, which depends on Library A and Library B.  As author of Application C, I don't care about Python, I'm just writing a C/C++/Fortran program that uses two libraries.  Linking C with A and B is perfectly legal and correct.  However, Spack as it currently stands would disallow this.

A this point, I have no obvious answer to this problem, I believe some brainstorming is in order.  Let me suggest the following possibilities:

1. Separate python2 from python3.  Thoughts:
   a) This makes sense because Python2 and Python3 are different languages with different binaries created by the default Python build.
   b) I would hope we don't have to go down the slippery slope of creating new package versions for every minor version of Python.
   c) This won't solve every Python compatibility problem: if Library A needs python3@3.4: and Library B needs python3@3.0:3.3, then we still have an unnecessary incompatibility

2. What if instead of Library A, we had two packages:
```
         alib:   Just the C/C++/Fortran library
         alib-py: Python bindings for alib
            depends_on('alib')
            depends_on('python@2.7')
```
and similarly for B:
```
         blib:   Just the C/C++/Fortran library
         blib-py: Python bindings for blib
            depends_on('blib')
            depends_on('python@3.2:')
```

Now we can link alib and blib no problem.  However... How can we make two Spack packages out of a single build?  This is where maybe Spack needs a new feature.  For example... what if we had "underlying" packages that then get turned into multiple "borrowing" packages:

```
alib-underlying:  # The underlying package, produces C library and Python extension

alib:
    depends_on('alib-underlying')
    To install: copy/link bin/, lib/, etc. directories from alib-underlying

alib-py:
    depends_on('alib-underlying')
    To install: copy/link the python/ directory from alib-underlying
```

This idea is based on the observation that any package that provides a useful library plus Python bindings is really like two packages in one.  As long as Python-related packages provide ONLY a Python bindings, then I think we'll be able to manage.  But if real-world packages provide multiple things at once, we need to figure out how to separate out Python-only packages.

**Comment by eschnett** [comment]
When I write a Python script, I'd like to put either `/usr/bin/env python2` or `/usr/bin/env python3` into the shebang line. That's reasonable, and that such a mechanism is necessary was foreseen by the Python developers. If I have to write `python2.6` or `python2.7.11` there, then something's wrong with the script, or it's a throw-away script.

We have different packages for HDF4 and HDF5, since they have a very different API and can be installed simultaneously without conflict.

I think the criterion should be:
1. Do the different versions conflict? (binary names, library names, API, etc.)
2. Are there people who might want both versions installed and accessible simultaneously?
3. Are there people who might want to have only one version available?

If there's a conflict, then the discussion is moot.

If people might want both versions simultaneously, then there should be either two separate packages, or a package that installs both simultaneously (e.g. FFTW single and double precision).

If many people reasonably might want only a single version, then there should be two packages.

**Comment by tgamblin** [comment]
@citibeth @eschnett: I can't write a detailed response to this right now but I think that @mathstuf's dependency types module goes some of the way to addressing this situation.  Or at least @mathstuf should look at it and see if it does. He has separate notions of build, link, and run dependencies.  

For the Python bindings @citibeth mentions, I *believe* that Python is only a run dependency.  For C, Python is *not* a run dependency, so the Python build/run deps of A & B should not conflict.

I still need to think about how the spec DAGs should look here, but I'm curious whether this is already workable in @mathsuf's PR.  @mathstuf?

@citibeth Another thing to think about would be doing this with virtual deps, which can be versioned.  But that doesn't address the partial package aspect.

@eschnett: So do you think there should be two packages?  I am torn on this because Python is in a weird spot.  There are lots of libraries that are starting to work with both Python 2 and 3, and I am not sure that separating things won't make it more complicated for those deployments in the future.  I think the criteria are reasonable... I need to think about this stuff more.

**Comment by tgamblin** [comment]
@citibeth: is there a reason you can't get basically what you want, right now, by using variants?  Suppose you do this:

```python
A:
    variant('python', default=True, 'enable python bindings')
    depends_on('python@2.7', when='+python')
    def patch(self):
        # do whatever is necessary to enable/disable python bindings according to variant
B:
    variant('python', default=True, 'enable python bindings')
    depends_on('python@3.2:', when='+python')
    def patch(self):
        # do whatever is necessary to enable/disable python bindings according to variant
C:
    depends_on('A~python')
    depends_on('B~python')
```

That will result in potentially more copies of A and B than you want but it will work.

**Comment by citibeth** [comment]
> @citibeth @eschnett: I can't write a detailed response to this right
> now but I think that @mathstuf's dependency types module goes some of
> the way to addressing this situation. Or at least @mathstuf should
> look at it and see if it does. He has separate notions of build, link,
> and run dependencies.

So let me get this straight...
  1. Build Dependency: I need CMake to build a project
  2. Link Dependency: I link to libssl.so in my project
  3. Run Dependency: I provide some Python3-specific .py files in my project.

> For the Python bindings @citibeth mentions, I believe that Python is
> only a run dependency.

Unfortunately, I believe Python is a link dependency as well.  I think that will be the case any time you create a Python C extension.

> For C, Python is not a run dependency, so the
> Python build/run deps of A & B should not conflict.

I'm dubious... but I think it's certainly worthwhile to see the results of @mathstuf's dependency types module and re-evaluating before rushing ahead on something else.

> @eschnett: So do you think there should be two packages? I am torn on
> this because Python is in a weird spot. There are lots of libraries
> that are starting to work with both Python 2 and 3, and I am not sure
> that separating things won't make it more complicated for those
> deployments in the future. I think the criteria are reasonable... I
> need to think about this stuff more.

My predictions on the Python 2/3 issue:
 1. Of the libraries that now work with 2/3, some will drop their Python2 support in some distant future.  Python2 IS deprecated, after all.
 2. Libraries with fewer resources behind them will never support 2/3, or will do so for a much shorter period of time.  My code is a good example.  One day, I decided it was time to switch to Python3.  And I did.  It was too much work to maintain backwards compatibility for Python2.

> @citibeth: is there a reason you can't get basically what you want,
> right now, by using variants? Suppose you do this: That will result in
> potentially more copies of A and B than you want but it will work.

I think that is the solution for now.  Building more copies of A and B than you absolutely have to is NOT the end of the world.  Thanks!

**Comment by mathstuf** [comment]
While I think that separate Python2 and Python3 packages might make sense, spack isn't really set up to handle such things. If an adequate answer can be given to this question, then splitting might be feasible:

  - With a DAG which contains Python2 and Python3 libraries, how should one construct `PYTHONPATH`?

> Build Dependency: I need CMake to build a project
> Link Dependency: I link to libssl.so in my project
> Run Dependency: I provide some Python3-specific .py files in my project.

Here, openssl is also a build dependency (you require its header to compile). You may also need python3 as a build dependency if you use something like `setup.py` to install those `.py` files (and probably `py-setuptools` too in that case).

> Python2 IS deprecated, after all.

Inaccurate. It is supported by upstream until 2020. While there may not be a 2.8, 2.7.16 may be a thing. It also certainly won't die in 2020.

> It was too much work to maintain backwards compatibility for Python2.

And some projects have yet to make the jump because supporting Python3 is too much work (usually because Python2 can't be dropped necessarily).
