### ISSUE TITLE
dependencies resolution: package +feature && package => equivalent

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#577]
Currently the following undesired behaviour may appear.
`petsc` has `depends_on('boost', when='+boost')`. However, if the user has `boost +mpi` installed, `petsc` would still try to install yet another boost, supposedly because `boost != boost +mpi` somewhere in the core.

When a decision is made to install or not another variant, IMHO the comparator should behave like
`boost && boost +mpi => true (do not install)`
whereas
`boost && boost -filesystem => false`.
That is, anything that extends the default variant should be as good as default. Whereas if some features are disabled, then one might need to reinstall it.

**Comment by adamjstewart** [comment]
This is a duplicate of #311.

Basically, the problem is that Spack currently doesn't take previously installed packages into account when deciding what to install.

I think we all agree that Spack should use previously installed packages more frequently instead of rebuilding everything that doesn't meet the spec exactly. But no one has gotten around to solving this problem yet.

**Comment by tgamblin** [comment]
@davydden: I'll try to clarify this because #311 is kind af a sprawling discussion and I need to document this anyway, so here's a rough draft.

As @adamjstewart said, see #311, and the most recent telcon notes -- better concretization is planned (and may show up very soon).

Currently the concretizer runs first without looking at what is installed, and it will reuse *only* if there is an exact match to what it comes up with.  This several negative implications:

  1. As you mention, if a package only requires `boost`, then it will rebuild if, e.g. `boost+mpi` is installed. This is not actually an issue with the `Spec` implementation; it's beacuse `mpi` is disabled by default, and only the fully concretized spec is tested against what is installed.  Spack does not compare to what is installed until *after* all the defaults are applied, so it doesn't notice that `petsc` doesn't care if `boost` has MPI support.

    If you look at what `Spec` actually does, though, the satisfaction rules are what you'd expect:

    ```bash
    $ spack python
    >>> from spack.spec import Spec
    >>> Spec('boost', concrete=True).satisfies('boost+mpi')
    False
    >>> Spec('boost+mpi', concrete=True).satisfies('boost')
    True
    ```

    An installed `boost+mpi` *should* be good enough to satisfy a request for `boost` (as `boost+mpi` is more specific).

    This gets tricky with disabled variants, and we do things slightly different than what you suggest.  Variants are intended to model only *additional* functionality on top of the base package, and if packages need a feature, they're expected to request it via:

        depends_on('pkg+feature')

    This prevents us from getting a bunch of packages that implicitly *expect* particular builtin functionality.

    What that means here is that an installed `boost~filesystem` *will* be good enough to satisfy a request for `boost`, as well.  Only if a package really *conflicts* with `+filesystem` should it say this:

        depends_on('boost~filesystem')

    That indicate that the package really won't work with a boost that has `filesystem` enabled.

    Now, you might ask, what happens if I do this:

    ```bash
    spack install boost
    # time passes
    spack install <package that depends on boost~filesystem>
	```
    
    It depends on what the defaults are for the variants.  There are three cases: 

      1. The first `boost` defaulted to `~filesystem`
      1. The first `boost` defaulted to `+filesystem`
      1. There was no `filesystem` variant on `boost` when the first `boost` was installed.

    Packages are installed with concrete values for all variants that exist at the time of installation.  So if `filesystem` *was* a variant for `boost`, then one of the first two cases applies.  Spack will ideally not end up rebuilding in case (i) (it may right now, if some other default setting for boost has changed, due to this concretization issue).  It *will* rebuild in case (ii), as the new package explicitly requested `+filesystem` and there isn't an installed boost that can satisfy the request.

    In the third case, Spack can't guarantee the state of `filesystem` on the prior `boost` install because the `package.py` build didn't know what `filesystem` was when it ran.  So, to be safe, Spack always rebuilds in this case.  Even if the prior version of `boost` disabled filesystem implicitly, we don't know whether that's true.  We decided it was simpler to rebuild a new version than to track how all prior versions of a package treated a non-explicit variant.  This gives the package authors a bit more freedom with things that are not explicitly "exposed", and it reduces the maintenance burden for package authors, as they don't have to somehow label prior package versions' defaults when they add a new variant.

    Make sense?  

  2. Another negative implication of not reusing what is installed is that if a package changes in a very small way, just enough to change its hash, then Spack will rebuild.  This makes it hard for people to get much stability if they frequently pull from github -- they'll end up rebuilding every time the default version changes or every time a variant is added.  We'd like to avoid that, so that users can upgrade when they're ready.

  3. Along the lines of (2), users don't always want the bleeding edge version; it may have security problems.

  4. Not sticking with what's installed mean you often have to type more than you might like.  e.g., if you install `openmpi`, and then install several packages that depend on `mpi`, Spack will try to build `mpich` when Spack should realize that you wanted `openmpi` because you installed it.

Of course, there is one major downside to concretizing based on what is installed: you lose determinism. Installing a spec that is partially constrained now depends on the order in which you install things.  Some people don't want that.

Anyway, we agreed in #311 that Spack should look at what is installed more carefully while concretizing, and the additional logic in #120 should make this easy to add very soon.  I also plan to keep an option on `spack install` that allows you to still ignore what is already installed, in case you want to force Spack to stick with its defaults or a site's defaults.  This should strike a good balance between reuse and determinism.

If you're interested in that, see the discussion in the most recent telcon notes, which outlines how I would like `packages.yaml` preferences to work w.r.t. looking at what is installed.  It gets fairly complicated but I think we've got a reasonable set of ideas.  I think that one this and specialized `packages.yaml` files are in place, things will be much more pleasant to use.

**Comment by alalazo** [comment]
@davydden Just to add a consideration that I don't see above : there are cases in which the behavior you suggest should be the opposite. Think of the commonly used `debug` variant : I assume that most of the users would expect that the default choice should be `~debug` if something is already installed, not `+debug`.

**Comment by davydden** [comment]
Thanks for the writeup, @tgamblin .

> What that means here is that an installed boost~filesystem will be good enough to satisfy a request for boost, as well.

so i suppose if a certain package really needs `filesystem`, it should not rely on default and instead write `depends_on(boost+filesystem)`. Then, if `filesystem` is `on` by default, `boost` will be enough. Otherwise `boost+filesystem` will be installed.

> Another negative implication of not reusing what is installed is that if a package changes in a very small way, just enough to change its hash, then Spack will rebuild. 

What is actually hashed? I thought you hash part of the DAG starting from the package node? Or do you also hash the python script?

> Of course, there is one major downside to concretizing based on what is installed: you lose determinism. Installing a spec that is partially constrained now depends on the order in which you install things. Some people don't want that.

if I understand you correctly, it's not the order only, but variants. 
```
spack install boost+mpi
spack install petsc
```
would give me one stack (assuming that `boost+mpi` satisfies `depends_on(boost)`), whereas 
```
spack install petsc
```
would give a boot without `mpi`. Or if you start from some other package that use `boost+mpi+feature` and also `petsc`, then `petsc` might end up being build against `boost+mpi+feature`. 
I suppose you can only guarantee determinism if you start from the top node in DAG on a fresh installation.

@alalazo:
> I assume that most of the users would expect that the default choice should be ~debug if something is already installed, not +debug

fully agree. But I don't think it should change the behaviour, the debug build should satisfy the original requirement. If the package has `depends_on(boost)`, one should be able to build it against `boost+debug` as one might be looking for a bug, hidden in boost library.

**Comment by alalazo** [comment]
@davydden So if one has `boost+debug` installed (for whatever reason) and:
```
class Foo(Package)
    variant('debug', default=False, ... )
    depends_on('boost')
```
you propose that :
```
spack install foo
```
uses the `boost+debug` for concretization, while you need to type : 
```
spack install foo ^ boost~debug
```
to build for production? I would expect the opposite behavior. In particular I think that this may become quite annoying for packages having a long list of dependencies (you have to specify `~debug`).

My point is that variants are not always expressing an 'extension', they might also represent a change in behavior and it is not straightforward that `+variant` will be always considered the good default choice.

**Comment by davydden** [comment]
> My point is that variants are not always expressing an 'extension', they might also represent a change in behavior and it is not straightforward that +variant will be always considered the good default choice.

fair enough. I agree. That would indeed be undesirable behaviour.

In that case one could indeed stick with the current concretisation logic as long as one can do the following (which is possible as far as I understand but I have not tried):

with

```
class Petsc(Package)
   depends_on('boost')
```

`spack install petsc` -> installs `boost`
`spack install petsc ^boost+mpi` -> installs `boost+mpi`

Whereas with

```
class Foo(Package)
  depends_on(`bost+mpi`)
  depends_on(`petsc`)
```
`spack install foo` -> installs `boost+mpi` as a common prerequisite for `petsc` and `Foo`.
`spack isntall foo ^boost+mpi+debug` -> installs `boost+mpi+debug` as a common prerequisite for `petsc` and `Foo`.

For that to work, somewhere `package+variant` should be positively compared to `package` to end up with a satisfying graph.

To make that kind of resolution clear for package developers and user, perhaps one needs to add a section in documentation which explains briefly construction of a (direct acyclic) graph and how can one re-use already installed packages by adding `^foo+variant`.

**Comment by tgamblin** [comment]
@davydden: both of the cases you listed should work as you describe, assuming that for `petsc`, `debug` defaults to `False`.  If `debug defaults to `True`, `spack install foo ^boost+mpi+debug` will just reuse the `boost` build by the previous command.

Also, to make the example more clear, within any package DAG, everything is RPATH'd so that only *one* configuration of any dependency package is in any package's RPATH.

That is to say, you can't have a DAG like this:

    A --> B --> D
      \
       C --> D'

Because now there's a race between `D` and `D'` -- the one that is loaded first will win at runtime and there may be errors.  

Spack only allows DAGs like this:

    A --> B
     \     \
      C --> D

There is a normalization step before (and during) concretization where constraints on the same package are merged.  You'll get an error saying that a spec is unsatisfiable if you do something like this:

```python
class A(Package):
    depends_on('B')
    depends_on('C')

class B(Package):
    depends_on('D+option')

class C(Package):
    depends_on('D~option')
```

**Comment by davydden** [comment]
@tgamblin i think i came across a current limitation of the implementation of syntax. In case
```
A->B->D
```
when I ran `spack install A ^D+feature` I get an error 
```
==> Error: A does not depend on D
```
So spezialisation seems to happen only for the main node and not for the whole graph.

Going back to the petsc example, what I have is
```
slepc (reuse what PETSc configure with) -> petsc -> boost
```
but pets's default boost is without mpi support. So it does not seem to be possible to install now `slepc`, build against `petsc` with `boost+mpi` instead of a standard `boost`. 

From a user perspective, instead of automating re-usage of previously installed packages, 
i think it would be enough to allow user to specify variants in the whole graph.

**Comment by eschnett** [comment]
You can write `spack install A ^B ^D+feature`; this will work. For example, I write
```
spack install petsc %gcc@5.3.0-spack +boost +hdf5 +mpi ^boost+mpi ^hdf5+mpi ^openblas ^openmpi
```

Yes, it suffices to allow people to specify the graph (and that is already possible). The question is what Spack's default behaviour should be -- use the minimal feature set, or look for already-installed packages.

To find a good default behaviour, one need to answer two questions:
- what do people want to do most of the time?
- what constitutes a "bad surprise", i.e. a "trap" for novice users?

I think many people will expect Spack to reuse an existing, installed package. That is a "natural" think to do, and the feature requests that people submit also indicate this.

On the other hand, rebuilding a package with different feature set if there is an existing package that would match is somewhat of a "trap": it costs time to re-install that package. There's also the following problem: if A is installed, and then B is built which automatically installs a different version A', and then package C requires both A and B, Spack needs to install a new version B' depending on A so that we then have:
```
A
A'
B -> A`
B' -> A
C -> (A, B')
```
which is five installed versions instead of three.

**Comment by davydden** [comment]
@eschnett that does not work:
```
$ spack install slepc ^petsc+mpi ^boost+mpi
==> Error: slepc does not depend on boost
```
I think you miss the point in dependencies, which are `A->B->C`, not `A->C` and `A->B->C`

**Comment by eschnett** [comment]
PETSc does not depend on Boost unless to use the `+boost` variant:
```
spack install slepc ^petsc+mpi+boost ^boost+mpi
```

**Comment by davydden** [comment]
oh, i see where my confusion come from: 
I though default variants (those which have `default=True` ) are applied automatically when you specify `^pacakge + variant` as they do when you install the package by `spack install <package>`. Thanks for pointing to this direction, @eschnett .
As a naïve user, i would prefer the defaults to be active in this case as well. So for `petsc`, in order to have anything disabled one would write `spack install slepc ^petsc~boost~mpi`. Which IMHO also makes sense as the following two lines become equivalent: `spack install slepc` == `spack install slepc ^petsc`. 
Perhaps there are also reasons not to do so.

**Comment by davydden** [comment]
Looking at the `spec` it seems that defaults are turned on already
```
$ spack spec slepc+arpack ^petsc+mpi+boost ^boost+mpi
Input spec
------------------------------
  slepc+arpack
      ^boost+mpi
      ^petsc+boost+mpi

Normalized
------------------------------
  slepc+arpack
      ^arpack-ng+mpi
          ^blas
          ^lapack
          ^mpi
      ^petsc+boost+mpi
          ^boost+mpi
          ^python@2.6:2.7
              ^bzip2
              ^ncurses
              ^openssl
                  ^zlib
              ^readline
              ^sqlite

Concretized
------------------------------
  slepc@3.6.2%clang@7.0.2-apple+arpack=darwin-x86_64
      ^arpack-ng@3.3.0%clang@7.0.2-apple+mpi+shared=darwin-x86_64
          ^openblas@0.2.16%clang@7.0.2-apple=darwin-x86_64
          ^openmpi@1.10.2%clang@7.0.2-apple~psm~tm~verbs=darwin-x86_64
              ^hwloc@1.11.2%clang@7.0.2-apple=darwin-x86_64
                  ^libpciaccess@0.13.4%clang@7.0.2-apple=darwin-x86_64
                      ^libtool@2.4.6%clang@7.0.2-apple=darwin-x86_64
      ^petsc@3.6.3%clang@7.0.2-apple+boost+double+hdf5+hypre+metis+mpi+shared=darwin-x86_64
          ^boost@1.60.0%clang@7.0.2-apple+atomic+chrono+date_time~debug+filesystem+graph~icu_support+iostreams+locale+log+math+mpi+multithreaded+program_options~python+random+regex+serialization+shared+signals+singlethreaded+system+test+thread+wave=darwin-x86_64
              ^bzip2@1.0.6%clang@7.0.2-apple=darwin-x86_64
              ^zlib@1.2.8%clang@7.0.2-apple=darwin-x86_64
          ^hdf5@1.8.16%clang@7.0.2-apple+cxx~debug+fortran+mpi+shared~szip~threadsafe=darwin-x86_64
          ^hypre@2.10.1%clang@7.0.2-apple+shared=darwin-x86_64
          ^metis@5.1.0%clang@7.0.2-apple~debug~double~gdb~idx64+shared=darwin-x86_64
              ^cmake@3.5.0%clang@7.0.2-apple~doc+ncurses~qt=darwin-x86_64
                  ^ncurses@6.0%clang@7.0.2-apple=darwin-x86_64
          ^parmetis@4.0.3%clang@7.0.2-apple~debug~double~gdb~idx64+shared=darwin-x86_64
          ^python@2.7%clang@7.0.2-apple=darwin-x86_64
```
so i think it kind of works as expected already with a workaround of specifying `^petsc+mpi+boost` in order to make `slepc` see that it eventually depends on boost.

**Comment by tgamblin** [comment]
@eschnett @davydden: currently Spack isn't smart enough to make a common reverse inference:

    spack install slepc ^petsc+mpi ^boost+mpi

This doesn't work because you don't have `^petsc+boost`, and Spack needs a little help to figure out that the only way you'd get `^boost` is with `petsc+boost`.  It makes things a little more cumbersome on the command line -- personally I think what @davydden wrote should work and should probably enable boost since that is the only way it could work for this build.

I *think* this is actually an easy fix in DAG normalization -- instead of raising an error if there are unknown deps, Spack *could* look ahead one level of optional deps to see whether simply enabling a variant would make the dep legal.  This is still a greedy decision, though, and there are cases where it won't be right.  I'm unsure how common they are.  One example: what happens if you see *two* packages with a variant (`+boost`) that enables this dependency (`^boost`)?   For simple stuff, you probably want to enable both of them, but what if one of the variants enables some other dependency, too, and that conflicts with something else in the DAG?  Or, what if there are as-yet unexpanded virtual pkgs that *could* result in additional concrete packages that have a variant that enables this dependency :scream:?  There is a limit to how far we can explore that space with the current implementation.

I think once we have full constraint solving we could implement something that lets you do the right thing in unambiguous cases and require disambiguation when it's not obvious, but right now a quick fix would be a greedy one so I hesitate to put it in.  Thoughts?

**Comment by davydden** [comment]
@tgamblin that sounds like a lot of corner cases to me. Personally, i am fine with helping `spack` a bit to realise that `petsc` also has `boost` enabled by default. I would suggest to cover this a bit in the documentation (including issues you raise) so that new users know how to make it work in their context.

**Comment by davydden** [comment]
i think we can close this one.
