### ISSUE TITLE
temporary build folder and logs

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#586]
Currently the temporary folder where a package is build can be quite elaborated: `/private/var/folders/5k/sqpp24tx3ylds4fgm13pfht00000gn/T/davydden/spack-stage/spack-stage-k7EHWk/trilinos-12.4.2-Source`. That makes debugging build errors more difficult than it should. I think something like `/private/tmp/trilinos-12.4.2-<hash>` would be better.

I would also suggest keeping build logs in some folder, i.e. `skack/logs` (separated for configure and build). The rationale is as follows: if the build is successful, the temporary folder gets deleted. But successful build does not yet mean correct build. Sometimes it is convenient to check configure stage of a package to see, say, what parts of the library were enabled/disabled. Good example is trilinos.

**Comment by tgamblin** [comment]
The location for temporary directories on Mac OS X comes from the value of `$TMPDIR`... which is indeed set to something more convoluted than on other systems:

My mac:
```bash
(atala):~$ env | grep TMP
TMPDIR=/var/folders/0s/q_y0zhfj6xdd5n7rn780zz6h001qr7/T/
```
LLNL RHEL6:
```bash
(cab688):~$ env |grep TMP
TMPDIR=/var/tmp/gamblin2
TMP=/var/tmp/gamblin2
```
I'm inclined to stick with a default of whatever the OS / site recommends via `TMPDIR`, since that's what `TMPDIR` is for.  On OS X, `$TMPDIR` is actually more secure than other options b/c it's only accessible to your user.  Of course, I suspect most OS X users are on single-user laptops, so I'm not sure how much that really matters...

You can, of course, customize this in `lib/spack/spack/__init__.py`.  That will soon move to a more convenient config file, so hopefully that will make things easier.

You can get to the stage directory very easily if you source Spack's `setup-env.sh`:

```bash
    spack install foo@1.0 %gcc  # ... build fails
    spack cd foo@1.0 %gcc    # go directly to the stage directory for this spec.
```

When the build is successful, the build log is preserved in `$prefix/.spack/build.out`.  So are the build environment (`$prefix/.spack/build.env)` and all `package.py` files and patches used to build the package and its dependencies (`$prefix/.spack/repos`).

**Comment by davydden** [comment]
thanks for a detailed explanation, @tgamblin . That makes perfect sense.
