### ISSUE TITLE
Packaging of Intel Compilers

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#761]
I'm starting a new thread here to get going on the Intel compilers. Some of the previous issues #553 and #558 started the discussion.

There are a few decisions that need to be made regarding the Intel compilers. First, is the fact that there are 3 product suites. The product is Parallel Studio and the various suites are 1. Composer Edition, 2. Professional Edition, and 3. Cluster Edition. The first is just the compiler and some libraries, the second adds Inspector, Advisor, and VTune, and the third adds MPI and the Intel Trace Analyzer. I guess they could all be separate packages in spack that provide the Intel compiler. One can actually download one of the 3 suites or download each component separately. My personal preference would be to package each component separately. Thoughts?

Another issue will be how to point it to an appropriate license. In general, one can do this with the Intel compilers by 1. putting a .lic file in a specific directory in the compiler, 2. setting an INTEL_LICENSE_FILE env var, or 3. (an extension of 1) putting a .lic file in a few other set locations such as $HOME/intel/licenses and somewhere in /opt. At LLNL, we do option 1 since it doesn't require user intervention.

Yet another issue is how to deal with customizations. At LLNL, I do a few things post install. One is to create .cfg files that add the appropriate rpath to the compiler's lib dir. Another is to add some symlinks since the compiler installation is quite messy.

I already have something working that will just install the compilers without adding the license or doing any customizations, so it's just a matter of deciding what is the best way to implement those features. I am also open to the name of the package, which I plainly set at "intelcompilers".

Let me know what folks think about all of this or if there are other issues that will need to be addressed.

**Comment by lee218llnl** [comment]
Oh yeah, there's also an annoying issue that Intel software creates a $HOME/intel/intel_sdp_products.db file that tracks what was installed and where. When it finds that file, it will override your requested prefix and install additional software in the same prefix as what's in the .db file. I don't know if it would be evil for the spack package.py file to delete that.

**Comment by adamjstewart** [comment]
> One can actually download one of the 3 suites or download each component separately. My personal preference would be to package each component separately. Thoughts?

I don't have strong opinions either way. It seems like Intel wants them all installed in the same directory. Do they still work if installed in separate directories? It would be nice if the Intel MPI libraries could be installed separately so that one could depend on them instead of the entire suite. Does the license cover all products or just the compiler?

> Another issue will be how to point it to an appropriate license. In general, one can do this with the Intel compilers by 1. putting a .lic file in a specific directory in the compiler, 2. setting an INTEL_LICENSE_FILE env var, or 3. (an extension of 1) putting a .lic file in a few other set locations such as $HOME/intel/licenses and somewhere in /opt. At LLNL, we do option 1 since it doesn't require user intervention.

#558 should handle everything you need. In your package.py file, just include the following and let the installer decide:
```python
license_required = True
license_comment  = '#'
license_files    = ['license.lic',  '/opt/intel/licenses/license.lic']
license_vars     = ['INTEL_LICENSE_FILE']
license_url      = 'https://software.intel.com/en-us/articles/intel-composer-xe-2015-silent-installation-guide'
```
We can name `license.lic` whatever you want.

At Argonne, we use `INTEL_LICENSE_FILE` since we store our licenses on a dedicated license server. Do you know of any way to write a license.lic file that points to the server like with PGI?

> Yet another issue is how to deal with customizations. At LLNL, I do a few things post install. One is to create .cfg files that add the appropriate rpath to the compiler's lib dir. Another is to add some symlinks since the compiler installation is quite messy.

This is the main reason I think we need a package. Everyone is currently installing the Intel compilers in a different way. If we can standardize this, I think it would make debugging much easier. I am all for creating .cfg files and symlinks.

> I am also open to the name of the package, which I plainly set at "intelcompilers".

I would like consistency here. Personally, I prefer having `gcc`, `intel`, `pgi`, and `nag` packages since we already call the compilers `%gcc`, `%intel`, `%pgi`, and `%nag`. I am also open to renaming the packages something like `gcc-compilers`, `intel-compilers`, `pgi-compilers`, and `nag-compilers`.

**Comment by lee218llnl** [comment]
They will all work if separated, although there may be some automatic references like -mkl that won't work. Each of the 3 suites are different licenses... you pay for more, you get more! I will lean towards separating packages and using the individual package downloads.
I will add your suggested license specifications, but I guess I will either need to use your branch or wait for a merge.
This is what our license file looks like, which references the server:
cab687@lee218:cat /usr/local/etc/license.client.intel
SERVER taz4.llnl.gov 001A4A030401 28518
USE_SERVER
I am making the .cfg files with rpath a variant right now, and setting it to default. We can change this if there are objections. I will also make the symlinks a variant that defaults to True, that way folks can turn it off if it bothers them (and we can always change the default behaviour later).
I might vote for compilers-gcc, compiler-intel, etc. This would make them easy to find. This is an issue that we really need others to weigh in on... @tgamblin? Having the Intel compiler package simply named "intel" seems wrong to me.

**Comment by alalazo** [comment]
> I would like consistency here. Personally, I prefer having gcc, intel, pgi, and nag packages since we already call the compilers %gcc, %intel, %pgi, and %nag.

FWIW I also prefer that.

**Comment by luigi-calori** [comment]
I also would prefer "intel" : at our site the module used for setting up intel compiler is "intel" ( actually a folder "intel" containing the modules for the different installed versions like #498)

We currently have set up the Cluster Edition and have all the components installed in the same folder expanded from the same tar file, we use a license server and have 
INTEL_LICENSE_FILE env var pointing to the main folder where there is a server.lic file pointing to the license servers. the module contain
setenv  INTEL_LICENSE_FILE      "/cineca/prod/compilers/intel/cs-xe-2015/binary"
setenv LM_LICENSE_FILE          "server.lic"


I have (somehow) managed to compile modules with spack using our own intel compiler by doing this:


module load intel/<select our intel compiler version>
spack compiler add

then each time I want spack to install with intel compiler:

module load intel/<select our intel compiler version>

echo "-Xlinker -rpath=${INTEL_HOME}/ipp/lib/intel64 -Xlinker -rpath=${INTEL_HOME}/tbb/lib/intel64/gcc4.4 -Xlinker -rpath=${INTEL_HOME}/mkl/lib/intel64 -Xlinker -rpath=${INTEL_HOME}/lib/intel64" > ${SCRIPTPATH}/intel.cfg

for v in ICCCFG ICPCCFG IFORTCFG 
 do
   export $v=${SCRIPTPATH}/intel.cfg
 done

Do you think that the module load and env var set up would be anyway needed also if using intel installed with your module?

Thanks for the effort and let me know if further info on our side could be helpful

**Comment by lee218llnl** [comment]
@luigi-calori if the license is properly placed and the $PATH points to the compiler and the rpaths are set in the .cfg files, then I believe you should not have to load the module.
Regarding the package name, I might cave and settle on "intel".
I am still uncertain about the best way to manage the different software in the suites. The full cluster edition includes MPI, ITAC, MKL, DAAL, TBB, IPP, VTune, Advisor, Inspector, and some other little goodies. It certainly would be easiest to just package up the whole suite into one installation, but that lacks flexibility. The individual components tend to get releases more frequently than the whole suite and version numbers vary across the components. It is also a huge installation ~8GB, I believe. We could create variants for each component, but that can get messy.

**Comment by adamjstewart** [comment]
@lee218llnl @luigi-calori 

##### Reasons why packaging them separate would be better:

Everyone keeps telling me that Intel MPI and MKL (blas/lapack/fft) are great and fast, but I currently can't use them with Spack. I would love to be able to tell Spack to install a package and depend on MKL. We could tell it to depend on intel, but then we get into the debate of whether or not to consider intel to be a build dependency and it just gets complicated.

Another problem with packaging them together is which download do we use? I think my division has a license for Professional Edition, not Cluster Edition. If we package them separately, I think this problem would be solved. Otherwise, we might have to make separate intel-composer, intel-professional, and intel-cluster packages. Alternatively, we could find a way to add logic to download different versions based on variants. This kind of support is already needed for things like PGI, which has a different filename and checksum based on arch/OS. I was going to wait until after the better arch/OS support is merged to take a stab at this.

I think I personally prefer packaging them separately.

##### Reasons why packaging them together would be better:

Do Intel MPI and MKL have licenses? If so, it will be more cumbersome to have to setup a license for every single one.

Has anyone installed them in separate directories before? Do they work fine on their own? I'm currently having trouble with netcdf and netcdf-fortran now that we split them into separate packages.

**Comment by lee218llnl** [comment]
@luigi-calori @adamjstewart Like Adam, I can see reasons to package them both ways, so I think we will ultimately want to package both suites and individual components. I am already working with the various suites by using variants. Regarding the different downloads, this may not be a big problem. Users will have to download their own package and place it in a mirror anyway, which renames the tarball with the package name. The silent installation process is the same regardless and I think I can set up the variants so that you won't try to install more than is included in the download.
For individual components, like MKL, we can setup virtual packages and have the suites "provide" the installed components. I am continuing to work on this an will setup a branch for folks to look at when I have something more concrete.

**Comment by adamjstewart** [comment]
> Regarding the different downloads, this may not be a big problem. Users will have to download their own package and place it in a mirror anyway, which renames the tarball with the package name.

Ah, that makes it easy then. The only problem is that the checksums will be different. We will either need a package attribute to never check the md5sum (we don't have this yet, right?) or allow a version to have a list of checksums. Or we could make a separate package for each suite, but that sounds redundant if that's the only difference.

If we do make packages for both suites and individual components, I vote for the compiler to be named intel (or compiler-intel) and the suite to be named intel-suite.

> For individual components, like MKL, we can setup virtual packages and have the suites "provide" the installed components.

:+1:

**Comment by lee218llnl** [comment]
Perhaps we can name the suite intel-parallel-studio, since that is in fact the name of the product. If we want something shorter, we can use their ipsxe abbreviation.
For the compiler component, would it make sense to have the virtual package be called "intel" and have the separate package itself be called compiler-intel or intel-compiler?
Ugh, didn't think of checksums, that does indeed complicate things and I can't think of an easy solution. I guess we could provide a list as you suggest, but if we do that, then we may as well provide a list of filenames too. Knowing which download is being provided would be helpful anyway to determine what components could be installed. We could also make the 3 suites part of the version number/string. Right now, the version string is <year>.<release>, we could prefix "composer", "professional", or "cluster" to the version. Does spack allow alpha chars in versions?

**Comment by alalazo** [comment]
> For the compiler component, would it make sense to have the virtual package be called "intel" and have the separate package itself be called compiler-intel or intel-compiler?

@lee218llnl I am not sure I fully get this point... why do we need a virtual package for a compiler?

**Comment by lee218llnl** [comment]
@alalazo If we were just packaging up the compilers, then the virtual package would not be necessary. But since we may end up packaging the compiler by itself and also as part of the parallel studio suites, then I thought it may make sense to have the compiler be a virtual package.

**Comment by adamjstewart** [comment]
Let's hold off on making a virtual package for the compiler. If we decide that compilers should be build dependencies someday, then sure. Personally I think it would be cool to make a virtual package for all compilers and use them as build dependencies. It's just a matter of how Spack would handle that.

**Comment by KineticTheory** [comment]
@luigi-calori Thank you for posting your setup for Intel compilers in #761.  Your instructions allowed me to start building packages with Intel/15.0.5.  

Now, I am trying to build parmetis%intel@15.0.5 but the Intel compiler setup doesn't work because parmetis uses CC=mpicc and CXX=mpicxx and these wrappers don't seem to respect 
`$ICCCFG`. (cmake fails because_ the compiler is not able to compile a simple test program_; libimf.so is not found.) Do you have a similar solution that works for mpicc?  Our systems expect `LD_LIBRARY_PATH` to be set correctly to allow Intel compilers to work.

**Comment by luigi-calori** [comment]
@KineticTheory Sorry, I' m sure to have build parmetis with intel some time ago but now I' ve tried but got different errors, they could be related to the stus of my spack installation that is not clean.
Unfortunately I will be out for two days so not sure to be able to try a new installation.
I just posted my intel setup in order to let people who are working on spack intel installationn to take into account my situation.
I remember when I was working on intel compile there were some issues with packages using cmake but not parmetis.
Are you on an updated clean spack develop checkout.
In that case I could try to see if I' m able to build again parmetis with my setup ( which is far from clean ) Hope that current PR's will manage to make intel compiler fully compatible with spack

**Comment by KineticTheory** [comment]
@luigi-calori I moved my question (with a more complete description) to the spack forum: https://groups.google.com/forum/#!topic/spack/NtGbcJKtWB0

**Comment by lee218llnl** [comment]
I created pull request #796 with my initial Intel compiler package. Feedback would be much appreciated.

**Comment by lee218llnl** [comment]
PR #796 turned into a mess and has been cleaned up in #946.

**Comment by adamjstewart** [comment]
@lee218llnl I think this issue can be closed now.
